Microsoft/RTVS

- src/EditorTestApp/Microsoft.Languages.Editor.Application.csproj
- src/SetupRHost/SetupRHost.wixproj
- src/build.proj
- Fix *proj files so that every project uses its own intermediate folder
- Remove intermediate folder cleanup from build.proj
- Add RenameSetupBundle step to the build.proj
- Change default platform to "any cpu"
- Update submodule reference
> Several build related fixes

- src/Debugger/Engine/Impl/AD7Expression.cs
- src/Debugger/Engine/Impl/AD7Property.cs
- src/Debugger/Impl/DebugBreakpoint.cs
- src/Debugger/Impl/DebugEvaluationResult.cs
- src/Debugger/Impl/DebugSession.cs
- src/Debugger/Impl/DebugStackFrame.cs
- src/Debugger/Test/BreakpointsTest.cs
- src/Debugger/Test/ValuesTest.cs
- src/Package/Impl/DataInspect/EvaluationWrapper.cs
- src/R/Editor/Impl/Data/RSessionDataObject.cs
- src/R/Editor/Impl/Data/WorkspaceVariableProvider.cs
Remove `DebugEvaluationResultFields.All`, requiring callers to always explicitly specify the fields that they need.
(Computing `DebugEvaluationResult.NameCount` was triggering this behavior, but it wasn't actually used anywhere.)
> Fix #943: Remote Hadoop data sources cause Variable Explorer and debugger to refresh very slowly

- src/Package/Impl/Feedback/SendFrownCommand.cs
- src/Package/Impl/Feedback/SendMailCommand.cs
- src/Package/Impl/Feedback/SendMailFallbackWindow.xaml
- src/Package/Impl/Feedback/SendMailFallbackWindow.xaml.cs
- src/Package/Impl/Logging/DiagnosticLogs.cs
- src/Package/Impl/Microsoft.VisualStudio.R.Package.csproj
- src/Package/Impl/Resources.Designer.cs
- src/Package/Impl/Resources.resx
Always pop up Explorer with the log file selected, even when using Outlook.
Stop automatically attaching logs to email even when using Outlook, and change the text to give directions on how to do so manually.
Add basic diagnostic info (VS, RTVS and R versions) directly into the precomposed email body, so that it is present even if logs are not attached.
Use a custom non-modal window instead of the stock message box as a mailto: fallback, so that the entire body of the message is included there, and can be easily copy/pasted, in case mailto: handler didn't work for any reason.
> Fix #1205: Stop attaching logs to send a frown email

- src/Package/Test/DataInspect/EvaluationWrapperTest.cs
- src/Package/TestApp/Data/VariableExplorerTest.cs
- src/Package/TestApp/Utility/ViewTreeDump.cs
- src/Package/TestApp/Utility/VisualTreeObject.cs
- Visual tree dump saves after filter
- Compare properties only when not collapsed
> Unittest visual tree tests only when control is not collapsed

- src/Debugger/Impl/DebugBreakpoint.cs
- src/Debugger/Impl/DebugSession.cs
- src/Debugger/Test/BreakpointsTest.cs
- src/Debugger/Test/DebugSessionExtensions.cs
- src/Debugger/Test/Match.cs
- src/Debugger/Test/SteppingTest.cs
- src/Host/Client/Impl/Definitions/IRCallbacks.cs
- src/Host/Client/Impl/Definitions/IRSession.cs
- src/Host/Client/Impl/Definitions/IRSessionEvaluation.cs
- src/Host/Client/Impl/Definitions/IRSessionInteraction.cs
- src/Host/Client/Impl/Host/RHost.EvaluationRequest.cs
- src/Host/Client/Impl/Host/RHost.cs
- src/Host/Client/Impl/Microsoft.R.Host.Client.csproj
- src/Host/Client/Impl/Program.cs
- src/Host/Client/Impl/Session/RSession.cs
- src/Host/Client/Test/Mocks/RSessionInteractionMock.cs
- src/Host/Client/Test/Mocks/RSessionMock.cs
- src/Host/Client/Test/Session/RSessionTest.CancelAll.cs
Fix #541: Debugger Break command can take a very long time to break
Fix #547: Breakpoints are not instantly updated
Fix #1191: R Host process stop: unexpected host response, Escape key after browse(), no debugger
Add support for async background evals in RHost and RSession, such that they do not require queueing requests and waiting for the next prompt to run; and use those new evals to implement debugger break.
Use async background evals to set and remove breakpoints.
Add test for debugger break/continue.
Fix OverlappingBreakpoints test to properly set/remove breakpoints while at prompt (previous behavior inadvertently relied on breakpoint creation/deletion implicitly waiting for next prompt).
> Fix #541, #1191, 547

- src/R/Core/Impl/DataTips/RDataTip.cs
Since indexer is an unary operator in AST now, use Children.First() instead of LeftOperand to determine which part of it the child node belongs to.
> Fix #1338: DataTip for indexers is wrong

- src/Debugger/Impl/Microsoft.R.Debugger.csproj
- src/Debugger/Impl/rtvs/R/mirror.R
- src/Host/Client/Impl/Session/RSessionEvaluationCommands.cs
- src/Package/Impl/Options/R/RToolsOptionsPage.cs
- src/Package/Impl/Options/R/Tools/CranMirrorTypeConverter.cs
- src/Package/Impl/Options/R/Tools/RToolsSettingsImplementation.cs
- src/Package/Impl/RPackages/Mirrors/CranMirrorList.cs
- src/Package/Impl/Resources.Designer.cs
- src/Package/Impl/Resources.resx
- src/Package/Test/Cran/CranMirrorListTest.cs
Provide a way to not set any CRAN mirror via R Tools | Options at all, using whatever is set by R itself (e.g. via .Rprofile or other startup code) instead.
> Fix #915: Allow user to specify CRAN mirror via .Rprofile

- src/Debugger/Impl/DebugBreakpoint.cs
- src/Debugger/Impl/DebugSession.cs
- src/Debugger/Test/BreakpointsTest.cs
- src/Debugger/Test/DebugReplTest.cs
- src/Debugger/Test/SteppingTest.cs
- src/Host/Client/Impl/Definitions/IRExpressionEvaluator.cs
- src/Host/Client/Impl/Definitions/IRSession.cs
- src/Host/Client/Impl/Definitions/IRSessionContext.cs
- src/Host/Client/Impl/Definitions/IRSessionEvaluation.cs
- src/Host/Client/Impl/Microsoft.R.Host.Client.csproj
- src/Host/Client/Impl/Session/RSession.cs
- src/Host/Client/Impl/Session/RSessionEvaluation.cs
- src/Host/Client/Impl/Session/RSessionEvaluationCommands.cs
- src/Host/Client/Impl/Session/RSessionEvaluationSource.cs
- src/Host/Client/Impl/Session/RSessionExtensions.cs
- src/Host/Client/Test/Mocks/RSessionEvaluationMock.cs
- src/Host/Client/Test/Mocks/RSessionMock.cs
- src/Package/Impl/DataInspect/DataSource/GridDataSource.cs
- src/Package/Impl/DataInspect/Office/CsvAppFileIO.cs
- src/Package/Impl/DataInspect/REnvironmentProvider.cs
- src/Package/Impl/Help/HelpHomeCommand.cs
- src/Package/Impl/Help/ShowHelpOnCurrentCommand.cs
- src/Package/Test/DataInspect/VariableRHostScript.cs
- src/Package/TestApp/Data/VariableExplorerTest.cs
- src/R/Components/Test/PackageManager/PackageManagerIntegrationTest.cs
- src/R/Editor/Application.Test/Completion/IntellisenseTest.cs
- src/R/Editor/Impl/Completion/RCompletionController.cs
- src/R/Editor/Impl/Data/LoadedPackagesProvider.cs
- src/R/Support/Impl/Help/FunctionRdDataProvider.cs
R evaluation API unification - everything that can eval R code now implements `IRExpressionEvaluator`.
Require `REvaluationKind` to be specified to avoid bugs when not-mutating eval is inappropriate, and force callers to specify it explicitly either way. Fix existing callers accordingly.
Remove `isMutating` parameter from `BeginEvaluationAsync` - all evaluations now begin as non-mutating, and change if `REvaluationKind.Mutating` is used on any `EvaluateAsync` call for that evaluation.
> R evaluation API unification

- src/Host/Client/Impl/Host/RHost.cs
- src/Host/Client/Impl/Microsoft.R.Host.Client.csproj
- src/Host/Client/Impl/NativeMethods.cs
Fix #1318: cxxfunction: Error in system(cmd, intern = !verbose) : 'C:/Program' not found
Shorten path when setting R_HOME.
Fix #1432: If R\bin is in PATH, wrong R.dll is loaded
When adding R\bin to PATH when launching host, insert it at the beginning rather than at the end.
> Fix #1318, #1432

- src/Debugger/Engine/Impl/AD7StackFrame.cs
- src/Debugger/Engine/Impl/AD7Thread.cs
- src/Debugger/Impl/DebugEvaluationResult.cs
- src/Debugger/Impl/DebugSession.cs
- src/Debugger/Impl/DebugStackFrame.cs
- src/Debugger/Impl/rtvs/R/traceback.R
- src/Debugger/Test/CallStackTest.cs
- src/Debugger/Test/SourceFile.cs
When retrieving call stack, include formatted environment names for those environments that have them; and use those names in the Call Stack window when available.
Fix #702: Remove unnecessary stack frames from the call stack
> Retrieve environment names

- src/Debugger/Impl/rtvs/R/eval.R
- src/Debugger/Impl/rtvs/R/util.R
- src/Debugger/Test/ValuesTest.cs
Backtick-quote names as necessary.
> Fix  #1408: Evaluation children with names that are not identifiers do not work correctly

- src/Common/Core/Impl/Collections/ListExtensions.cs
- src/Common/Core/Impl/Extensions/StringExtensions.cs
- src/Host/Client/Impl/Session/RSessionEvaluationCommands.cs
- src/Package/Impl/PackageManager/PackageManagerWindowPane.cs
- src/Package/Impl/PackageManager/VsRPackageManagerVisualComponent.cs
- src/R/Components/Impl/PackageManager/IRPackageManager.cs
- src/R/Components/Impl/PackageManager/IRPackageManagerVisualComponentContainerFactory.cs
- src/R/Components/Impl/PackageManager/Implementation/RPackageManager.cs
- src/R/Components/Impl/PackageManager/Implementation/RPackageManagerVisualComponent.cs
- src/R/Components/Impl/PackageManager/Implementation/View/DesignTime/DesignTimeRPackageManagerViewModel.cs
- src/R/Components/Impl/PackageManager/Implementation/View/DesignTime/DesignTimeRPackageViewModel.cs
- src/R/Components/Impl/PackageManager/Implementation/View/PackageDetails.xaml
- src/R/Components/Impl/PackageManager/Implementation/View/PackageList.xaml
- src/R/Components/Impl/PackageManager/Implementation/View/PackageList.xaml.cs
- src/R/Components/Impl/PackageManager/Implementation/View/PackageManagerControl.xaml
- src/R/Components/Impl/PackageManager/Implementation/View/PackageManagerResources.xaml
- src/R/Components/Impl/PackageManager/Implementation/ViewModel/RPackageManagerViewModel.cs
- src/R/Components/Impl/PackageManager/Implementation/ViewModel/RPackageViewModel.cs
- src/R/Components/Impl/PackageManager/ViewModel/IRPackageManagerViewModel.cs
- src/R/Components/Impl/PackageManager/ViewModel/IRPackageViewModel.cs
- src/R/Components/Impl/Resources.Designer.cs
- src/R/Components/Impl/Resources.resx
- src/R/Components/Test/PackageManager/PackageManagerIntegrationTest.cs
- src/R/Wpf/Impl/Converters.cs
- Add Load/Unload/Update methods to RPackageManagerViewModel
- Make IPackageManager.InstallPackage / IPackageManager.UninstallPackage / IPackageManager.LoadPackage / IPackageManager.UnloadPackage async. Missing input in REPL will be fixed later: #1469
- Make InstallAsync/UninstallAsync refresh installed packages cause existing logic skips dependent packages
- Fix #1450: Update package crashes
- Fix #1454: Uninstall package crashes
- Fix #1456: Package manager loaded view doesn't refresh when session is mutated or reset
- Fix #1459: 'Sources' button on package manager does nothing
- Fix #1460: pk mgr: search currently search at beginning of name
- Fix #1463: Package manager detail view should have margin at bottom
> Package Manager VM Fixes

- src/R/Components/Impl/PackageManager/Implementation/View/PackageList.xaml
- src/R/Components/Impl/PackageManager/Implementation/ViewModel/RPackageManagerViewModel.cs
- Fix #1476: Tooltip for packages we haven't fetched description yet is empty
- Remove double UI update when Loaded tab is updated
> Couple fixes for Package Manager

- src/Common/Core/Test/Match/MatchAny.cs
- src/Common/Core/Test/Match/MatchElements.cs
- src/Common/Core/Test/Match/MatchMembers.cs
- src/Common/Core/Test/Microsoft.Common.Core.Test.csproj
- src/Debugger/Engine/Impl/AD7Property.cs
- src/Debugger/Engine/Impl/AD7StackFrame.cs
- src/Debugger/Impl/DebugEvaluationResult.cs
- src/Debugger/Impl/DebugStackFrame.cs
- src/Debugger/Impl/DebugValueEvaluationResult.cs
- src/Debugger/Impl/rtvs/R/breakpoints.R
- src/Debugger/Impl/rtvs/R/eval.R
- src/Debugger/Test/BreakpointsTest.cs
- src/Debugger/Test/JsonTest.cs
- src/Debugger/Test/Match/MatchDebugEvaluationResults.cs
- src/Debugger/Test/Microsoft.R.Debugger.Test.csproj
- src/Debugger/Test/SteppingTest.cs
- src/Debugger/Test/ValuesTest.cs
(and fixes to various minor code issues exposed by the tests)
Add value tests for promises and active bindings.
Add value tests for children of evaluation results.
Remove duplicate JSON test data.
Use ShouldBeOfType instead of As where appropriate, because the latter doesn't assert the type.
Fix expression for slots to enable assignment.
Always sort children of environments - not just for frames.
Add synthetic parent environment nodes to environments.
Disable BreakContinue test.
Fix #737: Variable Explorer doesn't show name of element in 1-element vector
> Fix #1136: Create debugger data inspection tests 

- src/R/Components/Impl/PackageManager/Implementation/ViewModel/RPackageViewModel.cs
- src/R/Components/Impl/PackageManager/Model/RPackageVersion.cs
- src/R/Components/Test/Microsoft.R.Components.Test.csproj
- src/R/Components/Test/PackageManager/PackageVersionTest.cs
Fixes https://github.com/Microsoft/RTVS/issues/1413
I left the data type on the view model as a string, it could be changed to RPackageVersion if we like that better.  I remember it used to be a RPackageVersion instance and got changed to a string at some point, but I'm not sure why.
> Add proper package version comparison.

- src/Package/Impl/DataInspect/DataImport/ImportDataWindow.xaml
- src/Package/Impl/PackageManager/VsRPackageManagerVisualComponent.cs
- src/R/Components/Impl/PackageManager/Implementation/View/PackageList.xaml
- src/R/Components/Impl/PackageManager/Implementation/View/PackageManagerControl.xaml
- src/R/Components/Impl/PackageManager/Implementation/View/Spinner.xaml
+ Adjust fix for #1507: VS crash: ObjectDisposedException for MarshalingWindowFrame (we don't actually need to show REPL when PM is loaded - we just need to start it).
> Fix XAML bindings

- src/Host/Client/Impl/Encodings/REncodingsMap.cs
- src/Host/Client/Impl/Extensions/RStringExtensions.cs
- src/Host/Client/Impl/Microsoft.R.Host.Client.csproj
- src/Package/Impl/DataInspect/DataImport/EnterUrl.xaml
- src/Package/Impl/DataInspect/DataImport/ImportDataWindow.xaml
- src/Package/Impl/DataInspect/DataImport/ImportDataWindow.xaml.cs
- src/Package/Impl/DataInspect/DataSource/GridDataSource.cs
- src/Package/Impl/Repl/Data/ImportDataSetTextFileCommand.cs
- src/Package/Impl/Resources.Designer.cs
- src/Package/Impl/Resources.resx
- src/R/Components/Impl/Resources.Designer.cs
- src/R/Components/Impl/Resources.resx
- src/R/Editor/Impl/Data/RSessionDataObject.cs
Display list of .NET encodings
Convert files to UTF-8 and import via UTF-8
Fixed display of UTF-8 in Data Frame preview
Fixed threading/WPF control access issues
Added *.txt to import list
Added progress bar
Added R Encodings table - not used atm, but may come useful at some point
> #1532: Encodings in Data Import dialog don't work correctly

- src/Debugger/Impl/rtvs/R/packages.R
- src/R/Components/Impl/PackageManager/Implementation/RPackageManager.cs
The only optimization that I've been aware of that hadn't been done.  I'll close https://github.com/Microsoft/RTVS/issues/1328 after this.
This reduces the length of the JSON by 100kb, saving on serialization/transport/deserialization, and removes the special case of empty lists on deserialization.
We'll also now be able to have the same package be listed twice for "installed packages", which was not possible before with named lists.  I'm still preventing duplicates from happening right now, as I'm not sure the UI would expect it, but we can stop removing duplicates later.
> Remove names from the package lists returned to VS.

- src/Common/Core/Impl/Diagnostics/RestartManager.cs
- src/Common/Core/Impl/Microsoft.Common.Core.csproj
- src/Host/Client/Impl/Definitions/IRSession.cs
- src/Host/Client/Impl/Host/RHost.cs
- src/Host/Client/Impl/Session/RSession.cs
- src/Host/Client/Test/Mocks/RSessionMock.cs
- src/R/Components/Impl/Microsoft.R.Components.csproj
- src/R/Components/Impl/PackageManager/IRPackageManager.cs
- src/R/Components/Impl/PackageManager/Implementation/RPackageManager.cs
- src/R/Components/Impl/PackageManager/Implementation/RestartManager.cs
- src/R/Components/Impl/PackageManager/Model/PackageLockState.cs
- src/R/Components/Test/PackageManager/PackageManagerIntegrationTest.cs
I haven't gotten the UI part to work successfully in the case where the user wants us to reset the repl for them before install/uninstall (Task returned BeginInteractionAsync is awaited forever), so it's just the backend + tests in this PR.
FYI RestartManager impl comes from VS.
> Package manager backend: detect package dll lock

- src/Languages/Core/Impl/Tokens/Tokenizer.cs
- src/Package/Impl/Utilities/ProjectUtilities.cs
- src/R/Components/Impl/Microsoft.R.Components.csproj
- src/R/Editor/Impl/Completion/Engine/RCompletionEngine.cs
- src/R/Editor/Impl/Signatures/SignatureHelpSource.cs
- src/R/Editor/Test/Completions/RCompletionSourceTest.cs
#1579 Crash viewing in Excel in specific scenario
- check for misc files solution
- add catching com exceptions just in case
#1574 It is possible to get duplicate signature sessions
- minor issue when caret is at the end of an unterminated string
- fix tokenizer so it actually creates token when opening quote is at the very end of the file
> #1574 #1579

- src/R/Components/Impl/PackageManager/Implementation/ViewModel/RPackageManagerViewModel.cs
- src/R/Components/Impl/Resources.Designer.cs
- src/R/Components/Impl/Resources.resx
User will be notified prior to uninstalling/updating package that it is locked and can't be uninstalled.
> Fix #1538: Package manager could warn user when uninstall didn't remove all files

- src/Debugger/Test/SteppingTest.cs
Correct line range. Also reorder statements so that there's no chance to hit assignment outside of the loop.
> Fix #1382: BreakContinue test is unstable

- src/Package/Impl/DataInspect/DataImport/ImportDataWindow.xaml.cs
- src/Package/Impl/Package.vsct
- src/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveWorkflowOperations.cs
- src/R/Editor/Application.Test/Completion/IntellisenseTest.cs
- Make temp file less 'temporary' so re-invoking command from history would work
- Reuse file name rather than generating it every time
- Don't delete converted file so command from history won't fail
- Add asserts to workflow operations that require UI thread calls
> #1551 read.csv behind Data Import dialog should appear in REPL

- src/Common/Core/Impl/Extensions/TaskExtensions.cs
- src/Common/Core/Impl/Tasks/EventTaskSource.cs
- src/Common/Core/Test/Microsoft.Common.Core.Test.csproj
- src/Common/Core/Test/Tasks/TaskExtensionsTest.cs
- src/UnitTests/Core/Impl/EventTaskSources.cs
- src/UnitTests/Core/Impl/Microsoft.UnitTests.Core.csproj
- src/UnitTests/Core/Impl/Threading/UIThreadHelper.cs
To ensure that exception is returned back to the synchronization context, or shown with Debug.Fail if there is no synchronization context that can be used
> Change implementation of TaskExtensions.DoNotWait 

- src/Debugger/Engine/Impl/AD7BoundBreakpoint.cs
- src/Debugger/Engine/Impl/AD7Engine.cs
- src/Debugger/Engine/Impl/AD7PendingBreakpoint.cs
- src/Debugger/Engine/Impl/AD7Property.cs
- src/Debugger/Impl/DebugActiveBindingEvaluationResult.cs
- src/Debugger/Impl/DebugBreakpoint.cs
- src/Debugger/Impl/DebugBrowseEventArgs.cs
- src/Debugger/Impl/DebugChildAccessorKind.cs
- src/Debugger/Impl/DebugErrorEvaluationResult.cs
- src/Debugger/Impl/DebugEvaluationResult.cs
- src/Debugger/Impl/DebugEvaluationResultFields.cs
- src/Debugger/Impl/DebugPromiseEvaluationResult.cs
- src/Debugger/Impl/DebugSession.cs
- src/Debugger/Impl/DebugSourceLocation.cs
- src/Debugger/Impl/DebugStackFrame.cs
- src/Debugger/Impl/DebugValueEvaluationResult.cs
- src/Debugger/Impl/DebugValueEvaluationResultFlags.cs
- src/Debugger/Impl/DebugValueRepresentation.cs
- src/Debugger/Impl/DebugValueRepresentationKind.cs
- src/Debugger/Impl/IDebugSessionProvider.cs
- src/Debugger/Impl/Microsoft.R.Debugger.csproj
- src/Debugger/Test/BreakpointsTest.cs
- src/Debugger/Test/DebugSessionExtensions.cs
- src/Debugger/Test/Match/MatchDebugStackFrames.cs
- src/Package/Impl/DataInspect/EvaluationWrapper.cs
- src/R.sln
Clean up the use of evaluation - ditch unnecessary helpers, don't use `BeginEvaluationAsync` where it's not necessary, do not tie `DebugEvaluationResult` to a stack frame.
Rename things so that they're more descriptive and/or not misleading.
Split types into separate source files for better readability.
Remove unused stuff.
Comments, comments everywhere!
> Debugger refactoring and cleanup

- src/Host/Client/Impl/ExecutionTracing/RExecutionTracer.cs
Swallow `RException` that comes from eval for `browser()`
> Fix #1697: Stop Debugging after Break crashes VS

- src/Package/Impl/Expansions/ExpansionClient.cs
Fix incorrect mapping when snipped is getting inserted as it needs to account for projections in REPL.
> #1672 Parameter alignment auto-formatting breaks Code Completion

- src/Host/Client/Impl/rtvs/R/breakpoints.R
- src/Package/Impl/Repl/Commands/SourceRScriptCommand.cs
- src/Package/Test/Repl/ReplCommandTest.cs
- src/R/Components/Impl/InteractiveWorkflow/IRInteractiveWorkflowOperations.cs
- src/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveWorkflowOperations.cs
Add support for encoding to SourceFile helper methods, and fix encoding handling in rtvs:::debug_source.
Use ITextDocument encoding when available in SourceRScript.
Enable SourceRScript command whenever there's an active REPL window, regardless of whether it is visible or not; and make it visible when command is invoked.
Add tests for SourceRScript.
> Fix #1725: Support non-system encoding for Source R Script command

- src/Package/Impl/Commands/CommandAsyncToOleMenuCommandShim.cs
- src/Package/Impl/Packages/R/PackageCommands.cs
- src/R/Components/Impl/Controller/IAsyncCommand.cs
- src/R/Components/Impl/InteractiveWorkflow/Commands/SourceRScriptCommand.cs
- src/R/Components/Impl/Microsoft.R.Components.csproj
- src/R/Components/Test/AssertionExtensions.cs
- src/R/Components/Test/Assertions/AsyncCommandAssertions.cs
- src/R/Components/Test/InteractiveWorkflow/RInteractiveWorkflowCommandTest.cs
- src/R/Components/Test/Microsoft.R.Components.Test.csproj
- Build fix (replaced RToolsSettings singleton with test-related ISettings instance)
- Move SourceRScriptCommand to the correct namespace
- Add AsyncCommandAssertions to simplify status checks
> SourceRScriptCommandTest fixes

- src/Debugger/Impl/AD7ErrorBreakpoint.cs
- src/Debugger/Impl/AD7ErrorBreakpointResolution.cs
- src/Debugger/Impl/AD7PendingBreakpoint.cs
- src/Debugger/Impl/Microsoft.R.Debugger.csproj
- src/Host/Client/Impl/rtvs/R/breakpoints.R
- src/Package/Impl/Packages/Attributes/ProvideDebugEngineAttribute.cs
- src/Package/Impl/Packages/R/RPackage.cs
Fix #1806: No error message for conditional and hit count breakpoints
Implement IDebugErrorBreakpoint2 and IDebugErrorBreakpointResolution2, and return them when binding a breakpoint of an unsupported kind (conditional, hit count, function etc).
Fix #1796: Do not advertise false capabilities for the debug engine
Expose all registry entries on the registration attribute, and default them all to false. Only set the supported features to true on the package.
Fix #1805: debug_source produces warning message
Do not specify encoding in call to parse() - it's ignored when parsing text rather than file.
> Fix #1806, #1796, #1805

- src/Package/Impl/Rules/Run.cs
- src/Setup/CpsRules.wxi
The new rule file run.xaml was missing from the installer, so it was going to the embedded resource as a fallback, but that was using the wrong namespace.
On dev machine everything worked since run.xaml is found in the build output rules subdir.
Fixes https://github.com/Microsoft/RTVS/issues/1864
> Project properties fix

- src/Package/Impl/Packages/R/RPackage.cs
Adjust priority to place it right after SQL, and next to Python.
> Fix ##1069: Placement of R project templates in New Project dialog is weird

- src/Package/Impl/Repl/Workspace/InterruptRCommand.cs
- src/Package/Impl/Utilities/VsDebuggerModeTracker.cs
- src/R/Components/Impl/InteractiveWorkflow/IDebuggerModeTracker.cs
- src/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveWorkflow.cs
- src/R/Components/Test/Fakes/Trackers/TestDebuggerModeTracker.cs
Move focus from editor back to REPL no more than once per debugger break mode change.
> Fix #1938: REPL steals focus from editor after breaking in debugger

- src/Host/Client/Impl/rtvs/R/grid.R
- src/Package/Impl/DataInspect/VisualGrid/SortOrder.cs
- src/Package/Impl/DataInspect/VisualGrid/TextVisual.cs
- src/Package/Impl/DataInspect/VisualGrid/VisualGrid.cs
- src/Package/TestApp/Data/GridDataTest.cs
Fix #1916: Data grid sorting - clicking anywhere on column header should work
Accept clicks anywhere within the boundaries of the header cell for sorting purposes.
Fix #1955: Character columns cannot be sorted in descending order
Use xtfrm() to convert non-numeric columns to sort-equivalent numeric sequences for sorting purposes. Gracefully handle errors when column cannot be sorted.
> Fix #1916, #1955

- src/R/Components/Impl/Plots/Implementation/View/RPlotManagerControl.xaml
- src/R/Components/Impl/Plots/Implementation/View/RPlotManagerControl.xaml.cs
This change moves the plot resolution tool tip to the Image UI element. This is to fix the following problem @huguesv identified:
Tool tip is shown when there is no plot.
> This change moves the plot resolution tool tip to the Image UI element.

- src/Package/Impl/DataInspect/VariableGridHost.xaml.cs
- src/Package/Impl/DataInspect/VariableGridWindowPane.cs
Detaches RSession Mutated event from VariableGridHost when VariableGridWindowPane is closed. Previously the event handler for RSession Mutated in VariableGridHost re-evaluated the expression even after closing the view window.
> Fixes #1959 This change detaches RSession Mutated event from VariableGridHost

- src/Package/Impl/Microsoft.VisualStudio.R.Package.csproj
- src/Package/Impl/ProjectSystem/RProjectFileGenerator.cs
- src/ProjectSystem/Impl/Project/FileSystemMirroringProjectFileGenerator.cs
Fixes https://github.com/Microsoft/RTVS/issues/1893
The advantage of fixing it in the project file generator is that projects created from RStudio that are later opened in VS will have a startup file set automatically.
Changing the template to create the .rxproj with the startup file set as part of the template would allow each template to set whatever startup file they want, instead of relying on the project file generator to pick one.  However, I haven't been able to get this to work, VS complains "The template specified cannot be found. Please check that the full path is correct."  The template looks valid to me, it's likely that we are missing project type registrations of some sort, and VS doesn't know what to do with a .rxproj project template.
Since we only have one project …
> Add StartupFile property generation to RProjectFileGenerator.

- src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.DirectoryCreated.cs
- src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.DirectoryDeleted.cs
- src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.DirectoryRenamed.cs
- src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.FileCreated.cs
- src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.FileDeleted.cs
- src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.FileRenamed.cs
- src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcherEntries.cs
- src/ProjectSystem/Impl/Interop/NativeMethods.cs
- src/ProjectSystem/Impl/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.csproj
- src/ProjectSystem/Impl/Utilities/PathExtensions.cs
- src/ProjectSystem/Test/IO/MsBuildFileSystemWatcherEntriesTest.cs
Maybe there is a better fix... Problem is that short path must be stored since after item is deleted, GetShortFilePath and GetLongFilePath no longer work. Alternative is to pass full path and root down to AddEntry...
> #1851 Solution Explorer should not show temporary files

- src/Languages/Editor/Impl/Projection/ProjectionBufferManager.cs
Effectively forgotten change. Edge tracking in all spans must match otherwise paste over will grow span in one buffer and shrink in another introducing overlapped spans which is bad.
> #1989 Error pasting in r markdown

- src/Host/Client/Impl/Definitions/IRCallbacks.cs
- src/Host/Client/Impl/Host/RHost.EvaluationRequest.cs
- src/Host/Client/Impl/Host/RHost.Message.cs
- src/Host/Client/Impl/Host/RHost.cs
- src/Host/Client/Impl/Program.cs
- src/Host/Client/Impl/Session/RSession.cs
- src/Host/Client/Impl/rtvs/R/overrides.R
- src/Host/Client/Impl/rtvs/R/util.R
Change protocol so that the type of every message (one-way notification, request, response) is encoded in the message name in a uniform way.
Rename associated APIs (send_message etc) for clarity.
> Improve protocol to simplify remoting

- src/Host/Client/Impl/Definitions/IMessageTransport.cs
- src/Host/Client/Impl/Definitions/PlotMessage.cs
- src/Host/Client/Impl/Definitions/REvaluationKind.cs
- src/Host/Client/Impl/Definitions/REvaluationResult.cs
- src/Host/Client/Impl/Extensions/RawEvalResultExtensions.cs
- src/Host/Client/Impl/Host/RHost.EvaluationRequest.cs
- src/Host/Client/Impl/Host/RHost.Message.cs
- src/Host/Client/Impl/Host/RHost.cs
- src/Host/Client/Impl/Microsoft.R.Host.Client.csproj
- src/Host/Client/Impl/Session/RSessionEvaluationCommands.cs
- src/Host/Client/Impl/Transports/WebSocketMessageTransport.cs
- src/Host/Client/Impl/rtvs/R/graphics.R
- src/Host/Client/Impl/rtvs/R/util.R
- src/Host/Client/Test/IdeGraphicsDeviceTest.cs
- src/Host/Client/Test/Microsoft.R.Host.Client.Test.csproj
- src/Host/Client/Test/RtvsPackage/BlobsTest.cs
- src/Host/Client/Test/RtvsPackage/JsonTest.cs
- src/Package/Impl/DataInspect/Office/CsvAppFileIO.cs
- src/R/Components/Impl/Plots/Implementation/PlotMessageExtensions.cs
- src/R/Components/Impl/Plots/Implementation/RPlotManager.cs
- src/R/Components/Test/Plots/PlotIntegrationTest.cs
#2023  Host can send binary blobs. Plots updated to use blobs. Added =r (raw) eval kind. First element in the message json now has the header [id, name, blob_count, <optional>request_id].
> #2023  Host can send binary blobs.

- src/Host/Client/Impl/rtvs/R/util.R
- src/R/Components/Impl/PackageManager/IRPackageManager.cs
- src/R/Components/Impl/PackageManager/Implementation/RPackageManager.cs
- src/R/Components/Impl/PackageManager/Implementation/ViewModel/RPackageManagerViewModel.cs
- src/R/Components/Impl/PackageManager/Model/PackageLockState.cs
- src/R/Components/Test/PackageManager/PackageManagerIntegrationTest.cs
Moved the code that checks for the package lock state to R-host. Added a rtvs util function to retrieve lock state. Generalized the search for dlls in a library.
> Remote package lock state check

- src/Package/Impl/DataInspect/VariableViewModel.cs
If a variable can be coerced to data.frame, and length is greater than 1, export to excel button is shown for that variable.
> Export to Excel restrictions relaxed.  Fixes #2155

- src/Host/Broker/Impl/Pipes/MessagePipe.cs
- src/Host/Broker/Impl/Sessions/Session.cs
- src/Host/Broker/Impl/Sessions/SessionManager.cs
- src/Host/Broker/Impl/Sessions/SessionsController.cs
- src/Host/Broker/Impl/Startup/Program.cs
- src/Host/Client/Impl/Host/LocalRHostConnector.cs
Don't register session until it has been started.
When handling pipe request, check for non-existent sessions or those for which the process is not running, and report error accordingly.
Add host process PID when logging host messages and stderr in broker.
Enable stderr and packet logging by default for local connections.
> Broker session management improvements

- src/Host/Broker/Impl/Microsoft.R.Host.Broker.csproj
- src/Host/Broker/Impl/Security/HttpBasicAuth/BaseBasicContext.cs
- src/Host/Broker/Impl/Security/HttpBasicAuth/BasicAppBuilderExtensions.cs
- src/Host/Broker/Impl/Security/HttpBasicAuth/BasicCredential.cs
- src/Host/Broker/Impl/Security/HttpBasicAuth/BasicDefaults.cs
- src/Host/Broker/Impl/Security/HttpBasicAuth/BasicEvents.cs
- src/Host/Broker/Impl/Security/HttpBasicAuth/BasicExceptionContext.cs
- src/Host/Broker/Impl/Security/HttpBasicAuth/BasicHandler.cs
- src/Host/Broker/Impl/Security/HttpBasicAuth/BasicMiddleware.cs
- src/Host/Broker/Impl/Security/HttpBasicAuth/BasicOptions.cs
- src/Host/Broker/Impl/Security/HttpBasicAuth/BasicSignInContext.cs
- src/Host/Broker/Impl/Security/HttpBasicAuth/IBasicEvents.cs
- src/Host/Broker/Impl/project.json
- src/Package/Impl/Microsoft.VisualStudio.R.Package.csproj
- src/Package/Impl/source.extension.vsixmanifest
- src/Setup/Assemblies.wxi
Remove references to Odachi.AspNetCore.Authentication.Basic, and move the corresponding code directly into the broker assembly, to avoid strong name / no strong name mix-up issues.
> Fix assembly strong name issues

- src/Host/Client/Impl/Session/RSession.cs
- src/R/Components/Impl/ConnectionManager/Implementation/ConnectionManager.cs
- `libPath` for local and remote were accidentally swapped
- `ActiveConnection` should be compared with the new connection rather than with `BrokerConnector.BrokerUri` (they are actually the same)
> 2 bug fixes

- src/Host/Broker/Impl/Interpreters/Interpreter.cs
- src/Host/Broker/Impl/Interpreters/InterpreterManager.cs
- src/Host/Broker/Impl/Interpreters/InterpreterOptions.cs
- src/Host/Broker/Impl/Sessions/SessionsController.cs
- src/Host/Broker/Impl/Startup/Startup.cs
- src/Host/Protocol/Impl/InterpreterInfo.cs
- any interpreters that were manually specified in broker config are added to the list if they verify successfully;
- all auto-detected interpreters are also added to the list, using GUIDs as identifiers;
- if interpreter ID is not specified in an incoming connection, the first interpreter from the list is used.
Add interpreter names (for use in any future UI that would list all available interpreters for the broker when configuring connection).
> Fix enumeration of interpreters for non-local scenarios:

- src/Host/Broker/Impl/Interpreters/InterpreterManager.cs
- src/Host/Broker/Impl/Lifetime/LifetimeManager.cs
- src/Host/Broker/Impl/NativeMethods.cs
- src/Host/Broker/Impl/Pipes/MessagePipe.cs
- src/Host/Broker/Impl/Pipes/ProcessHelpers.cs
- src/Host/Broker/Impl/Resources.Designer.cs
- src/Host/Broker/Impl/Resources.resx
- src/Host/Broker/Impl/Security/Claims.cs
- src/Host/Broker/Impl/Security/SecurityManager.cs
- src/Host/Broker/Impl/Sessions/Session.cs
- src/Host/Broker/Impl/Sessions/SessionManager.cs
- src/Host/Broker/Impl/Sessions/SessionsController.cs
- src/Host/Broker/Impl/Startup/Program.cs
Fixes a bug where the rhost process does not receive the user environment variables (%USERPROFILE%, %USERNAME%, etc) when it is started with a different user identity than the broker process. #2234
> Fix for environment variables for the logged on user

- src/Host/Client/Impl/Host/LocalBrokerClient.cs
Rename RTVS_HOST_CONSOLE env variable to RTVS_SHOW_CONSOLE, and fix the logic to properly respect its value - default should be hidden.
> Fix #2333: Do not display console window for local broker

- src/Host/Broker/Impl/RemoteUri/RemoteUriHelper.cs
- src/Host/Client/Impl/BrokerServices/RemoteUriWebService.cs
Previously favicon.ico requests would cause 404 from RHost which is normal. But the remoting code did not send this server error response back to RTVS/Browser.
> Fixes #2347 protocol errors are transmitted back to RTVS

- src/Host/Client/Impl/Definitions/IRSessionReconnectTransaction.cs
- src/Host/Client/Impl/Host/BrokerClient.cs
- src/Host/Client/Impl/Microsoft.R.Host.Client.csproj
- src/Host/Client/Impl/Resources.Designer.cs
- src/Host/Client/Impl/Resources.resx
- src/Host/Client/Impl/Session/RSession.cs
- src/Host/Client/Impl/Session/RSessionProvider.cs
- src/Host/Client/Test/Session/RSessionProviderTest.cs
- src/R/Components/Impl/ConnectionManager/Commands/ReconnectCommand.cs
- src/R/Components/Impl/ConnectionManager/IConnectionManager.cs
- src/R/Components/Impl/ConnectionManager/Implementation/ConnectionManager.cs
- src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionManagerViewModel.cs
- src/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveWindowVisualComponent.cs
- src/R/Components/Impl/Resources.Designer.cs
- src/R/Components/Impl/Resources.resx
- Fix #2372: Don't restore connection when new connection failed
- Fix #2362: Failed connection should have different message when there is no fallback
- Fix #2354: Connection progress doesn't dismiss when it can't connect
- Fix #2352: Various remote status don't agree as to where I'm connected
- Fix #2351: Reconnect button doesn't work (neither in CM nor in status bar)
> Several bug fixes

- src/Common/Core/Impl/TaskUtilities.cs
- src/Common/Core/Test/Tasks/TaskUtilitiesTest.cs
- src/Host/Client/Impl/Definitions/IRSessionReconnectTransaction.cs
- src/Host/Client/Impl/Definitions/IRSessionSwitchBrokerTransaction.cs
- src/Host/Client/Impl/Session/RSession.cs
- src/Host/Client/Impl/Session/RSessionProvider.cs
This pattern is used in `RSessionProvider` several times - when any individual session fails on any step of switch or reconnection transaction, there is no reason for other sessions to continue, so we cancel them.
> Extracted `WhenAllCancelOnFailure`

- src/R/Components/Impl/Plots/Implementation/View/DragSurface.cs
- src/R/Components/Impl/Plots/Implementation/View/RPlotDeviceControl.xaml
- src/R/Components/Impl/Plots/Implementation/View/RPlotDeviceControl.xaml.cs
- src/R/Components/Impl/Plots/Implementation/View/RPlotHistoryControl.xaml
- src/R/Components/Impl/Plots/Implementation/View/RPlotHistoryControl.xaml.cs
It was being too aggressive, starting drag & drop operations when it shouldn't.  The most problematic of which is when it was starting a drag & drop of plot while VS was in toolwindow drag & drop mode.
Fixes https://github.com/Microsoft/RTVS/issues/2374
> Fix drag drop of plot windows

- src/R/Wpf/Impl/CommonResources.xaml
Fixes #2414 
Here's what it looks like in all 3 themes:
> Update inactive session icon so it doesn't look cut off.

- src/Package/Impl/DataInspect/VariableView.xaml.cs
- src/R/Components/Impl/Microsoft.R.Components.csproj
- src/R/Components/Impl/Plots/Implementation/RPlotDeviceVisualComponent.cs
- src/R/Components/Impl/Plots/Implementation/RPlotHistoryVisualComponent.cs
- src/R/Components/Impl/Plots/Implementation/RPlotManager.cs
- src/R/Components/Impl/Plots/Implementation/View/PointEventArgs.cs
- src/R/Components/Impl/Plots/Implementation/View/RPlotDeviceControl.xaml.cs
- src/R/Components/Impl/Plots/Implementation/View/RPlotHistoryControl.xaml.cs
Partial fix for #2410 (makes keyboard context menu work plot history window, but not plot device window)
Fixes #2403 
Also makes the context menu key work in variable explorer (used to be just shift-f10).
> Plot window clear on session connect, context menu via keyboard

- src/Host/Broker/Impl/Microsoft.R.Host.Broker.csproj
- src/Host/Broker/Impl/Pipes/MessagePipe.cs
- src/Host/Broker/Impl/Pipes/PipeDisconnectedException.cs
- src/Host/Broker/Impl/Pipes/WebSocketPipeAction.cs
- src/Host/Broker/Impl/Sessions/Session.cs
- src/Host/Broker/Impl/Sessions/SessionManager.cs
- src/Host/Broker/Impl/Sessions/SessionStateChangedEventArgs.cs
- src/Host/Client/Impl/Extensions/RStringExtensions.cs
- src/Host/Client/Impl/Host/BrokerClient.cs
- src/Host/Client/Impl/Session/RSession.cs
- src/Host/Client/Impl/Session/RSessionEvaluationCommands.cs
- src/Host/Client/Impl/Session/RSessionProvider.cs
- src/Host/Client/Impl/rtvs/R/breakpoints.R
- src/Host/Client/Impl/rtvs/R/eval.R
- src/Host/Client/Impl/rtvs/R/graphics.R
- src/Host/Client/Impl/rtvs/R/grid.R
- src/Host/Client/Impl/rtvs/R/mirror.R
- src/Host/Client/Impl/rtvs/R/overrides.R
- src/Host/Client/Impl/rtvs/R/packages.R
- src/Host/Client/Impl/rtvs/R/repr.R
- src/Host/Client/Impl/rtvs/R/traceback.R
- src/Host/Client/Impl/rtvs/R/util.R
- src/Host/Protocol/Impl/Microsoft.R.Host.Protocol.csproj
- src/Host/Protocol/Impl/SessionInfo.cs
- src/Host/Protocol/Impl/SessionState.cs
Resolve #2425: Automatically save host state when connection to client is lost
Resolve #2427: Prompt to reload saved session state
Disable reconnecting to live sessions.
When client disconnects from a websocket connection to broker, have broker disconnect from the host, so that the latter can shut down.
When shutting down host due to disconnect, save workspace image.
When starting a new session, check for autosaved workspace image, and prompt user to reload it.
When VS is closed, gracefully terminate any running hosts instead of just disconnecting from them.
When switching from one connection to another, gracefully terminate the old host once the switch is successful.
Expose session state in /sessions endpoint in the broker.
> #2425, #2427 (autosaving and restoring session state)

- src/Common/Core/Impl/NativeMethods.cs
- src/Common/Core/Impl/Security/SecurityServices.cs
CredUIPromptForWindowsCredentials  does not provide a delayed save feature. Until we have a similar blessed mechanism with the newer API it seems better to use the older one. Fixes #2478
> Switched Credential UI back CredUIPromptForCredentials instead of CredUIPromptForWindowsCredentials

- src/Host/Client/Impl/rtvs/R/util.R
Change message so that it is applicable to situations where the disconnect was caused by VS and/or broker crashing or being forcibly terminated.
> Fix #2484: Reload .RData shows in local connection case

- src/SetupRemote/Product.wxs
This change adds restart as post install requirement. Restarting makes it more reliable at starting a LocalSystem service.
> Fixes issue with server installation.

- src/Host/Client/Impl/Resources.Designer.cs
- src/Host/Client/Impl/Resources.resx
- src/Host/Client/Impl/Session/RSession.cs
Improve exception handling when initializing the new session. For errors that will not cause other components to malfunciton later (e.g. setting codepage or mirror), print out the error, but continue. For errors that may cause major malfunctions, print out the detailed error and terminate the session immediately, but avoid VS crashing.
> Fix #2326: Crash after switching back to local

- src/Debugger/Impl/AD7CustomViewer.cs
- src/Host/Client/Impl/DataInspection/IREvaluationResultInfo.cs
- src/Host/Client/Impl/DataInspection/RActiveBindingInfo.cs
- src/Host/Client/Impl/DataInspection/RErrorInfo.cs
- src/Host/Client/Impl/DataInspection/REvaluationResultInfo.cs
- src/Host/Client/Impl/DataInspection/RPromiseInfo.cs
- src/Host/Client/Impl/DataInspection/RValueInfo.cs
- src/Host/Client/Test/DataInspection/ValuesTest.cs
Provide an environment-independent expression to the grid viewer, such that it can be evaluated in any environment with the same result.
> Fix #2535: Can't view list when inside a function and subsequent debugger hang

- src/Host/Broker/Impl/Security/TlsConfiguration.cs
- src/Host/Broker/Impl/Sessions/SessionManager.cs
Clean up user entries for users who have no remaining sessions.
Allow no SSL for remote in debug builds only, for ease of testing.
> Fix #2572: User count returned when connecting to remote is incorrect.

- src/Host/Client/Impl/rtvs/R/util.R
- src/R/Components/Impl/Plots/IRPlotDeviceVisualComponent.cs
- src/R/Components/Impl/Plots/Implementation/RPlotDeviceVisualComponent.cs
- src/R/Components/Test/Plots/RPlotIntegrationTest.cs
Had to adjust the exporting code, as it was relying on `selectplot` to change the active device, which it no longer does.
Add some tests to ensure active plot device doesn't get changed when it shouldn't.
Fixes https://github.com/Microsoft/RTVS/issues/2538
See also https://github.com/Microsoft/R-Host/pull/98
> Several plot operations no longer change the active graphics device.

- src/Common/Core/Impl/Microsoft.Common.Core.csproj
- src/Common/Core/Impl/Threading/AsyncReaderWriterLock.Queue.cs
- src/Common/Core/Impl/Threading/AsyncReaderWriterLock.cs
- src/Common/Core/Test/Threading/AsyncReaderWriterLockTest.cs
- src/Common/Core/Test/Threading/MainThreadAwaitableTest.cs
- Separated lock items queue from the rest of the logic
- Some new tests added
> Fix #2570: AsyncReaderWriterLock hangs on requesting WriterLock after cancellation

- src/Package/Impl/ProjectSystem/Commands/OpenCommandPromptCommand.cs
Fixes #2627
Please let me know if there are other locations where we don't use fully qualified paths.
> Create process should use fully qualified path to exe.

- src/Host/Client/Impl/Resources.Designer.cs
- src/Host/Client/Impl/Resources.resx
- src/Host/Client/Impl/Session/RSession.cs
- src/Host/Client/Impl/Session/RSessionProvider.cs
- src/Host/Client/Test/EventTaskSources.cs
- src/Host/Client/Test/Session/RSessionTest.cs
- src/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveEvaluator.cs
- src/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveWorkflow.cs
- src/R/Components/Impl/PackageManager/Implementation/RPackageManager.cs
- src/R/Components/Impl/Resources.Designer.cs
- src/R/Components/Impl/Resources.resx
- Fix #2639: Terminating R and then using REPL produces incorrect error
- Fix #2656: Reset doesn't work after RHost process is terminated
- Fix #2644: Package manager RHost session should use the name PackageManager
> 3 bug fixes

- src/Host/Client/Impl/Session/RSession.cs
This change reduces the chances of doing Forced RHost Terminations. Previously we ended up doing forced termination almost every time. This added to the overall delay while doing reset.
> Partial improvement to Reset REPL.

- src/Common/Core/Impl/Microsoft.Common.Core.csproj
- src/Common/Core/Impl/Security/SecurityService.cs
- src/Common/Core/Impl/Services/CoreServices.cs
- src/Common/Core/Impl/Services/ICoreServices.cs
- src/Common/Core/Impl/Shell/CoreShellExtensions.cs
- src/Common/Core/Impl/Threading/MainThreadExtensions.cs
- src/Common/Core/Test/Fakes/Shell/TestCoreServices.cs
- src/Host/Client/Impl/Host/RemoteBrokerClient.cs
- src/Host/Client/Impl/Host/RemoteCredentialsDecorator.cs
- src/Host/Client/Impl/Program.cs
- src/Package/Impl/Shell/VsAppShell.cs
Switch to main thread before taking the credentials lock, to avoid deadlocking when main thread is waiting on the currently executing task.
> Fix #2575: F5 hangs when Remote + Reset R Interactive is on

- src/Common/Core/Test/Fakes/Shell/TestCoreServices.cs
- src/Common/Core/Test/Fakes/Shell/TestCoreShell.cs
- src/Common/Core/Test/Fakes/Shell/TestMainThread.cs
- src/Common/Core/Test/Microsoft.Common.Core.Test.csproj
- src/Package/Impl/DataInspect/Definitions/IREnvironmentProvider.cs
- src/Package/Impl/DataInspect/REnvironmentProvider.cs
- src/Package/Impl/DataInspect/VariableView.xaml.cs
- src/Package/Test/DataInspect/REnvironmentProviderTest.cs
Cancel refresh operation in REnvironmentProvider when the latter is disposed.
> Fix #2625: NRE in Variable Explorer when closing VS

- src/Common/Core/Impl/Json/Json.cs
- src/Common/Core/Impl/Microsoft.Common.Core.csproj
- src/Common/Core/Impl/project.json
- src/Host/Client/Impl/Host/RHost.cs
- src/Package/Impl/SurveyNews/SurveyNewsFeedClient.cs
- src/R/Components/Impl/Plots/Implementation/PlotClipboardData.cs
Work around JamesNK/Newtonsoft.Json#862 by explicitly requesting no "smart" date parsing during JSON deserialization.
> Fix #2721: AF in cat(), argument type mismatch in protocol message

- src/Host/Client/Impl/Definitions/GuidList.cs
- src/Host/Client/Impl/Definitions/IRSessionSwitchBrokerTransaction.cs
- src/Host/Client/Impl/Host/RemoteBrokerClient.cs
- src/Host/Client/Impl/Microsoft.R.Host.Client.csproj
- src/Host/Client/Impl/Session/RSessionProvider.cs
- src/R/Components/Impl/ConnectionManager/Implementation/View/ConnectionManagerControl.xaml.cs
- src/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveEvaluator.cs
- src/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveWorkflow.cs
- src/R/Components/Impl/InteractiveWorkflow/SessionGuids.cs
- src/R/Components/Impl/Microsoft.R.Components.csproj
- src/R/Components/Impl/PackageManager/Implementation/RPackageManager.cs
- src/R/Editor/Test/Script/RHostScript.cs
- src/R/Support/Impl/Help/IntelliSenseRSession.cs
- src/Setup/Definitions.wxi
#2735 Setup no longer displays version of the product
#2753 Occasional deadlock in ValidateX509CertificateAsync 
- mostly workaround, rejecting calls on UI thread and added cancellation handling
#2750 Double-click on connection for switching no longer works 
Minor changes in session naming - consolidate session names in one place.
> #2735, #2750, #2753

- src/Host/Client/Impl/rtvs/R/grid.R
- src/Host/Client/Impl/rtvs/R/repr.R
- src/Package/TestApp/Data/GridDataTest.cs
Gracefully handle externalptr and other non-formattable values when processing grid data.
> Fix #2756: View() fails for list with externalptr

- src/Package/Impl/Repl/IActiveRInteractiveWindowTracker.cs
- src/Package/Impl/Repl/VsActiveRInteractiveWindowTracker.cs
- src/R/Components/Impl/ConnectionManager/Implementation/ConnectionManager.cs
- src/R/Components/Impl/InteractiveWorkflow/ActiveWindowChangedEventArgs.cs
- src/R/Components/Impl/InteractiveWorkflow/IRInteractiveWorkflow.cs
- src/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveEvaluator.cs
- src/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveWorkflow.cs
- src/R/Components/Impl/Microsoft.R.Components.csproj
- Added `RInteractiveWorkflow.ActiveWindowChanged` event that is used by `ConnectionManager`
- Changed `RInteractiveWorkflow.ActiveWindow` to return null until REPL is actually initialized
- Removed unused event from `IActiveRInteractiveWindowTracker`
> Fix #2736: Connection should not turn green until REPL opens

- src/Host/Client/Impl/Session/RSession.cs
- src/R/Components/Impl/InteractiveWorkflow/Commands/InterruptRCommand.cs
- src/R/Components/Test/InteractiveWorkflow/RInteractiveWorkflowCommandTest.cs
When interrupting R, do not cancel the current interaction request task until R confirms completion.
Disable "Interrupt R" command while it's running to prevent re-entrancy.
Fix interrupt test to wait for prompt before first checking command status.
> Fix #2671: Interrupt R is disabled but REPL is busy

- src/Host/Client/Impl/Definitions/IObjectViewer.cs
- src/Host/Client/Impl/Definitions/IRCallbacks.cs
- src/Host/Client/Impl/Definitions/IRSessionCallback.cs
- src/Host/Client/Impl/Host/NullRCallbacks.cs
- src/Host/Client/Impl/Host/RHost.cs
- src/Host/Client/Impl/Program.cs
- src/Host/Client/Impl/Session/RSession.cs
- src/Host/Client/Test/Script/RHostClientTestApp.cs
- src/Host/Client/Test/Session/RSessionTest.CancelAll.cs
- src/Host/Client/Test/Stubs/RSessionCallbackStub.cs
- src/Package/Impl/DataInspect/Viewers/ObjectDetailsViewerProvider.cs
- src/R/Components/Impl/InteractiveWorkflow/Implementation/RSessionCallback.cs
- src/R/Components/Impl/Plots/IRPlotDeviceVisualComponent.cs
- src/R/Components/Impl/Plots/Implementation/RPlotDeviceVisualComponent.cs
- src/R/Components/Impl/Plots/Implementation/RPlotManager.cs
- src/R/Components/Impl/Plots/Implementation/ViewModel/RPlotDeviceViewModel.cs
- src/R/Components/Impl/Plots/ViewModel/IRPlotDeviceViewModel.cs
- src/UnitTests/Core/Impl/FluentAssertions/TaskAssertions.cs
- `_cancelAllCts` now affects all requests in the loop
- `CompleteSwitchingBrokerAsync` waits for cancellation only 10 seconds, after that host will be terminated
- `RHost.CancelAllAsync` can be canceled even when message loop is stuck
- Couple of tests added
> Fix #2810: Switching workspaces during a long-running operation gets stuck

- src/Common/Core/Impl/Logging/Implementation/LoggingPermissions.cs
- src/Common/Core/Impl/Logging/Implementation/LoggingServices.cs
- src/Common/Core/Impl/Security/SecurityService.cs
- src/Common/Core/Impl/Services/CoreServices.cs
- src/Common/Core/Impl/Shell/IApplicationConstants.cs
- src/Common/Core/Test/Fakes/Shell/TestCoreServices.cs
- src/Host/Client/Impl/Program.cs
- src/Package/Impl/Feedback/ReportIssueCommand.cs
- src/Package/Impl/Feedback/SendFrownCommand.cs
- src/Package/Impl/Feedback/SendMailCommand.cs
- src/Package/Impl/Feedback/SendSmileCommand.cs
- src/Package/Impl/Options/R/Tools/LogLevelTypeConverter.cs
- src/Package/Impl/Options/R/Tools/RToolsSettingsImplementation.cs
- src/Package/Impl/Packages/R/PackageCommands.cs
- src/Package/Impl/Repl/VsRInteractiveWorkflowProvider.cs
- src/Package/Impl/Shell/ApplicationConstants.cs
- src/Package/Impl/Shell/VsAppShell.cs
- src/Package/Impl/Shell/VsTaskService.cs
- src/Package/Impl/source.extension.14.0.vsixmanifest
- src/Package/Impl/source.extension.15.0.vsixmanifest
- src/Package/Test/Feedback/FeedbackCommandTest.cs
- src/Package/Test/Fixtures/DisposeRInteractiveWorkflowFixture.cs
- src/R/Components/Impl/ConnectionManager/Implementation/ConnectionManager.cs
- CoreServices is no longer a MEF export, and is available through `ICoreShell.Services` property only
- Common.Core is added to vsix manifest as assembly
> Fix #2801: Simplify MEF dependencies in CoreServices

- src/Common/Core/Impl/Shell/ICoreShell.cs
- src/Common/Core/Test/Fakes/Shell/TestCoreShell.cs
- src/Host/Client/Impl/Session/RSession.cs
- src/Languages/Editor/Test/Fakes/Shell/TestEditorShell.cs
- src/Languages/Editor/Test/Shell/TestShellBase.cs
- src/Package/Impl/Shell/IdleTimeSource.cs
- src/Package/Impl/Shell/VsAppShell.cs
- src/R/Components/Impl/ConnectionManager/Implementation/ConnectionManager.cs
- src/R/Components/Impl/InteractiveWorkflow/Commands/SessionInformationCommand.cs
- src/R/Components/Impl/PackageManager/IRPackageManager.cs
- src/R/Components/Impl/PackageManager/Implementation/RPackageManager.cs
- src/R/Components/Impl/PackageManager/Implementation/View/DesignTime/DesignTimeRPackageManagerViewModel.cs
- src/R/Components/Impl/PackageManager/Implementation/View/DesignTime/DesignTimeRPackageViewModel.cs
- src/R/Components/Impl/PackageManager/Implementation/View/PackageDetails.xaml
- src/R/Components/Impl/PackageManager/Implementation/View/PackageDetails.xaml.cs
- src/R/Components/Impl/PackageManager/Implementation/ViewModel/RPackageManagerViewModel.cs
- src/R/Components/Impl/PackageManager/Implementation/ViewModel/RPackageViewModel.cs
- src/R/Components/Impl/PackageManager/ViewModel/IRPackageManagerViewModel.cs
- src/R/Components/Impl/PackageManager/ViewModel/IRPackageViewModel.cs
- src/R/Components/Impl/Resources.Designer.cs
- src/R/Components/Impl/Resources.resx
- src/Setup/VsToolsAssemblies.wxi
#2826 When no R present, show option to connect to remote
- show WS window when user says NO to install MRC
#2808 Clicking on library link in package manager in remote case
- make plain text when session is remote. Add check for folder existence
#2792 Microsoft.Data.ConnectionUI binaries are unsigned
- remove binaries since VS ships them and install even without SQL tools
#2817 Different prompt for remote
> #2792, #2808, #2817, #2826

- src/Package/Impl/Repl/VsRInteractiveWorkflowProvider.cs
- src/R/Components/Impl/ConnectionManager/Implementation/ConnectionManager.cs
- src/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveWorkflow.cs
`ConnectionManager` constructor is called directly from `RInteractiveWorkflow` constructor. `IRInteractiveWorkflowProvider.GetOrCreate` is accessed from many MEF importing constructors, so there is no guarantee that `ConnectionManager` instance will be created from UI.
Logic to show `Resources.NoLocalR` and launch R Client setup is moved to the `RInteractiveWorkflow.CreateVisualComponentAsync`. It is guaranteed to be called from UI thread and before REPL becomes visible, so there will be no false error messages.
@MikhailArkhipov , can you please take a look at the change?
> Remove UI thread-dependent code from `ConnectionManager` constructor.

- src/Host/Client/Impl/rtvs/R/grid.R
- src/Package/Test/DataInspect/EvaluationWrapperTest.cs
When performing cell-by-cell formatting because column-level format() was unapplicable, duplicate the behavior of the latter.
> Fix #2838: Collection-typed cells are formatted improperly in data grid

- src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionViewModel.cs
- src/R/Components/Test/ConnectionManager/ConnectionManagerViewModelTest.cs
- src/R/Components/Test/ConnectionManager/ConnectionViewModelTest.cs
- src/R/Interpreters/Test/Install/RInstallationTest.cs
- Fix #2908: Any # added to the server URL is immediately removed when you save
- Fix #2361: Workspaces window doesn't allow multiple connections that differ only by URL fragment
- Fix `RInstallationTest`
- More tests for `ConnectionViewModel` and `ConnectionManagerViewModel`
> #2361 and #2908

- src/Host/Client/Impl/Host/LocalBrokerClient.cs
- src/Languages/Editor/Impl/project.15.0.json
- src/Mocks/VisualStudio/project.15.0.json
- src/R/Components/Impl/ConnectionManager/Implementation/ConnectionManager.cs
- src/R/Components/Impl/ConnectionManager/Implementation/View/ConnectionManagerControl.xaml
- src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionViewModel.cs
- Pipe must be opened in async mode for the WaitForConnectionAsync to be cancellable. Otherwise token is ignored.
- We need to cancel on either process exit or user clicks cancel
- Actual issue is that broker derives log name from the connection name. Hence we need to make sure the name is reasonably clean.
- Also fixed the issue when typing bad connection names crashed VS
> #2954 Can't connect to custom local interpreter

- src/Common/Core/Impl/Extensions/MatcherExtensions.cs
- src/Common/Core/Impl/Microsoft.Common.Core.csproj
- src/Package/Impl/ProjectSystem/Commands/SendToRemoteCommand.cs
- src/Package/Impl/ProjectSystem/ProjectProperties.cs
- src/ProjectSystem/Impl/Extensions/ProjectTreeExtensions.cs
Applies file filter while sending files using "send to remote" command. Exception to this rule is when the user selects file(s) to be sent, then that/those file(s) will be sent always.
> Fixes the issue where sent to remote did not apply the filter.

- src/R/Editor/Application.Test/Formatting/AutoFormatTest.cs
- src/R/Editor/Impl/Formatting/AutoFormat.cs
- src/R/Editor/Impl/Selection/RSelectionTracker.cs
The issue was twofold:
1). Caret positioning after formatting was incorrect. For example, in 
`x |<- 1`
typing ENTER produced
```
x
<|- 1
```
because caret position tracker only tracked changed range and offset from `x` was incorrect since autoformat removes trailing space. The fix is to for the tracking range to include next line do next token after the CRLF will be seen.
2). In
```
s <- 
"
string
"|x <- 1
```
upon ENTER formatter attempted to format `    "` not seeing that it is inside the string.
> #2974 Can not input line break between " and other command.

- src/Common/Core/Impl/IO/IUserProfileNamedPipeFactory.cs
- src/Common/Core/Impl/Microsoft.Common.Core.csproj
- src/Host/Protocol/Test/Microsoft.R.Host.Protocol.Test.csproj
- src/Host/Protocol/Test/UserProfileServicePipe/UserProfileServicePipeTest.cs
- src/Host/Protocol/Test/UserProfileServicePipe/UserProfileTestNamedPipeTestStreamFactory.cs
- src/Host/UserProfile/Impl/RUserProfileService.cs
- src/Host/UserProfile/Impl/RUserProfileServicesHelper.cs
Fixes #3012. The named pipe server in user-profile service only accepts connections from a network service. Since the tests run as user the connection is not authorized. Added a factory interface to create a server pipe for testing that does not require client to be a network service.
> Fixes to user profile tests.

- src/R/Components/Impl/Plots/IRPlotDeviceVisualComponent.cs
- src/R/Components/Impl/Plots/IRPlotManager.cs
- src/R/Components/Impl/Plots/Implementation/Commands/PlotDeviceCommand.cs
- src/R/Components/Impl/Plots/Implementation/Commands/PlotDeviceEndLocatorCommand.cs
- src/R/Components/Impl/Plots/Implementation/RPlotDeviceVisualComponent.cs
- src/R/Components/Impl/Plots/Implementation/RPlotManager.cs
- src/R/Components/Impl/Plots/Implementation/ViewModel/RPlotDeviceViewModel.cs
- src/R/Components/Impl/Plots/ViewModel/IRPlotDeviceViewModel.cs
- src/R/Components/Test/Plots/RPlotIntegrationTest.cs
Fix #3011 Assert and sometimes hang when quitting VS after using locator function
Fix #2939 LocatorCommandNoClick test fails with NRE
Change plot manager so `StartLocatorModeAsync` doesn't need to switch to the main thread, same for the code that ends locator mode.
This means that the `_devices` list is now being accessed from multiple threads, before it used to be guaranteed from main thread only. I'm locking around the use of the list, but I don't know if I need to go further and protect the device object themselves. I'm worried about introducing new deadlocks so close to release.
The view model state updates itself by listening to the plot manager plot device object LocatorModeChanged event, by posting to the main thread.
Scenarios that now work that used to be causing issues:
- Call …
> Prevent hang after using locator()

- src/Package/Impl/DataInspect/Viewers/GridViewer.cs
- src/Package/Test/DataInspect/ViewersTest.cs
Disable grid viewer for 1D collections that only have a single element in them.
> Fix #3090: Grid is enabled for single-element collections

- src/Host/Client/Impl/Definitions/IMessageTransport.cs
- src/Host/Client/Impl/Host/RHost.cs
- src/Host/Client/Impl/Transports/WebSocketMessageTransport.cs
- src/Package/Impl/History/Commands/LoadHistoryCommand.cs
RHost can fail at any time after start, including the moment when RTVS requests the handshake.
> Fix  #3091: WebSocketMessageTransport.ReceiveAsync null return value isn't handled

- src/Host/API/Impl/RSessionCallback.cs
- src/Host/Client/Impl/Definitions/IRCallbacks.cs
- src/Host/Client/Impl/Definitions/IRSessionCallback.cs
- src/Host/Client/Impl/Host/NullRCallbacks.cs
- src/Host/Client/Impl/Host/RHost.cs
- src/Host/Client/Impl/Program.cs
- src/Host/Client/Impl/Session/RSession.cs
- src/Host/Client/Impl/rtvs/R/util.R
- src/Host/Client/Test/Script/RHostClientTestApp.cs
- src/Host/Client/Test/Stubs/RSessionCallbackStub.cs
- src/Package/Test/DataInspect/EvaluationWrapperTest.cs
- src/R/Components/Impl/InteractiveWorkflow/Implementation/RSessionCallback.cs
- src/R/Components/Impl/Resources.Designer.cs
- src/R/Components/Impl/Resources.resx
Add an R helper function to get localizable strings from the IDE, and use it for all user-visible string literals in R code.
This depends on https://github.com/Microsoft/R-Host/pull/109
> Fix #3140: Move message text from R code to C#

- src/Host/Client/Impl/Host/RemoteBrokerClient.cs
- src/Host/Client/Impl/Resources.Designer.cs
- src/Host/Client/Impl/Resources.resx
- src/Host/Client/Impl/Session/RSession.cs
Block non http:// URLs in remote sessions.
> Fix #3119: ggvis sample crashes on remote

- src/R/Components/Impl/ConnectionManager/Implementation/View/ConnectionManagerControl.xaml
- src/R/Components/Impl/ConnectionManager/Implementation/View/ConnectionManagerControl.xaml.cs
- src/R/Components/Impl/ConnectionManager/Implementation/View/DesignTime/DesignTimeConnectionManagerViewModel.cs
- src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionManagerViewModel.cs
- src/R/Components/Impl/ConnectionManager/ViewModel/IConnectionManagerViewModel.cs
- src/R/Components/Impl/Resources.Designer.cs
- src/R/Components/Impl/Resources.resx
- src/R/Components/Test/ConnectionManager/ConnectionManagerViewModelTest.cs
- src/R/Wpf/Impl/CommonResources.xaml
- Fix #3199: Focus doesn't switch from one line in Workspaces to another
- Fix #3172: Unable to get to connection fields with keyboard
- Fix #3171: Narrator: Entries in Workspace window are read as class names
> Accessibility for Workspaces Window

- src/Host/API/Impl/Definitions/IRObjectInformation.cs
- src/Host/API/Impl/RHostSession.Interop.cs
- src/Host/API/Impl/RHostSessionExtensions.cs
- src/Host/Client/Impl/DataInspection/IRValueInfo.cs
- src/Host/Client/Impl/DataInspection/RValueInfo.cs
- src/Host/Client/Impl/rtvs/R/eval.R
- src/Package/Impl/DataInspect/DataImport/ImportDataWindow.xaml.cs
- src/Package/Impl/DataInspect/DataSource/Grid.cs
- src/Package/Impl/DataInspect/DataSource/GridRange.cs
- src/Package/Impl/DataInspect/DataSource/IGrid.cs
- src/Package/Impl/DataInspect/DataSource/IGridProvider.cs
- src/Package/Impl/DataInspect/DataSource/ListToRange.cs
- src/Package/Impl/DataInspect/DataSource/Range.cs
- src/Package/Impl/DataInspect/DefaultHeaderData.cs
- src/Package/Impl/DataInspect/GridDataProvider.cs
- src/Package/Impl/DataInspect/Viewers/GridViewer.cs
- src/Package/Impl/DataInspect/VisualGrid/ColumnSortOrder.cs
- src/Package/Impl/DataInspect/VisualGrid/GridPoints.cs
- src/Package/Impl/DataInspect/VisualGrid/HeaderTextVisual.cs
- src/Package/Impl/DataInspect/VisualGrid/Indexer.cs
- src/Package/Impl/DataInspect/VisualGrid/TextVisual.cs
- src/Package/Impl/DataInspect/VisualGrid/VisualGrid.cs
- src/Package/TestApp/Data/GridDataTest.cs
- src/R/Editor/Impl/Data/IRSessionDataObject.cs
- src/R/Editor/Impl/Data/RSessionDataObject.cs
Use 64-bit integers for number of elements / rows / columns, and the corresponding indices.
Guard against objects with extremely large extents in one or more dimensions.
> Fix #3205: VE crash for objects with length exceeding 32-bit

- src/Host/Client/Impl/Session/RSessionProvider.cs
- src/Host/Client/Impl/rtvs/R/util.R
Do not request localized strings from client in autosave-on-shutdown code.
Dispose broker when it is removed from the session provider.
> Fix #3209: After running tests R.Host.exe processes do not terminate

- src/R/Components/Impl/PackageManager/Implementation/View/PackageList.xaml
- src/R/Components/Impl/PackageManager/Implementation/ViewModel/RPackageManagerViewModel.cs
- src/R/Components/Impl/Resources.Designer.cs
- src/R/Components/Impl/Resources.resx
The reason why we get "cyclic namespace dependency" error isn't clear, especially after CRAN mirror was successfully updated, but error message now remain visible until list installed packages are loaded or explicitly dismissed.
> Fix #3217: Sometime package manager appears empty

- src/Debugger/Impl/DebuggerConstants.cs
- src/Debugger/Impl/PortSupplier/RDebugPortSupplier.DebugProcess.cs
- src/Debugger/Impl/PortSupplier/RDebugPortSupplier.cs
- src/Debugger/Impl/Resources.Designer.cs
- src/Debugger/Impl/Resources.resx
- src/Package/Impl/Utilities/VsDebuggerModeTracker.cs
- src/R/Components/Impl/InteractiveWorkflow/IDebuggerModeTracker.cs
- src/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveWorkflow.cs
- src/R/Components/Test/Fakes/Trackers/TestDebuggerModeTracker.cs
- src/R/Core/Impl/Formatting/RFormatter.cs
- src/R/Core/Test/Formatting/FormatConditionalsTest.cs
- src/R/Core/Test/Formatting/FormatOperatorsTest.cs
- src/R/Editor/Application.Test/Completion/IntellisenseTest.cs
- src/R/Editor/Impl/Completion/RCompletionController.cs
- src/R/Editor/Impl/Formatting/RangeFormatter.cs
#3264 R Interactive steals focus when debugging Python.
- add explicit check for R debugger session
#3260 Making a pipeline marks other code sections as touched
- start of expression locator returned relative position rather than absolute
#3262 Typing ::: sometimes gets messed up
- in case of typing `stats:::` in front of the existing member last `:`completed to the member and then `:` appeared after the member name. ':` should only complete right after the package name and not after another `:`.
#3261 Inconsistent formatting of spaces around = 
- brace handler is not active for partial formatting so we have to always use option for spaces around `=`, not just in arguments. However, using `=` instead of `<-` is highly discouraged and if someone does want to use it, default is to put …
> 3260, 3261, 3262, 3264

- src/Package/Impl/History/HistoryWindowPane.cs
- src/Package/Impl/Repl/Editor/KeyProcessor.cs
- src/Package/Impl/Repl/Editor/KeyProcessorProvider.cs
- Fix #3148: Keyboard navigation in history window is difficult
- Fix #3244: RTVS RC1 Errors and Latest PTVS
- Fix #3259: Null reference in VsAppShell.get_ThreadId()
> Port of PR #3272

- src/Languages/Editor/Impl/Projection/ProjectionBufferManager.cs
- src/Markdown/Editor/Impl/Tokens/MdTokenizer.cs
- src/Markdown/Editor/Test/Tokens/TokenizeBlockTest.cs
- src/R/Editor/Application.Test/Completion/IntellisenseTest.cs
- src/R/Editor/Impl/Completion/Providers/FilesCompletionProvider.cs
- src/R/Editor/Impl/Data/WorkspaceVariableProvider.cs
#3292 Brace matcher exception
- off by one error in markdown tokenizer. Fixed, added test.
#3293 Multiple nesting in a$b$c does not bring completion
- incorrect check for `exists`. Fixed, added test.
#3294 File completion resolves ./ incorrectly
- added support for `./` + test.
> 3292, 3293, 3294

- src/Package/Impl/RClient/MicrosoftRClientInstaller.cs
- src/R/Components/Impl/ConnectionManager/Implementation/ConnectionManager.cs
- src/R/Interpreters/Impl/Implementation/RInstallation.cs
- src/R/Interpreters/Impl/Implementation/SqlRClientInstallation.cs
The problem is that MRC installs over existing bits but does not remove old registry keys. So we end up seeing 3.2.2 and 3.3.2 pointing to the same path. Fetching first from the set take 3.2.2. Fixes
a) Stop special casing SQL. It is already in the registry anyway.
b). Take all found engines, select Microsoft ones, de-duplicate by install location and take highest version.
c). In connection manager always replace automatically detected engines since path can be the same but name can change after the upgrade.
d) Fix MRC download link.
> 3325 (Release 1.0)

- loc/lcl/CHS/Microsoft.R.Components.dll.lcl
- loc/lcl/CHT/Microsoft.R.Components.dll.lcl
- loc/lcl/CSY/Microsoft.R.Components.dll.lcl
- loc/lcl/DEU/Microsoft.R.Components.dll.lcl
- loc/lcl/ESN/Microsoft.R.Components.dll.lcl
- loc/lcl/FRA/Microsoft.R.Components.dll.lcl
- loc/lcl/ITA/Microsoft.R.Components.dll.lcl
- loc/lcl/JPN/Microsoft.R.Components.dll.lcl
- loc/lcl/KOR/Microsoft.R.Components.dll.lcl
- loc/lcl/PLK/Microsoft.R.Components.dll.lcl
- loc/lcl/PTB/Microsoft.R.Components.dll.lcl
- loc/lcl/RUS/Microsoft.R.Components.dll.lcl
- loc/lcl/TRK/Microsoft.R.Components.dll.lcl
- src/Host/Client/Impl/Host/RHost.cs
- src/Host/Client/Impl/rtvs/R/util.R
- src/R/Components/Impl/Resources.Designer.cs
- src/R/Components/Impl/Resources.resx
**Fix for VS 2017 1.0**
Long story in #3337. 
Basically we can't be using `message`, `warning`, `sprintf`, `winDialog` and friends in R to output localized content. They depend on currently set R locale. `winDialog` doesn't seem to be able to handle UTF-8 and tries to convert to OEM. `sprintf` appears to need proper C++ locale set (probably cp65001) to be able to handle UTF-8.
So the fix is to handle everything at the client.
- locstr removed
- added `loc_message`, `loc_warning`, `loc_yesno` and the respective parts in host
- host now supports `string.format` like functionality
- patched lcl files since `%s` changed to .NET formatting `{0}`
> #3337 On localized VS and OS messages in rtvs package are converted incorrectly 

- src/Host/Client/Impl/Definitions/IRCallbacks.cs
- src/Host/Client/Impl/Definitions/IRSessionCallback.cs
- src/Host/Client/Impl/Host/NullRCallbacks.cs
- src/Host/Client/Impl/Host/RHost.cs
- src/Host/Client/Impl/Program.cs
- src/Host/Client/Impl/Session/RSession.cs
- src/Host/Client/Test/Script/RHostClientTestApp.cs
- src/Host/Client/Test/Stubs/RSessionCallbackStub.cs
- src/Package/Impl/DataInspect/Viewers/FileEditor.cs
- src/R/Components/Impl/InteractiveWorkflow/Implementation/RSessionCallback.cs
- Rename `EditFile` into `EditFileAsync`
- Extract `FileEditor. _cookie` and `FileEditor. _tcs` into separate class to avoid concurrent access
- Register `FileEditor. _tcs` for cancellation
- Remove unnecessary `Task.Run`
> Fix cancellationToken

- src/Common/Core/Impl/Security/CredentialHandle.cs
- src/Common/Core/Impl/Security/SecurityService.cs
- src/Host/Client/Impl/Host/RemoteBrokerClient.cs
- src/Host/Client/Impl/Host/RemoteCredentialsDecorator.cs
- src/Package/Impl/Expansions/ExpansionClient.cs
- src/Package/Impl/ProjectSystem/PropertyPages/Run/RunPageControl.xaml
- src/Package/Impl/ProjectSystem/PropertyPages/Run/RunPageViewModel.cs
#3356 Crash on create new remote workspace 
- We really should not be throwing Win32 exceptions. Complete rework is out of question in Release/1_0 so I plumbed console output in one place and direct message box in another. Unfortunately, passing down ICoreShell is way too big change. Also, UI is frozen for localization, so reusing message from Core.
#2610 Snippets are not respecting trailing spaces 
- just check for standalone operator and bypass formatting
> #2610 #3356

- src/Common/Core/Impl/Diagnostics/Check.cs
- src/Common/Core/Impl/Extensions/IOExtensions.cs
- src/Common/Core/Test/Extensions/IOExtensionsTest.cs
- src/Host/Client/Impl/Blobs/DataTransferSession.cs
- src/Host/Client/Impl/rtvs/R/util.R
- src/Package/Impl/Publishing/Handlers/RmdPublishHandler.cs
- src/Package/Impl/Utilities/ProjectUtilities.cs
- src/Package/Impl/Utilities/VsUIShellExtensions.cs
The problem: we use TEMP path in local and remote. This breaks workflow when markdown has R code that sources files or reads CSV - basically any operation that involves paths.
Fix: provide work folder to the publishing code. 
1. Standalone file: use TEMP as before.
2. Project: work folder path is relative to the current working directory. Handle remote mapping as well.
```
source('./script.R') # x <- c(1:10)
```
```
plot(x)
```
work correctly in local and remote as long as file is in project.
> #3426 VS2015+RTVS on Win 10 not setting working directory of a project 

- src/Common/Wpf/Impl/Extensions/VisualTreeExtensions.cs
- src/Common/Wpf/Impl/LambdaConverter/StyleSetterExtension.cs
- src/Common/Wpf/Impl/Microsoft.Common.Wpf.csproj
- src/Package/Impl/DataInspect/Commands/CopyVariableCommand.cs
- src/Package/Impl/DataInspect/Commands/CopyVariableValueCommand.cs
- src/Package/Impl/DataInspect/Commands/DeleteVariableCommand.cs
- src/Package/Impl/DataInspect/Commands/OpenVariableInCsvCommand.cs
- src/Package/Impl/DataInspect/Commands/ShowVariableDetailsCommand.cs
- src/Package/Impl/DataInspect/Commands/VariableCommandBase.cs
- src/Package/Impl/DataInspect/DataGridStyle.xaml
- src/Package/Impl/DataInspect/TreeGrid/TreeGrid.cs
- src/Package/Impl/DataInspect/VariableView.xaml
- src/Package/Impl/DataInspect/VariableView.xaml.cs
- src/Package/Impl/DataInspect/VariableWindowPane.cs
- src/Package/Impl/Microsoft.VisualStudio.R.Package.csproj
- src/Package/Impl/Package.vsct
- src/Package/Impl/Wpf/VsWpfOverrides.cs
- src/R/Wpf/Impl/Brushes.cs
- Variable tree view is accessible by tab navigation, but inside it can be navigated only by arrows (left/right arrow expands/collapses the record). This is a common behavior for many tree views across windows and VS. Tab navigation switches between environments combobox and list of variables
- Buttons on variable records aren't accessible by keyboard anymore. Making them a tab stop creates an additional mess and makes it really hard to get out of the list. Buttons are available on the toolbar, which is accessible by Shift+Alt. Also, "Show details" can be invoked by hitting "Enter"
- Variable explorer focus is preserved when user switches to the toolbar or to the environments combobox
> Fix Variable Explorer accessibility

- src/Package/Impl/DataInspect/VariableView.xaml
Here is one of the things that is different in `VariableView`
> Attempt to fix #3468: Can't open Variable Explorer in 2017.2

- src/Host/Client/Impl/rtvs/R/grid.R
- src/Package/TestApp/Data/GridDataTest.cs
Use time() for ts, and zoo::index() for zoo, in lieu of row.names() when the latter is absent.
> Fix #3231: View() does not show row names for ts and zoo

- src/Common/Core/Impl/Extensions/TaskExtensions.cs
- src/Common/Core/Impl/Testing/ITestEnvironment.cs
- src/UnitTests/Core/Impl/Threading/ParallelTools.cs
- src/UnitTests/Core/Impl/XUnit/TaskObserver.cs
- src/UnitTests/Core/Impl/XUnit/XunitTestEnvironment.cs
- src/Windows/Host/Client/Test/Session/RSessionTest.Blobs.cs
- src/Windows/Host/Client/Test/Session/RSessionTest.CancelAll.cs
- src/Windows/Host/Client/Test/Session/RSessionTest.InteractionEvaluation.cs
- src/Windows/Host/Client/Test/Session/RSessionTest.ReadInput.cs
- Fix ParallelTools.InvokeAsync so that it correctly fails on timeout
- Change ITestEnvironment.AddTaskToWait to TryAddTaskToWait so that assembly fixtures can call DoNotWait
> Fix #3533: RSessionTest+ReadInput.ConcurrentRequests fails

- src/Common/Core/Impl/Threading/MainThreadExtensions.cs
- src/UnitTests/Core/Impl/XUnit/TaskObserver.cs
- src/Windows/R/Components/Test/Fixtures/RComponentServicesFixture.cs
- Allow UIThreadHelper to handle tasks that throw exceptions to UI thread
- Fail TaskObserver with inner exception if possible
> Fix couple more issues with TaskObserver

- src/Package/Impl/DataInspect/DataImport/ImportDataWindow.xaml
- src/Package/Impl/Resources.Designer.cs
- src/Package/Impl/Resources.resx
- src/R/Components/Impl/ConnectionManager/Implementation/View/ConnectionManagerControl.xaml
- src/R/Components/Impl/PackageManager/Implementation/View/PackageDetails.xaml
- src/R/Components/Impl/PackageManager/Implementation/View/PackageList.xaml
- src/R/Components/Impl/PackageManager/Implementation/View/PackageManagerControl.xaml
- src/R/Components/Impl/Plots/Implementation/View/RPlotHistoryControl.xaml
- src/R/Components/Impl/Resources.Designer.cs
- src/R/Components/Impl/Resources.resx
VSTS stuff assigned to me
**407002** Accessibility : MAS05A : Keyboard R Tools+R Packages : KB focus invisible over package name in package description pane
**402127** Accessibility : MAS40B : Inspect : Name property is empty for all Edit boxes and combo boxes in "Import DataSet" window
**407002** Accessibility : MAS05A : Keyboard R Tools+R Packages : KB focus invisible over package name in package description pane
**406548** Accessibility : MAS40B : INPSECT : R Tools + R Packages : Name property for the thumb is null in R Packages window
**406112** Accessibility : MAS40B : INPSECT : R Tools + R Packages : Name property for buttons is null in R Packages window
**406109** Accessibility : MAS40 : INSPECT : R Tools + R Plot History : Device Number and expand collapse button in R Plot History …
> Accessibility fixes

- src/Host/Client/Impl/rtvs/R/eval.R
- src/Host/Client/Test/DataInspection/ValuesTest.cs
Properly handle the case when `dim(x)` has named elements.
> Fix #3606: RTVS crashes when loading breast cancer NKI dataset into global environment in R interactive

- src/Host/Client/Impl/Session/RSessionEvaluationCommands.cs
- src/Windows/R/Editor/Impl/Signatures/RSignatureHelp.cs
Leave code page alone, R sets it correctly on its own (tried on Spanish Windows Language pack)
Fix crash in parameter-less signatures
> Default code page fix +  crash fix

- src/Host/API/Impl/RHostSession.cs
- src/Host/API/Test/RSessionApiTest.cs
Added method to terminate broker process. This is scoped fix for Release/1_0. Will restore project and refresh API for 1.2+ separately.
> #3594 RHostSession not terminate RHostBroker

- src/Windows/R/Components/Impl/Plots/Implementation/Commands/PlotDeviceCutCopyCommand.cs
- src/Windows/R/Components/Impl/Plots/Implementation/Commands/PlotDevicePasteCommand.cs
- src/Windows/R/Components/Impl/Plots/Implementation/Commands/PlotHistoryCutCopyCommand.cs
- src/Windows/R/Components/Impl/Plots/Implementation/PlotClipboardData.cs
- src/Windows/R/Components/Impl/Plots/Implementation/View/RPlotDeviceControl.xaml.cs
- src/Windows/R/Components/Impl/Plots/Implementation/View/RPlotHistoryControl.xaml
- src/Windows/R/Components/Impl/Plots/Implementation/View/RPlotHistoryControl.xaml.cs
- src/Windows/R/Components/Impl/Plots/Implementation/ViewModel/RPlotHistoryViewModel.cs
The issue was that some code still assumed `string` rather than `string[]`
Consolidated data object operations in one place so they are consistent across code and use same data representation. Also fixed multiselect (right click unselected elements)
>  #3695 Drag-drop fails with: Cannot complete the drag and drop operation

- src/Windows/Containers/Test/project.json
These binaries clobbered the product binaries which caused RTVS to fail after install.
> Removing unnecessary dependencies.

- src/Host/Broker/Impl/Microsoft.R.Host.Broker.csproj
- src/Linux/Core/Impl/Microsoft.R.Common.Core.Linux.csproj
- src/Linux/Host/Broker/Impl/Microsoft.R.Host.Broker.Linux.csproj
- src/Linux/R/Interpreters/Impl/Microsoft.R.Interpreters.Linux.csproj
- src/R.Settings.NetCore.props
.Net Core projects can reference .Net Standard Library metapackage which version is different than the framework itself. Since System.Web.Http is part of the metapackage, bumping its version to 2.0 solves the issue for .Net Core projects. For .Net Framework projects, we need to update version of System.Web.Http explicitly, but only for the projects that really reference it.
> Fix #3890: Connecting to remote windows fails with "Unable to load one or more of the requested types"

- src/Common/Core/Impl/Security/ISecurityService.cs
- src/Common/Core/Impl/Threading/MainThreadExtensions.cs
- src/Common/Core/Test/Stubs/Shell/SecurityServiceStub.cs
- src/Common/Wpf/Impl/AttachedProperties.cs
- src/Common/Wpf/Impl/Controls/Overlay.cs
- src/Common/Wpf/Impl/Microsoft.Common.Wpf.csproj
- src/Containers/Impl/Docker/LocalDockerService.cs
- src/Host/Client/Impl/Host/BrokerConnectionInfo.cs
- src/R/Components/Impl/Containers/Implementation/ContainerManager.cs
- src/R/Components/Impl/Settings/IRSettings.cs
- src/R/Wpf/Impl/CommonResources.xaml
- src/R/Wpf/Impl/Controls/Watermark.cs
- src/R/Wpf/Impl/Microsoft.R.Wpf.csproj
- src/Windows/Core/Impl/Security/SecurityService.cs
- src/Windows/Host/Client/Test/Fixtures/RemoteBrokerMethodFixture.cs
- src/Windows/R/Components/Impl/ConnectionManager/Implementation/ConnectionManager.cs
- src/Windows/R/Components/Impl/ConnectionManager/Implementation/View/ConnectionManagerControl.xaml
- src/Windows/R/Components/Impl/ContainerManager/Implementation/View/ContainerManagerControl.xaml
- src/Windows/R/Components/Impl/ContainerManager/Implementation/View/ContainerManagerControl.xaml.cs
- src/Windows/R/Components/Impl/ContainerManager/Implementation/ViewModel/ContainerManagerViewModel.cs
- src/Windows/R/Components/Impl/ContainerManager/Implementation/ViewModel/ContainerViewModel.cs
- src/Windows/R/Components/Impl/ContainerManager/Implementation/ViewModel/CreateLocalDockerViewModel.cs
- src/Windows/R/Components/Impl/Plots/Implementation/View/RPlotHistoryControl.xaml
- src/Windows/R/Components/Impl/Resources.Designer.cs
- src/Windows/R/Components/Impl/Resources.resx
#3939: Save credentials for created local docker container
#3952: Container password field should show system password character
#3963: Delete should be disabled for running containers (it actually shows the popup)
#3964: Connection is not removed after the container is deleted
#3967: Use docker file hash as the image name
#3976: Container dialog 'Version' field should have tooltip/watermark with explanation
#3978: UI issues in Create Container panel
#3980: Show watermark on Containers window instead of UI that docker isn't installed
> Container manager bug fixes

- src/R/Components/Impl/Containers/Implementation/ContainerManager.cs
`ContainerException` is swallowed.
> Fix #4034: VS crashes if docker is stopped while Vs is running.

- src/R/Editor/Impl/Completions/Providers/RoxygenTagCompletionProvider.cs
- src/R/Editor/Impl/Extensions/StringExtensions.cs
- src/R/Editor/Impl/Functions/PackageIndex.cs
- src/Windows/R/Editor/Impl/Completions/RCompletionSource.cs
- src/Windows/R/Editor/Test/Completions/RCompletionTestUtilities.cs
- src/Windows/R/Editor/Test/Roxygen/RoxygenCompletionTest.cs
#4119 Roxygen IntelliSense does not incrementally search
- limit trigger to `@`
- include '@' in the applicable span in comments (normally search stops on non-identifier chars)
- add tests
#4030 Update package index on connection change 
- update list of packages when connection changes
> 4119, 4030

- src/R.sln
- src/R/Editor/Impl/Completions/RCompletionContextExtensions.cs
- src/Windows/R/Editor/Impl/Completions/RCompletionController.cs
https://github.com/Microsoft/RTVS/issues/4187
Map caret down and use the active editor buffer instead which is  just a few lines typically and does not include all the output.
> 4187 REPL may become slow after large data output

- src/Package/Impl/Properties/AssemblyInfo.cs
- src/UnitTests/app.config
From user's email:
_The users of our tools (HDI, ASA, and Data Lake tools for VS) are running into assembly resolution issues for System.Net.Http, and we finally discovered that the root cause is that R Tools for VS changes the VS assembly binding for 4.0.0.0 to 4.1.1.1 for everything in VS.  In our apps, we have some app domains that fail to find 4.1.1.1 when they try to resolve System.Net.Http (looks that version is not standard) so it breaks those scenarios for us.  Could this be changed so that R Tools doesn’t everything else running in VS?_
> Remove unnecessary binding redirects

- src/Common/Core/Impl/Microsoft.R.Common.Core.csproj
- src/Host/Client/Impl/Microsoft.R.Host.Client.csproj
- src/Host/Protocol/Impl/Microsoft.R.Host.Protocol.csproj
- src/R.Settings.NetCore.props
- src/R/Components/Impl/Microsoft.R.Components.csproj
- src/Windows/Host/Broker/Impl/app.config
.netstandard packages `Microsoft.Extensions.FileSystemGlobbing` and `Microsoft.Extensions.Logging.Abstractions` of version 1.1.x aren't compiled specifically against .net46, and so they require separate version of `System.Net.Http`. Newer version of those packages are compatible only with .netstandard 2.0, so we need to use older versions (1.0.1) with .net46 and 1.1.x with .netcore
> Use different package versions for .net64 and .netstandard builds
