Microsoft/RTVS

- src/Common/Core/Impl/Collections/ListExtensions.cs
- src/Package/Impl/ProjectSystem/RProjectLoadHooks.cs
- src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.AttributesChanged.cs
- src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.DirectoryCreated.cs
- src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.DirectoryDeleted.cs
- src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.DirectoryRenamed.cs
- src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.FileCreated.cs
- src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.FileDeleted.cs
- src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.FileRenamed.cs
- src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.cs
- src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcherEntries.cs
- src/ProjectSystem/Impl/Logging/MsBuildFileSystemWatcherLoggingExtensions.cs
- src/ProjectSystem/Impl/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.csproj
- src/ProjectSystem/Test/AssertionExtensions.cs
- src/ProjectSystem/Test/Assertions/MsBuildFileSystemWatcherChangesetAssertions.cs
- src/ProjectSystem/Test/EventTaskSources.cs
- src/ProjectSystem/Test/IO/MsBuildFileSystemWatcherEntriesTest.cs
- src/ProjectSystem/Test/IO/MsBuildFileSystemWatcherTest.Delay50MsNoFiltering.cs
- src/ProjectSystem/Test/IO/MsBuildFileSystemWatcherTest.NoDelayNoFiltering.cs
- src/ProjectSystem/Test/IO/MsBuildFileSystemWatcherTest.cs
- src/ProjectSystem/Test/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.Test.csproj
- src/UnitTests/Core/Impl/FluentAssertions/GivenSelectorExtensions.cs
- src/UnitTests/Core/Impl/Microsoft.UnitTests.Core.csproj
- Fix #658: Assertion in File Watcher: The data area passed to a system call is too small
- Fix #1269: Save As file into the project folder doesn't update SolutionExplorer
> - Fix #1151: Improve file system watching mechanism

- src/Package/Impl/Commands/R/RPackageCommandId.cs
- src/Package/Impl/Feedback/ReportIssueCommand.cs
- src/Package/Impl/Microsoft.VisualStudio.R.Package.csproj
- src/Package/Impl/Package.vsct
- src/Package/Impl/Packages/R/PackageCommands.cs
- src/Package/Impl/Resources.Designer.cs
- src/Package/Impl/Resources.resx
(and rename existing Send Smile/Frown commands to make the distinction clearer)
> Add command for filing bugs on GitHub

- src/Debugger/Impl/rtvs/R/grid.R
- prep for further work to support environment list in UI
> Add functions to return environment list

- src/Package/Impl/Package.vsct
- src/Package/Impl/ProjectSystem/Commands/AddItemCommand.cs
- src/Package/Impl/ProjectSystem/Commands/OpenContainingFolderCommand.cs
- src/Package/Impl/ProjectSystem/Commands/SetDirectoryHereCommand.cs
- src/Package/Impl/Utilities/ProjectUtilities.cs
- src/Package/Test/Project/CommandsTest.cs
- src/ProjectSystem/Impl/Extensions/ProjectTreeExtensions.cs
#1319: Add R Script/ and RMD gives error
#1320 Show "Set Directory Here..." on project node
> Fix #1320: #1319

- src/R/Components/Impl/Microsoft.R.Components.csproj
- src/R/Components/Impl/PackageManager/IRPackageManager.cs
- src/R/Components/Impl/PackageManager/Implementation/RPackageManager.cs
- src/R/Components/Impl/PackageManager/Implementation/RPackageWebParser.cs
- src/R/Components/Impl/PackageManager/Model/RPackage.cs
- src/R/Components/Impl/PackageManager/RPackageInfoRetrievalException.cs
- src/R/Components/Test/Files/Parser/ddpcr.html
- src/R/Components/Test/Files/Parser/dplyr.html
- src/R/Components/Test/Files/Repos/Repo1/web/packages/rtvslib1/index.html
- src/R/Components/Test/Microsoft.R.Components.Test.csproj
- src/R/Components/Test/PackageManager/PackageManagerIntegrationTest.cs
- src/R/Components/Test/PackageManager/RPackageWebParserTest.cs
- src/R/Components/Test/PackageManager/TestPackages.cs
Add missing fields to RPackage.
> Add functionality to fetch additional package info from a web page.

- src/Debugger/Impl/rtvs/R/packages.R
- src/Host/Client/Impl/Session/RSessionEvaluationCommands.cs
- src/R/Components/Impl/Microsoft.R.Components.csproj
- src/R/Components/Impl/PackageManager/IRPackageManager.cs
- src/R/Components/Impl/PackageManager/Implementation/RPackageManager.cs
- src/R/Components/Impl/PackageManager/Implementation/RPackageWebParser.cs
- src/R/Components/Impl/PackageManager/RPackageManagerException.cs
- src/R/Components/Impl/Resources.Designer.cs
- src/R/Components/Impl/Resources.resx
- src/R/Components/Test/PackageManager/PackageManagerIntegrationTest.cs
- src/R/Components/Test/PackageManager/RPackageWebParserTest.cs
Add load, unload, get loaded packages.
Add install, uninstall package.
Add get library paths.
> Package manager backend

- src/Package/Impl/DataInspect/EvaluationWrapper.cs
- src/Package/Test/DataInspect/EvaluationWrapperTest.cs
- src/R/Editor/Impl/Data/RSessionDataObject.cs
- data.frame doesn't truncate from now on
> data.frame returns every children

- src/R/Components/Impl/PackageManager/Implementation/View/DesignTime/DesignTimeRPackageViewModel.cs
- src/R/Components/Impl/PackageManager/Implementation/View/PackageDetails.xaml
- src/R/Components/Impl/PackageManager/Implementation/View/PackageDetails.xaml.cs
- src/R/Components/Impl/PackageManager/Implementation/ViewModel/RPackageManagerViewModel.cs
- src/R/Components/Impl/PackageManager/Implementation/ViewModel/RPackageViewModel.cs
- src/R/Components/Impl/PackageManager/ViewModel/IRPackageViewModel.cs
#1422 Package Manager UI: Library in details page should be clickable
#1441 Packaga manager: Move list of authors to the bottom
#1425 Link to repo in package details should be clickable
> #1425 #1422 #1441 Link to repo in package details should be clickable

- src/Package/Impl/DataInspect/DataImport/EnterUrl.xaml
- src/Package/Impl/DataInspect/DataImport/EnterUrl.xaml.cs
- src/Package/Impl/DataInspect/DataImport/ImportDataWindow.xaml
- src/Package/Impl/DataInspect/DataImport/ImportDataWindow.xaml.cs
- src/R/Components/Impl/PackageManager/Implementation/View/PackageManagerControl.xaml
- src/R/Components/Impl/PackageManager/Implementation/View/PackageManagerResources.xaml
- src/R/Components/Impl/Resources.Designer.cs
- src/R/Components/Impl/Resources.resx
- src/R/Wpf/Impl/CommonResources.xaml
- src/R/Wpf/Impl/CommonResources.xaml.cs
- src/R/Wpf/Impl/Microsoft.R.Wpf.csproj
> Styling for EnterUrl.xaml and ImportDataWindow.xaml

- src/Package/Impl/DataInspect/DataImport/ImportDataWindow.xaml.cs
- src/Package/Impl/PackageManager/VsRPackageManagerVisualComponent.cs
#1511 Encoding list in the import dialog may appear empty
#1507 VS crash: ObjectDisposedException for MarshalingWindowFrame
> #1511 #1507

- src/Package/Impl/DataInspect/DataImport/EnterUrl.xaml
- src/Package/Impl/DataInspect/DataImport/EnterUrl.xaml.cs
- src/Package/Impl/DataInspect/DataImport/ImportDataWindow.xaml
- src/Package/Impl/DataInspect/VariableView.xaml
- src/R/Components/Impl/PackageManager/Implementation/View/PackageDetails.xaml
- src/R/Components/Impl/PackageManager/Implementation/View/PackageList.xaml
- src/R/Components/Impl/PackageManager/Implementation/View/PackageManagerControl.xaml
- src/R/Wpf/Impl/CommonResources.xaml
- src/R/Wpf/Impl/Converters.cs
Tested on various IDE fonts and high DPI screen
> #1424: Some rows in VE are taller than others

- src/Debugger/Test/JsonTest.cs
Note that this is just the test - the actual fix is https://github.com/Microsoft/R-Host/pull/54
> Add unit tests for #1513.

- src/Debugger/Engine/Impl/AD7BoundBreakpoint.cs
- src/Debugger/Engine/Impl/AD7Engine.cs
- src/Debugger/Impl/DebugSession.cs
- src/Package/Impl/Help/HelpHomeCommand.cs
- src/Package/Impl/Help/ShowHelpOnCurrentCommand.cs
- src/Package/Impl/Plots/PlotContentProvider.cs
- src/Package/Test/Plots/PlotHistoryTest.cs
- src/Package/TestApp/Help/HelpWindowTest.cs
- src/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveEvaluator.cs
- src/R/Editor/Application.Test/Completion/IntellisenseTest.cs
- src/R/Editor/Impl/SuggestedActions/Actions/RSuggestedActionBase.cs
This is one case where we didn't use DoNotWait, so I added the equivalent catch handlers.
> Fix #1519 Crash in PlotContentProvider

- src/R/Wpf/Impl/CommonResources.xaml
> Fix #1530: Package Manager UI: Remove checkmark when package is loaded

- src/Debugger/Engine/Impl/AD7Property.cs
- src/Debugger/Test/JsonTest.cs
- src/Host/Client/Test/EventTaskSources.cs
- src/Host/Client/Test/Microsoft.R.Host.Client.Test.csproj
- src/Host/Client/Test/Session/RSessionTest.Output.cs
and fixes to various minor issues caused by the change
PR for the actual fix is https://github.com/Microsoft/R-Host/pull/55
> Unit test for #1340 fix

- src/Package/Impl/Options/R/Tools/CranMirrorTypeConverter.cs
- src/Package/Impl/Resources.Designer.cs
- src/Package/Impl/Resources.resx
Reject unknown CRAN mirror names.
> Fix #1545: CRAN mirror setting allows arbitrary strings

- src/Package/Impl/DataInspect/DataImport/ImportDataWindow.xaml
- src/Package/Impl/DataInspect/DataImport/ImportDataWindow.xaml.cs
Reverts Microsoft/RTVS#1558, more changed are coming in.
> Revert "Preview data grid is read only"

- src/Host/Client/Impl/Definitions/MessageTransportException.cs
- src/Host/Client/Impl/Host/RHost.cs
- src/Host/Client/Impl/Microsoft.R.Host.Client.csproj
- src/Host/Client/Impl/Transports/WebSocketMessageTransport.cs
Move host message transport classes to their own folder.
> Increase websocket timeout in debug builds.

- src/Host/Client/Test/IdeGraphicsDeviceTest.cs
Test for Fixes https://github.com/Microsoft/RTVS/issues/1568
Will update submodule after r-host commit is in.
> Add test for temp png file leak issue in R-Host.

- src/Host/Client/Impl/Definitions/IRExpressionEvaluator.cs
- src/Host/Client/Impl/Definitions/REvaluationKind.cs
- src/Host/Client/Impl/Definitions/REvaluationResult.cs
- src/Host/Client/Impl/Host/RHost.EvaluationRequest.cs
- src/Host/Client/Impl/Host/RHost.cs
and reimplement ExecuteAsync to use that flag instead of the ";NULL" hack.
> Add REvaluationKind.NoResult corresponding to "0" evaluation flag

- src/Package/Impl/ProjectSystem/RProjectLoadHooks.cs
Verified that #931 isn't regressed
> Fix #1607: History isn't saved when user exits VS

- src/Common/Core/Impl/Extensions/TaskExtensions.cs
- src/Common/Core/Test/Tasks/TaskExtensionsTest.cs
- src/R/Components/Impl/InteractiveWorkflow/Implementation/RSessionCallback.cs
Added tests
Unblock `RSession` thread for `ReadUserInput` implementation
> Fix SilenceException so it doesn't convert task cancellation into task failure

- src/Package/Impl/DataInspect/DataImport/ImportDataWindow.xaml.cs
Fix for https://github.com/Microsoft/RTVS/issues/1535
> When row name is set to first column, set row.names to 1, not "1".

- src/Package/Impl/DataInspect/DataImport/ImportDataWindow.xaml.cs
- src/Package/Impl/DataInspect/EvaluationWrapper.cs
- src/Package/Impl/DataInspect/Office/CsvAppFileIO.cs
- src/Package/Impl/Feedback/SendMailCommand.cs
- src/Package/Impl/PackageManager/VsRPackageManagerVisualComponent.cs
- src/Package/Impl/ProjectSystem/Commands/CopyItemPathCommand.cs
- src/Package/Impl/Shell/VsAppShell.cs
- src/Package/Test/Project/CommandsTest.cs
- src/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveWorkflow.cs
+ removed incorrect calls of  _coreShell.DispatchOnMainThreadAsync
+ reverted original implementation of _coreShell.DispatchOnMainThreadAsync
Requires two :+1: to merge
> Fix different threading issues

- src/Host/Client/Test/Session/RSessionTest.InteractionEvaluation.cs
(covers https://github.com/Microsoft/RTVS/issues/1701)
> Add unit test for nested interactions and evaluations 

- src/Package/Impl/Commands/R/RPackageCommandId.cs
- src/Package/Impl/Package.vsct
- src/Package/Impl/Packages/R/PackageCommands.cs
- src/Package/Impl/ProjectSystem/Commands/SourceFilesCommand.cs
- src/Package/Impl/Repl/Commands/SourceRScriptCommand.cs
- src/R/Components/Impl/InteractiveWorkflow/IRInteractiveWorkflowOperations.cs
- src/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveWorkflowOperations.cs
#984
For now, I've made it use source() instead of debug_source() in the case where we are debugging and user wants echo.
> source with echo

- src/Host/Client/Test/Microsoft.R.Host.Client.Test.csproj
- src/R/Components/Impl/History/IRHistoryEntries.cs
- src/R/Components/Impl/History/Implementation/RHistory.cs
- src/R/Components/Impl/History/Implementation/RHistoryEntries.cs
- src/R/Components/Test/Microsoft.R.Components.Test.csproj
- src/R/Components/Test/project.json
- src/UnitTests/Core/Impl/XUnit/TestAttribute.cs
+ Fix Microsoft.R.Components.Test dependencies
> Fix #1071: Up/down arrow in History doesn't update viewport

- src/Package/Impl/DataInspect/VariableView.xaml
- src/Package/Impl/DataInspect/VariableView.xaml.cs
- src/R/Editor/Impl/Data/RSessionDataObject.cs
- active bindings
- promises
- functions
- data frames
- matrices
- errors
- normal variables (everything else)
> Add icons to variables in Variable Explorer:

- src/Package/Impl/Help/HelpWindowPane.cs
Fixes https://github.com/Microsoft/RTVS/issues/1856
> Helpsearch

- src/Package/Impl/DataInspect/VariableGridHost.xaml.cs
- src/Package/Test/DataInspect/EvaluationWrapperTest.cs
Fixes https://github.com/Microsoft/RTVS/issues/1847
> Handle the possibility of a removed variable in data grid.

- src/Debugger/Impl/AD7BoundBreakpoint.cs
- src/Debugger/Impl/AD7Engine.cs
- src/Debugger/Impl/AD7Property.cs
- src/Debugger/Impl/AD7Thread.cs
- src/Debugger/Impl/PortSupplier/RDebugPortSupplier.cs
- src/Host/Client/Impl/rtvs/R/breakpoints.R
- src/Package/Impl/Microsoft.VisualStudio.R.Package.csproj
- src/Package/Impl/ProjectSystem/Constants.cs
- src/Package/Impl/ProjectSystem/RDebugLaunchProvider.cs
- src/Package/Impl/ProjectSystem/RProjectFactory.cs
- src/Package/Impl/Repl/Debugger/AttachDebuggerCommand.cs
- src/Package/Impl/Resources.Designer.cs
- src/Package/Impl/Resources.resx
- src/Package/Impl/Rules/Content.xaml
- src/Package/Impl/Rules/Debugger.xaml
- src/Package/Impl/Rules/Folder.xaml
- src/Package/Impl/Rules/General.BrowseObject.xaml
- src/Package/Impl/Rules/None.xaml
- src/Package/Impl/Rules/ProjectItemsSchema.xaml
- src/Package/Impl/Rules/Run.xaml
- src/Package/Impl/Rules/Scc.xaml
- src/Package/Impl/Rules/rtvs.rules.props
- src/Package/Impl/Targets/Microsoft.R.targets
- src/ProjectSystem/Impl/Project/FileSystemMirroringProjectFileGenerator.cs
- src/Setup/CpsRules.wxi
- src/Setup/Definitions.wxi
- src/Setup/Feature.wxi
- src/Setup/MSBuildTargets.wxi
- src/Setup/Product.wxs
- src/Setup/Setup.wixproj
Fix #1090: Launch project with debugging (F5)
Fix #1654: Launch project without debugging (Ctrl+F5)
Implement IDebugLaunchProvider for R projects.
> F5 and Ctrl+F5

- src/Package/Impl/Help/HelpWindowPane.cs
- src/Package/Impl/Package.vsct
- src/Package/Impl/Resources.Designer.cs
- src/Package/Impl/Resources.resx
#1872 For RMarkdown documents, add a toolbar button for generating Word docs 
#1863 R Help: Can't search again for same topic 
#1857 Missing R Host message is incorrect
> #1857 #1863 #1872

- src/Package/Impl/ProjectSystem/PropertyPages/RunPageControl.xaml
https://github.com/Microsoft/RTVS/issues/1890
> Hide command line args from project propety page.

- src/Package/Test/DataInspect/EvaluationWrapperTest.cs
- src/R/Editor/Test/Script/RHostScript.cs
Fixes https://github.com/Microsoft/RTVS/issues/1887
> Make FormulaTest pass on both R 3.2 and 3.3.

- src/Package/Impl/Microsoft.VisualStudio.R.Package.csproj
- src/Package/Impl/Options/R/Tools/EncodingTypeConverter.cs
- src/Package/Impl/ProjectSystem/Commands/AddRScriptCommand.cs
- src/Package/Impl/Templates/ItemTemplates/RScript/rscript.vstemplate
- src/Package/Test/Microsoft.VisualStudio.R.Package.Test.csproj
- src/Package/Test/Options/EncodingsTest.cs
- src/R/Editor/Impl/Completion/RCompletionController.cs
+ small issue in completion on Enter in editor so it only completes when text is not fully typed or when completion is explicitly selected
> #1877 #1901

- src/Host/Client/Impl/rtvs/R/grid.R
- src/Package/Impl/DataInspect/GridData.cs
This was a sub-issue in one of the grid bugs that I have overlooked.
> Display indices instead of NA for headers of rows and columns that do not have a name

- src/Host/Client/Impl/rtvs/R/grid.R
- src/Package/Impl/DataInspect/DataSource/GridDataSource.cs
- src/Package/Impl/DataInspect/DataSource/IGridProvider.cs
- src/Package/Impl/DataInspect/Definitions/ISortOrder.cs
- src/Package/Impl/DataInspect/GridDataProvider.cs
- src/Package/Impl/DataInspect/VisualGrid/MatrixView.xaml
- src/Package/Impl/DataInspect/VisualGrid/MatrixView.xaml.cs
- src/Package/Impl/DataInspect/VisualGrid/SortOrder.cs
- src/Package/Impl/DataInspect/VisualGrid/VisualGrid.cs
- src/Package/Test/DataInspect/EvaluationWrapperTest.cs
- src/Package/TestApp/Data/GridDataTest.cs
- src/Package/TestApp/Files/VariableGrid02.tree
- src/Package/TestApp/Files/VariableGridSorted01.tree
- src/Package/TestApp/Files/VariableGridSorted02.tree
- src/Package/TestApp/Microsoft.VisualStudio.R.Interactive.Test.csproj
- src/UnitTests/Core/Impl/XUnit/Categories.cs
Fix a bunch of failing grid unit tests and related issues.
Add better tests for rtvs:::grid_data (not ful coverage yet, more to be added).
> Fix #1924: Sorting a list in the grid does not work

- src/Package/Impl/Help/SearchWebForCurrentCommand.cs
- src/Package/Impl/Microsoft.VisualStudio.R.Package.csproj
- src/Package/Impl/Options/Attributes/WebHelpSearchBrowserTypeConverter.cs
- src/Package/Impl/Options/R/RToolsOptionsPage.cs
- src/Package/Impl/Options/R/Tools/RToolsSettingsImplementation.cs
- src/Package/Impl/Resources.Designer.cs
- src/Package/Impl/Resources.resx
- src/R/Support/Impl/Microsoft.R.Support.csproj
- src/R/Support/Impl/Settings/Definitions/IRToolsSettings.cs
- src/R/Support/Impl/Settings/Definitions/WebHelpSearchBrowserType.cs
- src/R/Support/Test/Utility/TestRToolsSettings.cs
> Additional F1 Web search options

- src/Package/Impl/Commands/RHistory/VsRHistoryCommandFactory.cs
- src/Package/Impl/DataInspect/Viewers/ViewerBase.cs
- src/Package/Impl/ProjectSystem/OpenRDataCommandGroupHandler.cs
- src/Package/Impl/Repl/ReplPromptTagger.cs
- src/Package/Impl/Repl/VsRInteractiveWindowComponentContainerFactory.cs
- src/R/Components/Test/Fakes/VisualComponentFactories/TestRInteractiveWindowComponentContainerFactory.cs
Remove initialization logic from importing constructor
> Fix #1229: Loading solution is stuck

- src/Package/Impl/DataInspect/VariableGridHost.xaml.cs
- src/Package/Impl/DataInspect/VisualGrid/VisualGrid.cs
Reset sorting if shape of the data in the grid changes.
> Fix #1931: Assert for single-dimensional array

- src/Package/Impl/DataInspect/Commands/DeleteAllVariablesCommand.cs
- src/Package/Impl/DataInspect/VariableView.xaml.cs
- src/Package/Impl/DataInspect/VariableWindowPane.cs
Delete all variables is enabled for .GlobalEnv only Fixes #1899.
> Delete all variables is enabled for .GlobalEnv only Fixes #1899.

- src/Host/Client/Impl/DataInspection/IRValueInfo.cs
- src/Host/Client/Impl/DataInspection/RActiveBindingInfo.cs
- src/Host/Client/Impl/DataInspection/REvaluationResultInfo.cs
- src/Host/Client/Impl/DataInspection/REvaluationResultProperties.cs
- src/Host/Client/Impl/DataInspection/RValueInfo.cs
- src/Host/Client/Impl/Definitions/REvaluationResult.FieldNames.cs
- src/Host/Client/Impl/Definitions/REvaluationResult.cs
- src/Host/Client/Impl/Extensions/RawEvalResultExtensions.cs
- src/Host/Client/Impl/Microsoft.R.Host.Client.csproj
- src/Host/Client/Impl/rtvs/R/eval.R
- src/Host/Client/Impl/rtvs/R/util.R
- src/Package/Impl/DataInspect/VariableViewModel.cs
Added a bool filed to RValueInfo to indicate if a variable can be exported to CSV.
> Fixes #2114 - a crash when CSV export is not possible.

- src/Host/Client/Impl/Host/RHost.cs
- src/Host/Client/Impl/Session/RSession.cs
- src/Host/Client/Test/Microsoft.R.Host.Client.Test.csproj
- src/Host/Client/Test/Session/RSessionTest.Blobs.cs
* #2111 Unified RSession blob send, get, and destroy methods.
* #2112 Added negative tests for Send, Get, and Destroy Blobs.
> Couple of fixes.

- src/Package/Impl/Options/R/RToolsOptionsPage.cs
- src/Package/Impl/Sql/Commands/PublishSProcOptionsCommand.cs
- src/Package/Impl/Sql/Publish/DacPacBuilder.cs
- src/Package/Impl/Sql/Publish/SProcPublisher.cs
- src/Package/Impl/Sql/Publish/SqlPublishOptionsDialogViewModel.cs
- src/Package/Impl/Sql/Publish/SqlPublshOptionsDialog.xaml
- src/Package/Impl/Sql/Publish/SqlPublshOptionsDialog.xaml.cs
- src/Package/Impl/Utilities/ActiveWpfTextViewTracker.cs
- src/Package/Test/Sql/PublishOptionsDialogModelTest.cs
- src/Package/Test/Sql/PublishOptionsDialogTest.cs
- src/R/Editor/Impl/Completion/Engine/RCompletionEngine.cs
- src/R/Editor/Impl/Completion/Providers/WorkspaceVariableCompletionProvider.cs
- src/R/Editor/Impl/ContentType/TextViewExtensions.cs
- src/R/Editor/Impl/Data/WorkspaceVariableProvider.cs
- src/R/Editor/Impl/DragDrop/DataObject.cs
- src/R/Editor/Impl/Navigation/Peek/InternalFunctionPeekResultSource.cs
- src/R/Editor/Impl/Signatures/SignatureHelp2.cs
- src/R/Editor/Test/DragDrop/DragDropTest.cs
- src/R/Editor/Test/Extensions/TextViewExtensionsTest.cs
- src/R/Editor/Test/Signatures/ParameterTest.cs
#2138 Replace TwoWay binding by event handlers in SQL publishing
#1990 Wrong reported default for Use multiline selection
#2058 Goto definition should take selection into account
#2019 Putting $ evaluates the code and shows an error.
#2146 Drag & drop of sql file creates code that doesn't work for mult… 
#2147 Incorrect parameter suggested in arguments with nested function…
> Assorted fixes

- src/Common/Core/Impl/IO/FileSystem.cs
- src/Common/Core/Impl/IO/IFileSystem.cs
- src/Package/Impl/DataInspect/Office/CsvAppFileIO.cs
- src/Package/Impl/DataInspect/VariableViewModel.cs
- src/Package/Impl/Packages/R/RPackage.cs
CsvAppFileIO changed to use IApplicationShell, IFileSystem, and IProcessServices
> #2121 CsvAppFileIO changed to use file system and process services

- src/Host/Client/Impl/rtvs/R/grid.R
- src/Package/Test/DataInspect/EvaluationWrapperTest.cs
- src/Package/TestApp/Data/GridDataTest.cs
> Fixes grid data when it includes NA values.

- src/R/Components/Test/PackageManager/TestRepositories.cs
Fix R expression in SetCranRepoAsync to parse correctly.
> Fix #2162: SwitchFromInstalledToAvailableWhileLoadingInstalled is hanging

- src/Common/Core/Impl/Extensions/IOExtensions.cs
- src/Common/Core/Impl/IO/FileSystem.cs
- src/Common/Core/Impl/IO/IFileSystem.cs
- src/Common/Core/Impl/Microsoft.Common.Core.csproj
- src/Common/Core/Impl/project.json
- src/Host/Client/Impl/Definitions/IRSession.cs
- src/Host/Client/Impl/Host/RHostBrokerConnectorExtensions.cs
- src/Host/Client/Impl/Microsoft.R.Host.Client.csproj
- src/Host/Client/Impl/Session/RSession.cs
- src/Host/Client/Impl/rtvs/R/util.R
- src/Host/Client/Test/Mocks/RSessionMock.cs
- src/Package/Impl/Commands/R/RPackageCommandId.cs
- src/Package/Impl/Microsoft.VisualStudio.R.Package.csproj
- src/Package/Impl/Package.vsct
- src/Package/Impl/ProjectSystem/Commands/SetAsStartUpRScriptCommand.cs
- src/Package/Impl/ProjectSystem/Definitions/IRProjectProperties.cs
- src/Package/Impl/ProjectSystem/ProjectProperties.cs
- src/Package/Impl/ProjectSystem/PropertyPages/Run/RunPageControl.xaml
- src/Package/Impl/ProjectSystem/PropertyPages/Run/RunPageViewModel.cs
- src/Package/Impl/ProjectSystem/RDebugLaunchProvider.cs
- src/Package/Impl/Rules/Run.xaml
- src/Package/Impl/source.extension.vsixmanifest
- src/Package/Test/Project/ProjectSystem/PropertyPages/RunPageViewModelTest.cs
- src/Setup/Assemblies.wxi
- src/Setup/Definitions.wxi
- src/SetupRHost/Definitions.wxi
- src/SetupRHost/Product.wxs
Adds remote F5 feature. Updates properties page for Run. Adds context menu command to set R Script as StartUp file.
> Adds remote F5 feature. Updates properties page for Run.

- src/R/Components/Impl/ConnectionManager/Implementation/View/ConnectionStatusBar.xaml
- src/R/Components/Impl/ConnectionManager/Implementation/View/DesignTime/DesignTimeConnectionStatusBarViewModel.cs
- src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionStatusBarViewModel.cs
- src/R/Components/Impl/ConnectionManager/ViewModel/IConnectionStatusBarViewModel.cs
- src/R/Wpf/Impl/CommonResources.xaml
> Replace status bar icons with the one that match the Connection Manager

- src/Common/Core/Impl/Extensions/StringExtensions.cs
- src/Package/Impl/Options/R/RToolsOptionsPage.cs
- src/Package/Impl/Packages/R/RPackage.cs
- src/Package/Impl/ProjectSystem/Configuration/ProjectConfigurationSettingsProvider.cs
- src/Package/Impl/Sql/Publish/SqlPublshOptionsDialog.xaml.cs
- src/Package/Impl/Telemetry/RtvsTelemetry.cs
- src/Package/Test/Sql/PublishOptionsDialogTest.cs
- src/Package/Test/Telemetry/TelemetryTest.cs
- src/R/Support/Impl/Help/Packages/PackageIndex.cs
#2197 What is IsLoadingFromStorage option
#2201 Some tests are broken
> #2197 #2201 

- src/Host/Client/Impl/Session/RSession.cs
- src/Package/Impl/ProjectSystem/RProjectLoadHooks.cs
Do not change working directory when starting host or loading project if connection is remote (and local paths are not applicable).
> Unblock #2223, #2224

- src/Host/Broker/Impl/Sessions/Session.cs
- src/Host/Client/Impl/rtvs/R/util.R
Fixes #2228 Win32Exception when windows authentication is used
Fixes #2212 Error deploying files on F5
> Couple of fixes

- src/Common/Core/Impl/Extensions/ClipboardExtensions.cs
- src/Common/Core/Impl/Microsoft.Common.Core.csproj
- src/Package/Impl/Commands/R/RPackageCommandId.cs
- src/Package/Impl/Microsoft.VisualStudio.R.Package.csproj
- src/Package/Impl/Package.vsct
- src/Package/Impl/ProjectSystem/Commands/CopyItemPathCommand.cs
- src/Package/Impl/ProjectSystem/Commands/CopyRemoteItemPathCommand.cs
- src/Package/Impl/ProjectSystem/Definitions/IRProjectPropertiesExtensions.cs
Adds context menu item to get remote item path if RTVS is connected to a Remote RHost #2177
> Adds context menu item to get remote item path #2177

- src/R/Components/Impl/ConnectionManager/Implementation/View/ConnectionManagerControl.xaml
- src/R/Components/Impl/ConnectionManager/Implementation/View/ConnectionManagerControl.xaml.cs
- src/R/Components/Impl/ConnectionManager/Implementation/View/DesignTime/DesignTimeConnectionManagerViewModel.cs
- src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionManagerViewModel.cs
- src/R/Components/Impl/ConnectionManager/ViewModel/IConnectionManagerViewModel.cs
- src/R/Components/Impl/Resources.Designer.cs
- src/R/Components/Impl/Resources.resx
- src/R/Wpf/Impl/CommonResources.xaml
- Simplify ConnectionManagerViewModel code
> Show arrows for the Workspaces list elements

- src/R/Components/Impl/ConnectionManager/Implementation/View/ConnectionManagerControl.xaml
- src/R/Components/Impl/ConnectionManager/Implementation/View/DesignTime/DesignTimeConnectionManagerViewModel.cs
- src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionManagerViewModel.cs
- src/R/Components/Impl/ConnectionManager/ViewModel/IConnectionManagerViewModel.cs
- src/R/Components/Impl/Resources.Designer.cs
- src/R/Components/Impl/Resources.resx
- src/R/Wpf/Impl/CommonResources.xaml
+ Section for the local connections
> Fix for the styles

- src/R/Components/Impl/ConnectionManager/Implementation/View/ConnectionManagerControl.xaml
- src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionViewModel.cs
- src/R/Support/Impl/Help/Packages/PackageIndex.cs
- src/R/Wpf/Impl/Converters.cs
And actually enable name and path for new connections
> Bold active connection

- src/Host/Broker/Impl/Sessions/Session.cs
> Fixes the ERROR_INVALID_ACCOUNT_NAME in local scenario. 

- src/Host/Client/Impl/Session/RSession.cs
- src/Host/Client/Impl/Session/RSessionProvider.cs
- src/Host/Client/Test/Session/RSessionProviderTest.cs
#2217: Unable to recover and switch to local
#2281: Switching from local to remote connection disconnects
> Fix couple of bugs

- src/Common/Core/Impl/Extensions/ArraySegmentExtensions.cs
- src/Common/Core/Impl/Extensions/StreamExtensions.cs
- src/Common/Core/Impl/Microsoft.Common.Core.csproj
- src/Common/Core/Impl/Net/WebSocketHelper.cs
- src/Host/Broker/Impl/RemoteUri/RemoteUriHelper.cs
- src/Host/Client/Impl/BrokerServices/RemoteUriWebService.cs
> Remote Shiny

- src/Host/Client/Impl/Session/RSessionEvaluationCommands.cs
- src/Host/Client/Impl/rtvs/R/graphics.R
- src/R/Components/Impl/Plots/Implementation/RPlotManager.cs
Fixes https://github.com/Microsoft/RTVS/issues/2291
> Prevent json deserialization error if device id is not found.

- src/Host/Client/Impl/Session/RSessionProvider.cs
- src/Package/Impl/StatusBar/VsStatusBar.cs
- src/R/Support/Impl/Help/Packages/PackageIndex.cs
-Reuse existing extension method
- Fix #2297: RSessions are leaking
- Fix VsStatusBar so it tries to add items to visual root on idle if VS visual tree isn't ready
> Several fixes

- src/Package/Impl/source.extension.vsixmanifest
- src/R.Build.Version.targets
> Rev master version up to 0.6

- src/Host/Client/Test/IdeGraphicsDeviceTest.cs
> Fix for ExportToImage tests fail with host crash

- src/R/Components/Impl/Plots/Implementation/NonScaledImage.cs
- src/R/Components/Impl/Plots/Implementation/View/RPlotDeviceControl.xaml.cs
- src/R/Components/Impl/Plots/Implementation/WpfUnitsConversion.cs
Fixes https://github.com/Microsoft/RTVS/issues/2375
> Prevent crash when plot window is docked as document window and hidden

- src/Host/Protocol/Impl/Message.cs
> Replace logging for large blobs with blob length and hash. 

- src/Common/Core/Impl/TaskUtilities.cs
- src/Host/Client/Impl/Host/BrokerClient.cs
- src/Host/Client/Impl/Host/BrokerClientProxy.cs
- src/Host/Client/Impl/Host/RemoteBrokerClient.cs
- src/Host/Client/Impl/Resources.Designer.cs
- src/Host/Client/Impl/Resources.resx
- src/Host/Client/Impl/Session/RSessionProvider.cs
- src/Package/Impl/Help/HelpVisualComponent.cs
- src/R/Components/Impl/ConnectionManager/Implementation/ConnectionManager.cs
- src/R/Components/Impl/ConnectionManager/Implementation/View/ConnectionManagerControl.xaml
- src/R/Editor/Impl/Formatting/AutoFormat.cs
- src/R/Editor/Impl/Formatting/FormatOperations.cs
- src/R/Editor/Test/Formatting/AutoFormatTest.cs
#2025 Auto-formatting add extra space at line break
#2321 Help window should reset when switching sessions
#2415 Switching to offline remote connection doesn't produce error
#2395 Connection diagnostics is unreliable
> #2025, #2321, #2395, #2415

- src/R/Components/Impl/Plots/Implementation/View/RPlotHistoryControl.xaml.cs
Fixes https://github.com/Microsoft/RTVS/issues/2345
> Fix dragging from plot history.

- src/R/Components/Test/Plots/RPlotIntegrationUITest.cs
> Fix plot ui tests when running on high dpi machine.

- src/Host/Client/Impl/BrokerServices/RemoteUriWebService.cs
- src/R/Core/Impl/AST/Operators/Operator.cs
- src/R/Core/Impl/Formatting/RFormatter.cs
- src/R/Core/Test/Formatting/FormatMultilineTest.cs
- src/R/Core/Test/Formatting/FormatOperatorsTest.cs
#2480 Spaces placed around hyphen used for numeric negation			
#2470 Formatting: comments are not indented same as statement
Fix crash on remote ?help
> #2480 #2470 and unfiled crash in remote ?help

- src/Debugger/Impl/AD7Engine.cs
Stop debugging when broker switching is complete.
> Fix #2325: Switching sessions doesn't stop debugging

- src/Host/Monitor/Impl/App.xaml
- src/Host/Monitor/Impl/Microsoft.R.Host.Monitor.csproj
- src/Package/Impl/Publishing/Commands/PreviewCommand.cs
Fix another case of background thread call to VS services
> Remove Aero references

- src/Host/Client/Impl/Definitions/IRSessionProvider.cs
- src/Host/Client/Impl/Host/BrokerClient.cs
- src/Host/Client/Impl/Host/BrokerClientProxy.cs
- src/Host/Client/Impl/Host/IBrokerClient.cs
- src/Host/Client/Impl/Host/NullBrokerClient.cs
- src/Host/Client/Impl/Resources.Designer.cs
- src/Host/Client/Impl/Resources.resx
- src/Host/Client/Impl/Session/RSessionProvider.cs
- src/Host/Client/Impl/rtvs/R/util.R
- src/Host/Client/Test/Mocks/RSessionProviderMock.cs
- src/Package/Impl/Packages/Markdown/MdPackage.cs
- src/Package/Impl/Publishing/Commands/PreviewCommand.cs
- src/Package/Impl/Publishing/Commands/PreviewPdfCommand.cs
- src/Package/Impl/Resources.Designer.cs
- src/Package/Impl/Resources.resx
- src/R/Components/Impl/InteractiveWorkflow/Commands/SessionInformationCommand.cs
- src/R/Components/Impl/Microsoft.R.Components.csproj
- src/R/Components/Impl/Resources.Designer.cs
- src/R/Components/Impl/Resources.resx
- src/R/Support/Impl/Help/Functions/FunctionIndex.cs
- src/R/Support/Impl/Help/Functions/FunctionInfo.cs
#2532 Existence of Pandoc is checked locally
- Fix endless requests to RData for non-existing functions (semi-hang debugger data tip)
- Fix issue when opening markdown without REPL up asserts b/c VsShell hasn't been initialized as R package is not loaded yet.
Improve remote host information printing:
- Move code to components
- Print after the R information is printed
> #2532 and couple more fixes

- src/Host/Monitor/Impl/Logging/MonitorLogger.cs
- src/Host/UserProfile/Impl/ServiceLogger.cs
- src/Host/UserProfile/Impl/ServiceLoggerProvider.cs
Added event logging to UserProfile Service. Monitor will continue to log to a file, since it is a application that runs as a user. #2477
> Logging from UserProfile 

- src/Host/Client/Impl/BrokerServices/WebServer.cs
- src/Host/Client/Impl/Host/BrokerClient.cs
- src/Host/Client/Impl/Host/BrokerClientProxy.cs
- src/Host/Client/Impl/Host/IBrokerClient.cs
- src/Host/Client/Impl/Host/NullBrokerClient.cs
- src/Host/Client/Impl/Host/RemoteBrokerClient.cs
- src/Host/Client/Impl/Microsoft.R.Host.Client.csproj
- src/Host/Client/Impl/Session/RSession.cs
- src/Host/Client/Impl/rtvs/man/fetch_file.Rd
- src/Package/Test/Browsers/WebBrowserServicesTest.cs
- src/R/Editor/Test/Completions/RCompletionSourceTest.cs
- src/R/Support/Impl/Help/FunctionRdDataProvider.cs
- src/R/Support/Impl/Help/Packages/PackageIndex.cs
- src/R/Support/Impl/RD/Parser/RdParser.cs
- src/Setup/RtvsPackage.wxi
- src/Setup/RtvsPackageFiles3.wxi
- src/Setup/Setup.wixproj
- src/SetupRemote/Definitions.wxi
- src/SetupRemote/RtvsPackage.wxi
#2500 REPL stuck spinning when trying to show help
#2507 Remote: rtvs::: is not autocompleting
> #2500, #2507

- src/Host/Broker/Impl/Microsoft.R.Host.Broker.csproj
- src/Host/Broker/Impl/NativeMethods.cs
- src/Host/Broker/Impl/Resources.Designer.cs
- src/Host/Broker/Impl/Resources.resx
- src/Host/Broker/Impl/Sessions/BrokerMaxedUsersException.cs
- src/Host/Broker/Impl/Sessions/SessionManager.cs
- src/Host/Broker/Impl/Sessions/SessionsController.cs
- src/Host/Client/Impl/Host/RHostDisconnectedException.cs
- src/Host/Client/Impl/Resources.Designer.cs
- src/Host/Client/Impl/Resources.resx
- src/Host/Protocol/Impl/BrokerApiError.cs
> Broker on client windows allows only 1 user to create sessions.

- src/Common/Core/Impl/Events/DirtyEventSource.cs
- src/Common/Core/Impl/Extensions/StringExtensions.cs
- src/Common/Core/Impl/Microsoft.Common.Core.csproj
- src/Package/Impl/ToolWindows/PackageManagerWindowPane.cs
- src/Package/Impl/ToolWindows/VsRPackageManagerVisualComponent.cs
- src/R/Components/Impl/PackageManager/IRPackageManager.cs
- src/R/Components/Impl/PackageManager/IRPackageManagerVisualComponentContainerFactory.cs
- src/R/Components/Impl/PackageManager/Implementation/RPackageManager.cs
- src/R/Components/Impl/PackageManager/Implementation/RPackageManagerVisualComponent.cs
- src/R/Components/Impl/PackageManager/Implementation/View/DesignTime/DesignTimeRPackageManagerViewModel.cs
- src/R/Components/Impl/PackageManager/Implementation/ViewModel/RPackageManagerViewModel.cs
- src/R/Components/Impl/PackageManager/ViewModel/IRPackageManagerViewModel.cs
- src/R/Components/Test/Fakes/VisualComponentFactories/TestRPackageManagerVisualComponentContainerFactory.cs
- Fix #2357: Package manager stuck
- Fix #2510: Unable to load installed package in remote
- Fix #2282: remote: left over msgs (eg pkg mgr) need to be cleared
> Fix several package manager issues

- src/Languages/Editor/Impl/Text/TextRangeExtensions.cs
Couple methods disappeared during merge causing build break
> Restore lost change

- src/Common/Core/Impl/IO/FileSystem.cs
- src/Common/Core/Impl/IO/IFileSystem.cs
- src/Host/Client/Impl/Blobs/DataTransferSession.cs
- src/Host/Client/Impl/Microsoft.R.Host.Client.csproj
- src/Host/Client/Impl/rtvs/R/util.R
- src/Host/Client/Test/RtvsPackage/BlobsTest.cs
- src/Package/Impl/DataInspect/Office/CsvAppFileIO.cs
> Improves download experience for export of CVS on remote R

- src/R/Components/Impl/Plots/Implementation/Commands/PlotDevicePasteCommand.cs
Fix https://github.com/Microsoft/RTVS/issues/2649
> Handle exceptions from clipboard.

- src/Host/Client/Impl/Session/RSession.cs
> NRE in DestroyBlobsAsync

- src/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveEvaluator.cs
- src/R/Core/Impl/AST/Expressions/ExpressionParser.cs
- src/R/Core/Impl/AST/Extensions/AstRootExtensions.cs
- src/R/Core/Impl/Formatting/FormattingScope.cs
- src/R/Core/Impl/Formatting/RFormatter.cs
- src/R/Core/Impl/Microsoft.R.Core.csproj
- src/R/Core/Impl/Parser/RParser.cs
- src/R/Core/Test/Formatting/FormatMultilineTest.cs
- src/R/Editor/Impl/SmartIndent/SmartIndenter.cs
- src/R/Editor/Test/Formatting/SmartIndentTest.cs
This reverts commit 5e1a474e3a2e53241a2add081f0508da16b29ec1, reversing
changes made to 69137c9cbeba7e6579efe1a979f90226da34dd5a.
> Revert "Merge pull request #2653 from MikhailArkhipov/Formatting"

- src/Host/Client/Impl/Session/RSessionProvider.cs
- src/Host/Client/Test/Session/RSessionProviderTest.cs
> Fix regression introduced by 9fca44e (Fix #2644: Package manager RHost session should use the name PackageManager)

- src/Common/Core/Impl/Extensions/ExceptionExtensions.cs
- src/Host/Broker/Impl/Pipes/MessagePipe.cs
- src/Host/Client/Impl/Transports/WebSocketMessageTransport.cs
- src/Host/Protocol/Impl/Message.cs
- src/Host/Protocol/Test/Microsoft.R.Host.Protocol.Test.csproj
- src/Host/Protocol/Test/ProtocolMessage/ProtocolMessageTest.cs
- src/Host/Protocol/Test/RHostPipe/RHostPipeTest.cs
> Fuzz Tests for RTVS side message protocol

- src/SetupRemote/Product.wxs
> Fixes Uninstall does not remove UserProfile service from services

- src/Host/Client/Impl/Definitions/IRSessionProvider.cs
- src/Host/Client/Impl/Session/RSessionEvaluationCommands.cs
- src/Host/Client/Impl/Session/RSessionProvider.cs
- src/Host/Client/Test/Session/RSessionProviderTest.cs
- src/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveEvaluator.cs
- src/R/Components/Impl/PackageManager/IRPackageManager.cs
- src/R/Components/Impl/PackageManager/Implementation/RPackageManager.cs
- Fix #2665: Opening REPL with fresh install gives confusing message
- Fix #2673: IsolatedSession causes RHost leaks and creating RHost processes that never die
> Two bug fixes

- src/Host/Broker/Impl/Sessions/SessionManager.cs
> Fixes NRE in Broker SessionManager.GetSessions

- src/Host/Broker/Impl/Extensions/ExceptionExtensions.cs
- src/Host/Broker/Impl/Microsoft.R.Host.Broker.csproj
- src/Host/Broker/Impl/Resources.Designer.cs
- src/Host/Broker/Impl/Resources.resx
- src/Host/Broker/Impl/Startup/Program.cs
> Broker detects if server port is available.

- src/Package/Impl/ProjectSystem/Commands/SetDirectoryHereCommand.cs
- src/Package/Impl/Repl/Commands/SelectWorkingDirectoryCommand.cs
- src/Package/Impl/Repl/Commands/SetDirectoryToProjectCommand.cs
- src/Package/Impl/Repl/Commands/SetDirectoryToSourceCommand.cs
- src/Package/Impl/Repl/Commands/WorkingDirectoryCommand.cs
- src/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveWorkflow.cs
> Enable directory commands only when local host is running.

- src/Package/Impl/Shell/VsAppShell.cs
- src/R/Editor/Impl/Data/RSessionDataObject.cs
Fix #2417: AF in data
Fix #2701: EnsureInitialized must be called on the UI thread
> Fix #2417, #2701

- src/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveEvaluator.cs
Avoid using DispatchOnUIThread when printing text where possible, to prevent message queue saturation.
> Fix #2550: Interrupt printing in REPL

- src/UnitTests/Core/Impl/Microsoft.UnitTests.Core.csproj
- src/UnitTests/Core/Impl/NativeMethods.cs
- src/UnitTests/Core/Impl/ProcessUtils.cs
> Add GetPortByProcessId to allow parallel tests.

- src/R/Components/Impl/ConnectionManager/Implementation/View/ConnectionManagerControl.xaml
- src/R/Components/Impl/ConnectionManager/Implementation/View/ConnectionManagerControl.xaml.cs
- src/R/Components/Impl/ConnectionManager/Implementation/View/DesignTime/DesignTimeConnectionViewModel.cs
- src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionManagerViewModel.cs
- src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionViewModel.cs
- src/R/Components/Impl/ConnectionManager/ViewModel/IConnectionViewModel.cs
- src/R/Components/Impl/Resources.Designer.cs
- src/R/Components/Impl/Resources.resx
- src/R/Components/Test/ConnectionManager/ConnectionViewModelTest.cs
Fix #2632 Test connection does not work when supplying just the machine name
Fix #2634 Delete connection should show confirmation dialog
Fix #2635 Trailing space in the machine name make 'Save' disabled
> Workspace fixes

- src/Host/Broker/Impl/Sessions/Session.cs
> Adds suppress ui flag to remote host

- src/Host/Client/Impl/Blobs/DataTransferSession.cs
- src/Host/Client/Impl/rtvs/R/util.R
- src/R/Components/Impl/InteractiveWorkflow/Commands/SourceRScriptCommand.cs
> Fixes sourcing file on remote with debugger attached.

- src/R/Components/Impl/ConnectionManager/Implementation/View/ConnectionManagerControl.xaml
- src/R/Components/Impl/ConnectionManager/Implementation/View/ConnectionManagerControl.xaml.cs
> Skip connecting while editing text boxes.

- src/Host/Broker/Impl/About/LoadController.cs
- src/Package/Impl/Options/R/RToolsOptionsPage.cs
Calculate network load differently
> #2728 Host utilization meter doesn't work on some machines 

- src/Host/Client/Impl/Host/RemoteBrokerClient.cs
- src/Host/Client/Impl/Session/RSessionProvider.cs
- src/Package/Impl/Resources.Designer.cs
- src/Package/Impl/Resources.resx
- src/R/Components/Impl/ConnectionManager/Implementation/View/ConnectionManagerControl.xaml
- src/R/Components/Impl/ConnectionManager/Implementation/View/ConnectionManagerControl.xaml.cs
- src/R/Components/Impl/ConnectionManager/Implementation/View/DesignTime/DesignTimeConnectionManagerViewModel.cs
- src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionManagerViewModel.cs
- src/R/Components/Impl/ConnectionManager/ViewModel/IConnectionManagerViewModel.cs
#2708 Connection manager (workspaces) doesn't respect VS theme
#2740 Got 3 (three) certificate dialog when connecting to remote
#2747 Canceling test connection does not really cancel
#2742 NRE in Connection Manager
> #2708, #2740, #2747, #2742

- src/R/Components/Impl/ConnectionManager/IConnectionManager.cs
- src/R/Components/Impl/ConnectionManager/Implementation/ConnectionManager.cs
- src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionManagerViewModel.cs
> Fixes issue with creating multiple workspaces with the same machine.

- src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.DirectoryRenamed.cs
- src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.FileRenamed.cs
- src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcherEntries.cs
> Fixes issue with renaming filtered file or directory

- src/Host/Broker/Impl/Sessions/SessionManager.cs
Fixes #2754 : This change specifically fixes 404 error. I was not able to repro the 401, likely because #2766 fixed it.
> Fixes connection to remote fails with random errors.

- src/Common/Core/Impl/TaskUtilities.cs
- src/Common/Core/Impl/Threading/AsyncReaderWriterLock.Queue.cs
- src/Common/Core/Impl/Threading/AsyncReaderWriterLock.cs
- src/Common/Core/Test/Threading/AsyncReaderWriterLockTest.cs
- src/Host/Client/Impl/Host/RHost.cs
- src/Host/Client/Impl/Host/RemoteCredentialsDecorator.cs
- src/Host/Client/Impl/Session/RSession.cs
- src/Host/Client/Impl/Session/RSessionProvider.cs
- src/Host/Client/Test/Session/RSessionProviderTest.cs
- src/R/Components/Impl/ConnectionManager/Implementation/View/ConnectionManagerControl.xaml.cs
- src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionManagerViewModel.cs
- src/R/Components/Impl/PackageManager/Implementation/RPackageManager.cs
- src/R/Components/Impl/PackageManager/Implementation/ViewModel/RPackageManagerViewModel.cs
- Fix #2778: Deadlock on fast switch
- Fix #2777: Long delays may cause incorrect connection indicator
- Fix #2773: pkg mgr says disconnected
> Three bug fixes

- src/R/Components/Impl/Information/Converters.cs
- src/R/Wpf/Impl/CommonResources.xaml
Where there is no last used connection, try automatically pick local R if available
> #2769 Initial experience when i have local R's is bad

- src/Host/Broker/Impl/RemoteUri/RemoteUriHelper.cs
- src/Host/Client/Impl/BrokerServices/WebServer.cs
> Fixes connection failure issue with shiny apps

- src/Common/Core/Impl/Extensions/StreamExtensions.cs
- src/Host/Broker/Impl/RemoteUri/RemoteUriHelper.cs
- src/Host/Client/Impl/Blobs/DataTransferSession.cs
- src/Host/Client/Impl/BrokerServices/RemoteUriWebService.cs
- src/Host/Client/Test/IdeGraphicsDeviceTest.cs
- src/Host/Client/Test/RtvsPackage/BlobsTest.cs
- src/Host/Client/Test/Session/RSessionTest.Blobs.cs
- src/Package/Impl/DataInspect/Office/CsvAppFileIO.cs
- src/Package/Impl/DataInspect/Viewers/ObjectDetailsViewerProvider.cs
- src/Package/Impl/ProjectSystem/Commands/SendFileCommandBase.cs
- src/Package/Impl/ProjectSystem/Commands/SendToRemoteCommand.cs
- src/Package/Impl/ProjectSystem/Commands/SourceFilesCommand.cs
- src/Package/Impl/ProjectSystem/RDebugLaunchProvider.cs
- src/Package/Impl/Publishing/Handlers/RmdPublishHandler.cs
- src/R/Components/Impl/InteractiveWorkflow/Commands/SourceRScriptCommand.cs
- src/R/Components/Impl/Plots/Implementation/RPlotManager.cs
There is more in plot manager etc - next time.
> Add cancellations to data transfer operations

- src/Package/Impl/Shell/VsAppShell.cs
> Fixes credentials dialog isn't modal

- src/Host/Client/Impl/BrokerServices/WebServer.cs
- src/Host/Client/Impl/Host/RHost.cs
- src/Host/Client/Impl/Host/RemoteBrokerClient.cs
- src/Host/Client/Impl/Resources.Designer.cs
- src/Host/Client/Impl/Resources.resx
- src/Host/Client/Impl/Session/RSession.cs
Added more logging and info text to diagnose this better.
> Addresses the issue with help getting stuck on remote.

- src/Common/Core/Impl/Enums/YesNo.cs
- src/Common/Core/Impl/Microsoft.Common.Core.csproj
- src/Host/Client/Impl/Host/NullBrokerClient.cs
- src/Package/Impl/Microsoft.VisualStudio.R.Package.csproj
- src/Package/Impl/Options/Attributes/YesNoTypeConverter.cs
- src/Package/Impl/Options/R/RToolsOptionsPage.cs
- src/Package/Impl/Options/R/Tools/RToolsSettingsImplementation.cs
- src/Package/Impl/Resources.Designer.cs
- src/Package/Impl/Resources.resx
- src/Package/Impl/ToolWindows/ConnectionManagerWindowPane.cs
- src/Package/Impl/ToolWindows/VsConnectionManagerVisualComponentContainerFactory.cs
- src/R/Components/Impl/ConnectionManager/IConnectionManager.cs
- src/R/Components/Impl/ConnectionManager/Implementation/ConnectionManager.cs
- src/R/Components/Impl/ConnectionManager/Implementation/ConnectionManagerVisualComponent.cs
- src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionManagerViewModel.cs
- src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionStatusBaseViewModel.cs
- src/R/Components/Impl/Resources.Designer.cs
- src/R/Components/Impl/Resources.resx
- src/R/Components/Impl/Settings/IRSettings.cs
- src/R/Components/Test/ConnectionManager/ConnectionManagerTest.cs
- src/R/Components/Test/ConnectionManager/ConnectionManagerViewModelTest.cs
- src/R/Components/Test/Fakes/VisualComponentFactories/TestConnectionManagerVisualComponentContainerFactory.cs
- src/R/Components/Test/StubFactories/RSettingsStubFactory.cs
- src/R/Components/Test/Stubs/RSettingsStub.cs
- src/R/Support/Impl/Settings/IRToolsSettings.cs
- src/R/Support/Test/Utility/TestRToolsSettings.cs
- Fix #2920: Display warning dialog with "don't show me this again" сheckbox when switching Workspaces.
- Fix #2921: Not loading last used local workspace on startup
- Fix #2918: Creating connection with same name and URL bu different arguments de-sync indicators
- Fix #2811: Give warning that session will be terminated when user tries connect to another R
> 4 bug fixes + tests

- src/Host/Broker/Impl/About/AboutController.cs
- src/Host/Broker/Impl/Interpreters/InterpreterManager.cs
- src/R/Components/Impl/InteractiveWorkflow/Commands/SessionInformationCommand.cs
- src/R/Components/Impl/Resources.Designer.cs
- src/R/Components/Impl/Resources.resx
- Change guilds to ints
- Output interpreter names and IDs
- Provide guidance message to the user
> #2929 Simplify selection of remote Rs 

- src/Markdown/Editor/Impl/Classification/Background/BackgroundTextAdornment.cs
- src/Markdown/Editor/Impl/Classification/Background/BackgroundTextAdornmentFactory.cs
- src/Markdown/Editor/Impl/ContainedLanguage/RLanguageHandler.cs
- src/Package/Impl/Options/R/Commands/SetupRemoteCommand.cs
- src/R/Components/Impl/InteractiveWorkflow/Commands/SessionInformationCommand.cs
- src/R/Components/Impl/Resources.Designer.cs
- src/R/Components/Impl/Resources.resx
- src/R/Wpf/Impl/CommonResources.xaml
#2948 NRE is markdown region highlighter 
#2931 Check remote version and output message if client is different 
#2850 Need link to instructions page for the remote setup
> #2850 #2931 #2948

- src/Host/Broker/Impl/Resources.Designer.cs
- src/Host/Broker/Impl/Resources.resx
- src/Host/Client/Impl/Definitions/IRSession.cs
- src/Host/Client/Impl/Host/BrokerClient.cs
- src/Host/Client/Impl/Resources.Designer.cs
- src/Host/Client/Impl/Resources.resx
- src/R/Components/Impl/ConnectionManager/Implementation/View/ConnectionManagerControl.xaml
- src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionManagerViewModel.cs
- src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionViewModel.cs
- src/R/Components/Impl/InteractiveWorkflow/Commands/SessionInformationCommand.cs
- src/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveEvaluator.cs
- src/R/Components/Impl/Resources.Designer.cs
- src/R/Components/Impl/Resources.resx
- src/R/Components/Test/ConnectionManager/ConnectionViewModelTest.cs
#2952 Output name of the R interpreter when it is not found
#2937 After changing connection URL message is misleading
Harden URL checks
Disable connect button when URL is invalid
Handle Enter better
Add bad URL check in HTTP client it case it still leaks there
> #2937 #2952 + hardened URL checks

- src/Common/Core/Impl/IO/FileSystem.cs
- src/Host/Client/Impl/BrokerServices/WebServer.cs
- src/Host/Client/Impl/Definitions/IConsole.cs
- src/Host/Client/Impl/Host/RemoteBrokerClient.cs
- src/Host/Client/Impl/Session/NullConsole.cs
- src/Host/Client/Impl/Session/RSessionProvider.cs
- src/Package/Impl/ProjectSystem/Commands/SendFileCommandBase.cs
- src/Package/Impl/ProjectSystem/Commands/SendToRemoteCommand.cs
- src/Package/Impl/ProjectSystem/Commands/SourceFilesCommand.cs
- src/Package/Impl/Resources.Designer.cs
- src/Package/Impl/Resources.resx
- src/R/Components/Impl/InteractiveWorkflow/Commands/SessionInformationCommand.cs
- src/R/Components/Impl/InteractiveWorkflow/Implementation/InteractiveWindowConsole.cs
- src/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveEvaluator.cs
> Uses progress dialog box to show compression, transfer and extraction of files.

- src/Host/Broker/Impl/Resources.Designer.cs
- src/Host/Broker/Impl/Resources.resx
- src/Host/Client/Impl/Host/RHost.cs
- src/Host/Client/Impl/Resources.Designer.cs
- src/Host/Client/Impl/Resources.resx
- src/Host/Client/Impl/Session/RSession.cs
- src/Package/Impl/Resources.Designer.cs
- src/Package/Impl/Resources.resx
- src/R/Components/Impl/Resources.Designer.cs
- src/R/Components/Impl/Resources.resx
- Suppress detailed exception information in REPL
- Log initialization errors
- Fix message wording
> Message wording and some diagnostic logging

- src/Package/Impl/Resources.Designer.cs
- src/Package/Impl/Resources.resx
> Typo fixed

- src/Common/Core/Impl/Security/SecurityService.cs
- src/Host/Client/Impl/Resources.Designer.cs
- src/Host/Client/Impl/Resources.resx
- src/R/Components/Impl/InteractiveWorkflow/Commands/SessionInformationCommand.cs
- src/R/Components/Impl/Resources.Designer.cs
- src/R/Components/Impl/Resources.resx
#2987 Azure Server is not showing the computer stats red text
#2955 Fix inconsistencies in our dialog boxes for yes / no
#2971 bad english for host switch
> #2987 #2955 #2971

- src/Common/Core/Impl/NativeMethods.cs
- src/Common/Core/Impl/Security/SecurityService.cs
Instead of the device-pin that currently does not work.
> Show username-password prompt by default

- src/Host/Client/Impl/Session/RSession.cs
Detect when a ReadConsole callback was interrupted via CancelAll, and handle that case appropriately.
> Fix #2881: Host crashes after interrupting, then running another command

- src/SetupRemote/Product.wxs
- src/SetupRemote/SetupRemote.wixproj
> Installer now adds firewall exception and auto starts seclogon

- src/Host/Client/Impl/BrokerServices/WebService.cs
- src/Host/Client/Impl/Host/BrokerClient.cs
> Fixes crashes caused while preparing logging messages.

- src/Common/Core/Impl/Extensions/IOExtensions.cs
- src/Package/Impl/Help/HelpVisualComponent.cs
> #3051 Can't open pdf when using internal help browser

- src/SetupRHostRemote/Product.wxs
- src/SetupRHostRemote/SetupRHostRemote.wixproj
- src/SetupRemote/Product.wxs
> Moving RHost Firewall exception to the RHost Remote installer

- src/Host/Broker/Impl/Sessions/Session.cs
- src/Host/Client/Impl/rtvs/R/util.R
- src/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveEvaluator.cs
- src/R/Components/Impl/Resources.Designer.cs
- src/R/Components/Impl/Resources.resx
> Handles issues with blocked REPL due to UI in remote

- src/Package/Impl/DataInspect/VisualGrid/VisualGridScroller.cs
Use BufferBlock instead of BlockingCollection in VisualGridScroller, to avoid blocking waits across awaits.
> Fix #3076: Getting the class of an object after a failed View() hangs the REPL

- src/R/Components/Impl/Resources.Designer.cs
- src/R/Components/Impl/Resources.resx
> Added line breaks to long delete message.

- src/Host/Client/Impl/BrokerServices/RemoteUriWebService.cs
- src/Host/Client/Impl/BrokerServices/WebServer.cs
- src/Host/Client/Impl/Resources.Designer.cs
- src/Host/Client/Impl/Resources.resx
> Handle exceptions while running HTTP web server for remote.

- src/Package/Impl/DataInspect/DataImport/ImportDataWindow.xaml
- src/Package/Impl/DataInspect/DataImport/ImportDataWindow.xaml.cs
#3146 Shift+Tab in 'Import Data from text file' closes the dialog
- Handle specific keys only
#3147 Focus is rendered incorrectly in 'import data' dialog
- remove bg/fg settings, use default control styling
> #3146 #3147

- src/Package/Impl/Wpf/ThemeUtilities.cs
> #3176 High contrast shows error when opening Wokspaces

- src/Common/Core/Impl/Security/ISecurityService.cs
- src/Common/Core/Impl/Security/SecurityService.cs
- src/Common/Core/Impl/Security/SecurityUtilities.cs
- src/Host/Client/Impl/Host/RemoteCredentialsDecorator.cs
- src/R/Components/Test/ConnectionManager/ConnectionManagerTest.cs
This is a surgical fix for 1_0
> Surgical fix for the password bug.

- src/Package/Impl/DataInspect/VisualGrid/VisualGrid.cs
- src/Package/Impl/DataInspect/VisualGrid/VisualGridScroller.cs
And simplify main thread paint a bit
> Remove forced background paint

- src/R/Components/Impl/InteractiveWorkflow/Commands/SourceRScriptCommand.cs
> Source R file will be available for remote only if remote file is available.

- src/Package/Impl/DataInspect/VisualGrid/MatrixView.xaml
- src/Package/Impl/DataInspect/VisualGrid/VisualGrid.cs
- src/Package/Impl/Options/R/Editor/REditorOptionsDialog.cs
- src/Package/Impl/Resources.Designer.cs
- src/Package/Impl/Resources.resx
- src/R/Core/Impl/Formatting/RFormatOptions.cs
- src/R/Core/Impl/Formatting/RFormatter.cs
- src/R/Editor/Impl/Completion/Providers/ParameterNameCompletionProvider.cs
- src/R/Editor/Impl/Formatting/FormatOperations.cs
- src/R/Support/Impl/Help/FunctionRdDataProvider.cs
- src/R/Support/Impl/Help/IntelliSenseRSession.cs
- src/R/Support/Impl/Help/Packages/PackageIndex.cs
- src/R/Support/Impl/Help/Packages/PackageInfo.cs
See https://github.com/Microsoft/RTVS/pull/3252
> PR 3235 into Release/1_0

- loc/lcl/CHS/Microsoft.R.Host.UserProfile.exe.lcl
- loc/lcl/ESN/Microsoft.R.Support.dll.lcl
- loc/lcl/ESN/Microsoft.VisualStudio.R.Sql.dll.lcl
- loc/lcl/FRA/Microsoft.VisualStudio.R.Sql.dll.lcl
- loc/lcl/PLK/Microsoft.Markdown.Editor.dll.lcl
LEGO: Pull request from lego/hb_835_20170303094045989 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170303094045989 to master

- loc/lcl/FRA/Microsoft.R.Host.Broker.exe.lcl
LEGO: Pull request from lego/hb_835_20170309001019154 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170309001019154 to master

- src/Setup/Product.wxs
- src/SetupCustomActions/CustomAction.cs
Removed custom action since bundle now blocks the setup. Bundle PR incoming.
> Setup block for unsupported versions of the IDE 

- src/Host/Broker/Impl/RemoteUri/RemoteUriHelper.cs
- src/Host/Client/Impl/BrokerServices/RemoteUriWebService.cs
> Fixes issue with shiny and uploading files.

- src/Host/Broker/Impl/RemoteUri/RemoteUriHelper.cs
- src/Host/Client/Impl/BrokerServices/RemoteUriWebService.cs
https://github.com/Microsoft/RTVS/pull/3295
> Porting from 1_0

- src/Debugger/Impl/project.14.0.json
- src/Languages/Editor/Impl/project.14.0.json
- src/Mocks/Editor/project.14.0.json
- src/Mocks/VisualStudio/project.14.0.json
- src/Package/Impl/Imaging/ImagesProvider.cs
- src/Package/Impl/project.14.0.json
- src/Package/Test/project.14.0.json
- src/ProjectSystem/Impl/project.14.0.json
- src/ProjectSystem/Test/project.14.0.json
- src/R/Editor/Impl/Completion/Providers/FilesCompletionProvider.cs
- src/R/Support/Impl/project.14.0.json
Also fixes 14.0 references to VS SDK. Not sure how 15.0 references leaked into them.
> #3305 File completion on remote workspace duplicates directory entries

- src/Common/Core/Impl/Diagnostics/Check.cs
- src/Common/Core/Impl/Services/IServiceManager.cs
- src/Common/Core/Impl/Services/ServiceManager.cs
- src/Common/Core/Test/Microsoft.Common.Core.Test.csproj
- src/Common/Core/Test/Services/ServiceManagerTests.cs
Also added checks that `ServiceManager` isn't disposed
> Fix #3322: ServiceManager doesn't detect reentrancy

- src/Host/Client/Impl/Resources.Designer.cs
- src/Host/Client/Impl/Resources.resx
- src/Host/Client/Impl/Session/RSession.cs
#3319 . In linux, we cannot call eval before we start the main loop.
> Moving suggest MRO from RHost to RTVS

- src/Host/Broker/Impl/Security/Certificates.cs
- src/Host/Broker/Impl/Security/SecurityOptions.cs
- src/Host/Broker/Impl/Security/TlsConfiguration.cs
> Adds option to use certificate file for use with TLS (SSL)

- src/Package/Impl/Microsoft.VisualStudio.R.Package.csproj
- src/R.sln
This is the other side of https://github.com/Microsoft/R-Host/pull/124. Again, creating a separate branch for this, until we figure out the build system side of the story.
> Use MSYS2 build of Microsoft.R.Host

- src/Package/Impl/ProjectSystem/ProjectSystemServices.cs
Properly figure out startup project
> #3371 Active startup project is calculated incorrectly 

- src/Windows/Core/Impl/Security/SecurityService.cs
Looks like a `return` was missed.
> Fix for credential save issue.

- loc/lcl/PTB/Microsoft.VisualStudio.R.Package.dll.lcl
LEGO: Pull request from lego/hb_835_20170401024514487 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170401024514487 to master

- src/Host/Client/Impl/rtvs/R/util.R
- src/Package/Impl/Interop/CommandTargetToOleShim.cs
- src/Package/Impl/Publishing/Commands/PreviewCommand.cs
- src/Package/Impl/Publishing/Commands/PreviewPdfCommand.cs
> Added executable_exists_on_path with platform specific implementation.

- loc/lcl/CHT/Microsoft.VisualStudio.R.Package.dll.lcl
LEGO: Pull request from lego/hb_835_20170405144550054 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170405144550054 to master

- src/Package/Impl/DataInspect/DataImport/EnterUrl.xaml
- src/Package/Impl/DataInspect/DataImport/ImportDataWindow.xaml
Give name matching label of the text and combo boxes.
> VSTS 402127 - 'Name' is missing in accessible properties

- loc/lcl/RUS/Microsoft.R.Components.dll.lcl
- loc/lcl/RUS/Microsoft.VisualStudio.R.Package.dll.lcl
LEGO: Pull request from lego/hb_835_20170413144528979 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170413144528979 to master

- loc/lcl/CHS/Microsoft.R.Components.dll.lcl
- loc/lcl/CHS/Microsoft.VisualStudio.R.Package.dll.lcl
- loc/lcl/CHT/Microsoft.R.Components.dll.lcl
- loc/lcl/CHT/Microsoft.VisualStudio.R.Package.dll.lcl
- loc/lcl/KOR/Microsoft.R.Components.dll.lcl
LEGO: Pull request from lego/hb_835_20170418204637119 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170418204637119 to master

- src/Common/Wpf/Impl/Controls/ExpandCollapseAutomationPeer.cs
- src/Common/Wpf/Impl/Controls/ExpandCollapseButton.cs
- src/Common/Wpf/Impl/Controls/ExpandCollapseMode.cs
- src/Common/Wpf/Impl/Microsoft.Common.Wpf.csproj
- src/Package/Impl/DataInspect/VisualGrid/HeaderTextVisual.cs
- src/Package/Impl/DataInspect/VisualGrid/MatrixView.xaml
- src/Package/Impl/ProjectSystem/PropertyPages/Run/RunPageControl.xaml
- src/Package/Impl/ProjectSystem/PropertyPages/Wpf/WpfBasedPropertyPage.cs
- src/Package/Impl/Resources.Designer.cs
- src/Package/Impl/Resources.resx
- src/R/Components/Impl/ConnectionManager/Implementation/View/ConnectionManagerControl.xaml
- src/R/Components/Impl/Plots/Implementation/View/RPlotHistoryControl.xaml
- src/R/Components/Impl/Resources.Designer.cs
- src/R/Components/Impl/Resources.resx
- src/R/Wpf/Impl/CommonResources.xaml
- Fix #3434: Parts of project settings not localized
- Fix #3417: Allow mouse wheel scroll in any area of View() window
- Fix #3416: Sorting indicator in Grid View is wrong
- Fix expand/collapse element accessibility properties
> Accessibility & localization fixes

- loc/lcl/ESN/Microsoft.VisualStudio.R.Package.dll.lcl
- loc/lcl/RUS/Microsoft.VisualStudio.R.Package.dll.lcl
LEGO: Pull request from lego/hb_835_20170427084520405 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170427084520405 to master

- loc/lcl/CSY/Microsoft.VisualStudio.R.Package.dll.lcl
- loc/lcl/FRA/Microsoft.VisualStudio.R.Package.dll.lcl
- loc/lcl/ITA/Microsoft.VisualStudio.R.Package.dll.lcl
- loc/lcl/PLK/Microsoft.VisualStudio.R.Package.dll.lcl
- loc/lcl/PTB/Microsoft.VisualStudio.R.Package.dll.lcl
- loc/lcl/RUS/Microsoft.VisualStudio.R.Package.dll.lcl
- loc/lcl/TRK/Microsoft.VisualStudio.R.Package.dll.lcl
LEGO: Pull request from lego/hb_835_20170427144538978 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170427144538978 to master

- loc/lcl/JPN/Microsoft.R.Components.dll.lcl
- loc/lcl/JPN/Microsoft.R.Host.Client.dll.lcl
- loc/lcl/JPN/Microsoft.VisualStudio.R.Package.dll.lcl
- loc/lcl/PLK/Microsoft.R.Components.dll.lcl
- loc/lcl/PLK/Microsoft.VisualStudio.R.Package.dll.lcl
LEGO: Pull request from lego/hb_835_20170428144531321 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170428144531321 to master

- src/Package/Impl/DataInspect/VariableView.xaml
- src/Package/Impl/DataInspect/VariableView.xaml.cs
- src/Package/Impl/ProjectSystem/PropertyPages/Run/RunPageControl.xaml
- src/R/Wpf/Impl/CommonResources.xaml
- Fix #3459: Error in project settings UI Run page
- Fix context menu crash in VE
> Couple of bug fixes

- loc/lcl/CHS/Microsoft.R.Components.dll.lcl
- loc/lcl/CHT/Microsoft.R.Components.dll.lcl
- loc/lcl/CSY/Microsoft.R.Components.dll.lcl
- loc/lcl/DEU/Microsoft.R.Components.dll.lcl
- loc/lcl/ESN/Microsoft.R.Components.dll.lcl
- loc/lcl/FRA/Microsoft.R.Components.dll.lcl
- loc/lcl/ITA/Microsoft.R.Components.dll.lcl
- loc/lcl/JPN/Microsoft.R.Components.dll.lcl
- loc/lcl/KOR/Microsoft.R.Components.dll.lcl
- loc/lcl/PLK/Microsoft.R.Components.dll.lcl
- loc/lcl/PTB/Microsoft.R.Components.dll.lcl
- loc/lcl/RUS/Microsoft.R.Components.dll.lcl
- loc/lcl/TRK/Microsoft.R.Components.dll.lcl
LEGO: Pull request from lego/hb_835_20170501175325853 to Release/1_0 with localized lcls
> LEGO: Pull request from lego/hb_835_20170501175325853 to Release/1_0

- src/Common/Core/Impl/OS/Win32EnvironmentBlock.cs
- src/Host/Broker/Impl/Sessions/Session.cs
R environment variables  were not passed on to the R session.
> R environment variables 

- loc/lcl/CHS/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/CHT/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/CSY/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/DEU/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/ESN/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/FRA/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/ITA/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/JPN/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/KOR/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/PLK/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/PTB/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/RUS/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/TRK/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
LEGO: Pull request from lego/hb_835_20170502071613433 to Release/1_0 with localized lcls
> LEGO: Pull request from lego/hb_835_20170502071613433 to Release/1_0

- loc/lcl/CHS/Microsoft.R.Components.dll.lcl
- loc/lcl/CHS/Microsoft.VisualStudio.R.Package.dll.lcl
- loc/lcl/CHT/Microsoft.R.Components.dll.lcl
- loc/lcl/CHT/Microsoft.VisualStudio.R.Package.dll.lcl
- loc/lcl/ESN/Microsoft.R.Components.dll.lcl
- loc/lcl/ESN/Microsoft.VisualStudio.R.Package.dll.lcl
- loc/lcl/TRK/Microsoft.R.Components.dll.lcl
- loc/lcl/TRK/Microsoft.VisualStudio.R.Package.dll.lcl
LEGO: Pull request from lego/hb_835_20170502144528874 to Release/1_0 with localized lcls
> LEGO: Pull request from lego/hb_835_20170502144528874 to Release/1_0

- src/Windows/Core/Impl/OS/Win32EnvironmentBlock.cs
- src/Windows/Host/Broker/Impl/Services/WindowsRHostProcessService.cs
Changes include:
1. R-host update to include fixes for R 3.4
2. Broker updated to capture R environment variables.
> Port changes from 1_0 to master

- loc/lcl/PTB/Microsoft.R.Components.dll.lcl
- loc/lcl/PTB/Microsoft.VisualStudio.R.Package.dll.lcl
LEGO: Pull request from lego/hb_835_20170502204523301 to Release/1_0 with localized lcls
> LEGO: Pull request from lego/hb_835_20170502204523301 to Release/1_0

- src/Host/Broker/Impl/Sessions/Session.cs
> Added a command line argument for the R binary path.

- loc/lcl/CSY/Microsoft.R.Components.dll.lcl
- loc/lcl/CSY/Microsoft.VisualStudio.R.Package.dll.lcl
- loc/lcl/DEU/Microsoft.R.Components.dll.lcl
- loc/lcl/DEU/Microsoft.VisualStudio.R.Package.dll.lcl
LEGO: Pull request from lego/hb_835_20170503144521275 to Release/1_0 with localized lcls
> LEGO: Pull request from lego/hb_835_20170503144521275 to Release/1_0

- src/R/Editor/Impl/Completion/Engine/RCompletionEngine.cs
- src/R/Editor/Impl/Completion/Providers/ParameterNameCompletionProvider.cs
- src/R/Editor/Test/Completions/RCompletionSourceTest.cs
Handle case when caret is right at the end and there is no closing brace in the function call.
> #3455 Intellisense for Parameters not working

- loc/lcl/PTB/Microsoft.R.Components.dll.lcl
LEGO: Pull request from lego/hb_835_20170504024527907 to Release/1_0 with localized lcls
> LEGO: Pull request from lego/hb_835_20170504024527907 to Release/1_0

- loc/lcl/PLK/Microsoft.R.Components.dll.lcl
- loc/lcl/PLK/Microsoft.VisualStudio.R.Package.dll.lcl
LEGO: Pull request from lego/hb_835_20170504084515871 to Release/1_0 with localized lcls
> LEGO: Pull request from lego/hb_835_20170504084515871 to Release/1_0

- loc/lcl/FRA/Microsoft.R.Components.dll.lcl
- loc/lcl/FRA/Microsoft.VisualStudio.R.Package.dll.lcl
LEGO: Pull request from lego/hb_835_20170504204526038 to Release/1_0 with localized lcls
> LEGO: Pull request from lego/hb_835_20170504204526038 to Release/1_0

- src/Package/Impl/Sql/Publish/SProcPublisher.cs
- src/R/Components/Impl/Sql/Publish/IDacPackage.cs
- src/R/Sql/Impl/Publish/DacPackageImpl.cs
> Dispose DACPAC after delpoyment

- loc/lcl/ITA/Microsoft.R.Components.dll.lcl
- loc/lcl/ITA/Microsoft.VisualStudio.R.Package.dll.lcl
LEGO: Pull request from lego/hb_835_20170505024524476 to Release/1_0 with localized lcls
> LEGO: Pull request from lego/hb_835_20170505024524476 to Release/1_0

- loc/lcl/KOR/Microsoft.R.Components.dll.lcl
- loc/lcl/KOR/Microsoft.VisualStudio.R.Package.dll.lcl
- loc/lcl/RUS/Microsoft.R.Components.dll.lcl
- loc/lcl/RUS/Microsoft.VisualStudio.R.Package.dll.lcl
LEGO: Pull request from lego/hb_835_20170505084527664 to Release/1_0 with localized lcls
> LEGO: Pull request from lego/hb_835_20170505084527664 to Release/1_0

- loc/lcl/CHS/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/CHT/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/CSY/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/DEU/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/ESN/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/FRA/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/ITA/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/JPN/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/KOR/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/PLK/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/PTB/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/RUS/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/TRK/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
LEGO: Pull request from lego/hb_835_20170506024527927 to Release/1_0 with localized lcls
> LEGO: Pull request from lego/hb_835_20170506024527927 to Release/1_0

- loc/lcl/ITA/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
LEGO: Pull request from lego/hb_835_20170507024516988 to Release/1_0 with localized lcls
> LEGO: Pull request from lego/hb_835_20170507024516988 to Release/1_0

- loc/lcl/CHT/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/CSY/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/KOR/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
LEGO: Pull request from lego/hb_835_20170508084513305 to Release/1_0 with localized lcls
> LEGO: Pull request from lego/hb_835_20170508084513305 to Release/1_0

- loc/lcl/CHS/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/DEU/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/ESN/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/JPN/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/PLK/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/TRK/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
LEGO: Pull request from lego/hb_835_20170508144523896 to Release/1_0 with localized lcls
> LEGO: Pull request from lego/hb_835_20170508144523896 to Release/1_0

- loc/lcl/FRA/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
- loc/lcl/PTB/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
LEGO: Pull request from lego/hb_835_20170508204517886 to Release/1_0 with localized lcls
> LEGO: Pull request from lego/hb_835_20170508204517886 to Release/1_0

- src/Host/Client/Impl/Definitions/IRSessionProvider.cs
- src/Host/Client/Impl/Session/RSessionProvider.cs
- src/Package/Impl/ProjectSystem/RProjectLoadHooks.cs
- src/R/Components/Impl/InteractiveWorkflow/IRInteractiveWorkflowProvider.cs
I've tried several different approaches, but I believe this one will be smallest and safest change
> Fix #3442: RTVS Verson 1.0.30321.1407 with VS 2015 Community edition does not save R

- loc/lcl/RUS/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll.lcl
LEGO: Pull request from lego/hb_835_20170510204520061 to Release/1_0 with localized lcls
> LEGO: Pull request from lego/hb_835_20170510204520061 to Release/1_0

- src/Common/Core/Impl/Threading/MainThreadExtensions.cs
- src/Package/Impl/DataInspect/VariableView.xaml
- src/Package/Impl/InfoBar/InfoBarEvents.cs
- src/Package/Impl/InfoBar/VsInfoBar.cs
- src/Package/Impl/InfoBar/VsInfoBarProvider.cs
- src/Package/Impl/Microsoft.VisualStudio.R.Package.csproj
- src/Package/Impl/ToolWindows/PackageManagerWindowPane.cs
- src/Package/Impl/ToolWindows/VsRPackageManagerVisualComponent.cs
- src/R/Components/Impl/InfoBar/IInfoBarProvider.cs
- src/R/Components/Impl/Microsoft.R.Components.csproj
- src/R/Components/Impl/PackageManager/Implementation/RPackageManagerVisualComponent.cs
- src/R/Components/Impl/PackageManager/Implementation/View/DesignTime/DesignTimeRPackageManagerViewModel.cs
- src/R/Components/Impl/PackageManager/Implementation/View/PackageManagerControl.xaml
- src/R/Components/Impl/PackageManager/Implementation/View/PackageManagerControl.xaml.cs
- src/R/Components/Impl/PackageManager/Implementation/ViewModel/RPackageManagerViewModel.cs
- src/R/Components/Impl/PackageManager/ViewModel/IRPackageManagerViewModel.cs
- src/R/Components/Impl/Resources.Designer.cs
- src/R/Components/Impl/Resources.resx
- src/R/Components/Test/Fakes/InfoBar/TestInfoBar.cs
- src/R/Components/Test/Fakes/InfoBar/TestInfoBarProvider.cs
- src/R/Components/Test/Fakes/VisualComponentFactories/TestRPackageManagerVisualComponentContainerFactory.cs
- src/R/Components/Test/Microsoft.R.Components.Test.csproj
- Fix #3348: Make package manager message more friendly
- Fix #3458: Use VS infobar instead of custom implementation in Package Manager
> Fix PM accessability issues

- .gitmodules
- src/Host/Broker/Impl/About/AboutController.cs
- src/Host/Broker/Impl/Services/ISystemInfoService.cs
- src/Host/Broker/Impl/Sessions/Session.cs
- src/Host/Broker/Impl/Sessions/SessionManager.cs
- src/Host/Broker/Impl/Sessions/SessionsController.cs
- src/Host/Protocol/Impl/AboutHost.cs
- src/Host/Protocol/Impl/VideoCardInfo.cs
- src/Linux/Core/Impl/OS/UnixProcessServices.cs
- src/Linux/Host/Broker/Impl/Resources.Designer.cs
- src/Linux/Host/Broker/Impl/Resources.resx
- src/Linux/Host/Broker/Impl/Security/UnixClaims.cs
- src/Linux/Host/Broker/Impl/Services/AuthenticationOnlyMessage.cs
- src/Linux/Host/Broker/Impl/Services/LinuxAuthenticationService.cs
- src/Linux/Host/Broker/Impl/Services/LinuxSystemInfoService.cs
- src/Linux/Host/Broker/Impl/Services/Utility.cs
- src/Linux/Host/Broker/Impl/Startup/LinuxStartup.cs
- src/Linux/Native/RunAsUser/Microsoft.R.Host.RunAsUser.vcxproj
- src/Linux/Native/RunAsUser/Microsoft.R.Host.RunAsUser.vcxproj.filters
- src/Linux/Native/RunAsUser/main.cpp
- src/Linux/Native/RunAsUser/readme.txt
- src/Linux/Native/RunAsUser/util.h
- src/R.sln
- src/Windows/Host/Broker/Impl/Services/WindowsSystemInfoService.cs
- src/Windows/R/Components/Impl/InteractiveWorkflow/Commands/SessionInformationCommand.cs
- src/Windows/R/Components/Impl/Resources.Designer.cs
- src/Windows/R/Components/Impl/Resources.resx
1. Video card information is extracted in linux
2. PAM authentication support using RunAsUser binary
3. implementation of IAuthenticationService on linux
> Linux broker: part 2

- src/R/Editor/Impl/Functions/Definitions/IIntellisenseHostSession.cs
- src/R/Editor/Impl/Functions/Definitions/IPackageIndex.cs
- src/R/Editor/Impl/Functions/IntelliSenseRSession.cs
- src/R/Editor/Impl/Functions/PackageIndex.cs
> Port fix for the 'install.packages' locking dlls

- src/Host/Client/Impl/Session/RSessionEvaluationCommands.cs
> Fixes setLocale issue on Linux

- src/Windows/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveEvaluator.cs
> Fixes issue with text progress.

- src/Linux/Host/Broker/Impl/Services/LinuxRHostProcessService.cs
- src/Linux/Host/Broker/Impl/Services/Utility.cs
- src/Linux/Host/Broker/Impl/Startup/Program.cs
- src/Linux/Native/RunAsUser/main.cpp
- Fix for RunAsUser does not return immediately upon failure for AuthOnly request.
- Checking EndOfStream affects Reading stream later.
- Simplifying the environment capture.
> Bug fixes for linux remote

- loc/lcl/JPN/Microsoft.R.Components.dll.lcl
- loc/lcl/KOR/Microsoft.R.Components.dll.lcl
LEGO: Pull request from lego/hb_835_20170531084522985 to Release/1_0 with localized lcls
> LEGO: Pull request from lego/hb_835_20170531084522985 to Release/1_0

- loc/lcl/CHS/Microsoft.R.Components.dll.lcl
- loc/lcl/CHT/Microsoft.R.Components.dll.lcl
- loc/lcl/CSY/Microsoft.R.Components.dll.lcl
- loc/lcl/DEU/Microsoft.R.Components.dll.lcl
- loc/lcl/ESN/Microsoft.R.Components.dll.lcl
- loc/lcl/FRA/Microsoft.R.Components.dll.lcl
- loc/lcl/ITA/Microsoft.R.Components.dll.lcl
- loc/lcl/PLK/Microsoft.R.Components.dll.lcl
- loc/lcl/PTB/Microsoft.R.Components.dll.lcl
- loc/lcl/RUS/Microsoft.R.Components.dll.lcl
- loc/lcl/TRK/Microsoft.R.Components.dll.lcl
LEGO: Pull request from lego/hb_835_20170531204539602 to Release/1_0 with localized lcls
> LEGO: Pull request from lego/hb_835_20170531204539602 to Release/1_0

- src/Linux/Host/Broker/Impl/Services/AuthenticateAndRunMessage.cs
- src/Linux/Host/Broker/Impl/Services/LinuxRHostProcessService.cs
- src/Linux/Host/Broker/Impl/Services/Utility.cs
- src/Linux/Native/RunAsUser/Microsoft.R.Host.RunAsUser.vcxproj
- src/Linux/Native/RunAsUser/Microsoft.R.Host.RunAsUser.vcxproj.filters
- src/Linux/Native/RunAsUser/log.cpp
- src/Linux/Native/RunAsUser/log.h
- src/Linux/Native/RunAsUser/main.cpp
- src/Linux/Native/RunAsUser/stdafx.h
- src/Linux/R/Interpreters/Impl/RInterpreterInfo.cs
Fixes #3576
Implements #3549
Adds current working directory when RHost starts.
> Few more fixes

- src/Common/Core/Impl/Services/IServiceManager.cs
- src/Common/Core/Impl/Services/ServiceManager.cs
- src/Common/Core/Impl/Services/ServiceManagerExtensions.cs
- src/Common/Core/Test/Services/ServiceManagerTests.cs
- src/Package/Impl/Shell/VsAppShell.Services.cs
Remove `IServiceManager` method that almost not used and can be replaced with existing extension method
> Remove IServiceManager.AddService(Type)

- src/Languages/Core/Impl/Braces/BraceToken.cs
- src/Languages/Core/Impl/Braces/BraceTokenType.cs
- src/Languages/Core/Impl/Braces/BraceTokenizer.cs
- src/Languages/Core/Test/Braces/BraceTokenizerTest.cs
- src/Languages/Core/Test/Bytes/ByteStreamTest.cs
- src/Languages/Core/Test/Microsoft.Languages.Core.Test.csproj
- src/Package/Impl/Publishing/Commands/PreviewCommand.cs
- src/Windows/Editor/Impl/BraceMatch/BraceMatcher.cs
- src/Windows/Editor/Impl/Text/EditorBufferSnapshot.cs
- src/Windows/Markdown/Editor/Impl/BraceMatch/RmdBraceHighlightProvider.cs
- src/Windows/Markdown/Editor/Impl/BraceMatch/RmdBraceMatcher.cs
- src/Windows/Markdown/Editor/Impl/BraceMatch/RmdBraceMatcherProvider.cs
- src/Windows/Markdown/Editor/Impl/Classification/MarkdownClassificationTypes.cs
- src/Windows/Markdown/Editor/Impl/Commands/MdCommandFactory.cs
- src/Windows/Markdown/Editor/Impl/Microsoft.Markdown.Editor.Windows.csproj
- src/Windows/Markdown/Editor/Impl/Tokens/MarkdownTokenType.cs
- src/Windows/R/Editor/Impl/RData/BraceMatch/RdBraceMatcherProvider.cs
Fix #3623 
R Markdown brace matching/highlight
Install `rmarkdown` rather than complain
> R Markdown brace matching + #3623

- src/Host/Protocol/Test/RHostPipe/RHostPipeTest.cs
- src/Package/Impl/Repl/VsRInteractiveWindowComponentContainerFactory.cs
- src/Package/Test/Mocks/InteractiveWindowComponentContainerFactoryMock.cs
- src/Windows/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveWindowVisualComponent.cs
- src/Windows/R/Components/Test/ConnectionManager/ConnectionManagerViewModelTest.cs
- src/Windows/R/Components/Test/Fakes/VisualComponentFactories/TestRInteractiveWindowComponentContainerFactory.cs
- src/Windows/R/Components/Test/InteractiveWorkflow/RInteractiveEvaluatorTest.cs
- Fix several tests
- Fix #3336: Some ConnectionManagerViewModelTest fail if there are no user created connections
- Fix #3009: Some tests always fail in a group
> Test fixes

- src/Host/Broker/Impl/Microsoft.R.Host.Broker.csproj
- src/Host/Broker/Impl/RemoteUri/RemoteUriHelper.cs
- src/Host/Broker/Impl/Sessions/Session.cs
- src/Linux/Host/Broker/Impl/Services/LinuxRHostProcessService.cs
- src/Package/Impl/Microsoft.VisualStudio.R.Package.csproj
- src/Windows/Host/Client/Impl/BrokerServices/RemoteUriWebService.cs
- src/Windows/Setup/RemoteServices/Assemblies.wxi
fixes #3349.
Few other bugs discovered while testing.
> Bunch of fixes

- src/R/Components/Impl/ConnectionManager/Implementation/View/ConnectionManagerControl.xaml
- src/R/Support/Impl/Help/Functions/FunctionIndex.cs
User and Watson reported.
Add accessible name to R argument field
> Fix crash and accessibility issue

- src/Package/Impl/History/VsRHistoryVisualComponentContainerFactory.cs
History provider is no longer exported
> Fix crash creating history window

- src/Common/Core/Impl/Net/Network.cs
- src/Host/Client/Impl/Extensions/UriExtensions.cs
- src/Host/Client/Impl/Microsoft.R.Host.Client.csproj
- src/Host/Client/Impl/Resources.Designer.cs
- src/Host/Client/Impl/Resources.resx
> Fix for azure ping issue.

- src/Host/Client/Impl/rtvs/R/overrides.R
- src/Linux/Host/Broker/Impl/Resources.Designer.cs
- src/Linux/Host/Broker/Impl/Resources.resx
- src/Linux/Host/Broker/Impl/Services/AuthenticationOnlyMessage.cs
- src/Linux/Host/Broker/Impl/Services/LinuxAuthenticationService.cs
- src/Linux/Host/Broker/Impl/Services/Utility.cs
- src/Linux/Host/Broker/Impl/rtvsd.config.json
- src/Linux/Native/RunAsUser/src/main.cpp
- src/Linux/Native/RunAsUser/src/stdafx.h
> Check user group in linux and minor fixes

- src/Linux/Host/Broker/Impl/Services/LinuxSystemInfoService.cs
> Fix for WSL specific .net core issue.

- src/Common/Core/Impl/OS/IProcessServices.cs
- src/Host/Broker/Impl/Sessions/Session.cs
- src/Linux/Core/Impl/OS/KillProcessMessage.cs
- src/Linux/Core/Impl/OS/PathConstants.cs
- src/Linux/Core/Impl/OS/UnixProcess.cs
- src/Linux/Core/Impl/OS/UnixProcessServices.cs
- src/Linux/Host/Broker/Impl/Services/LinuxRHostProcessService.cs
- src/Linux/Host/Broker/Impl/Services/Utility.cs
- src/Linux/Native/RunAsUser/src/main.cpp
- src/Linux/Native/RunAsUser/src/stdafx.h
- src/Linux/Setup/DebPackage/build_rtvs_deb
- src/Windows/Core/Impl/OS/ProcessServices.cs
> Fixes issue where broker user cannot kill process running as another user.

- src/Host/Broker/Impl/Sessions/Session.cs
> Convert data writtern to stdout and stderr by child process of rhost to messages.

- src/Host/Client/Impl/Host/RemoteBrokerClient.cs
- src/Host/Client/Impl/Resources.Designer.cs
- src/Host/Client/Impl/Resources.resx
- src/Linux/Native/RunAsUser/src/main.cpp
- src/Linux/Setup/DebPackage/build_rtvs_deb
- src/Linux/Setup/DebPackage/postinst
- src/Linux/Setup/DebPackage/prerm
- src/Linux/Setup/rtvsd.service
https://github.com/Microsoft/RTVS/issues/3708
https://github.com/Microsoft/RTVS/issues/3698
> Adds system user and group during package installation.

- src/Host/Client/Impl/Host/BrokerConnectionInfo.cs
- src/Host/Client/Impl/Session/RSessionProvider.cs
- src/Package/Impl/Options/R/RToolsOptionsPage.cs
- src/Package/Impl/Options/R/Tools/RSettingsImplementation.cs
- src/Package/Impl/Resources.Designer.cs
- src/Package/Impl/Resources.resx
- src/R/Components/Impl/ConnectionManager/Connection.cs
- src/R/Components/Impl/Settings/IRSettings.cs
- src/Windows/Host/Client/Impl/Program.cs
- src/Windows/Host/Client/Test/Fixtures/RemoteBrokerMethodFixture.cs
- src/Windows/Host/Client/Test/Session/RSessionProviderTest.cs
- src/Windows/Host/Client/Test/Session/RSessionTest.cs
- src/Windows/Markdown/Editor/Impl/Preview/Code/EvalSession.cs
- src/Windows/R/Components/Impl/ConnectionManager/Implementation/ConnectionManager.cs
- src/Windows/R/Components/Impl/Information/HostLoadIndicatorViewModel.cs
- src/Windows/R/Components/Test/Stubs/RSettingsStub.cs
- src/Windows/R/Editor/Test/Utility/TestRSettings.cs
And #3716 RHost name for live markdown is weird
> #3709 Provide an option to turn off host load indicator

- loc/lcl/ITA/Microsoft.R.Host.Client.dll.lcl
LEGO: Pull request from lego/hb_835_20170718204632640 to Release/1_0 with localized lcls
> LEGO: Pull request from lego/hb_835_20170718204632640 to Release/1_0

- loc/lcl/PTB/Microsoft.R.Host.Client.dll.lcl
LEGO: Pull request from lego/hb_835_20170719024516896 to Release/1_0 with localized lcls
> LEGO: Pull request from lego/hb_835_20170719024516896 to Release/1_0

- loc/lcl/CHS/Microsoft.R.Host.Client.dll.lcl
LEGO: Pull request from lego/hb_835_20170719144520981 to Release/1_0 with localized lcls
> LEGO: Pull request from lego/hb_835_20170719144520981 to Release/1_0

- loc/lcl/JPN/Microsoft.R.Host.UserProfile.exe.lcl
LEGO: Pull request from lego/hb_835_20170720144518004 to Release/1_0 with localized lcls
> LEGO: Pull request from lego/hb_835_20170720144518004 to Release/1_0

- loc/lcl/FRA/Microsoft.R.Host.Client.dll.lcl
LEGO: Pull request from lego/hb_835_20170720204527577 to Release/1_0 with localized lcls
> LEGO: Pull request from lego/hb_835_20170720204527577 to Release/1_0

- src/Host/Client/Impl/Definitions/IRContext.cs
> Reverting a previous change, since the underlying global context issue was fixed

- src/Host/Broker/Impl/Pipes/WebSocketPipeAction.cs
- src/Host/Broker/Impl/Resources.Designer.cs
- src/Host/Broker/Impl/Resources.resx
- src/Host/Broker/Impl/Sessions/Session.cs
- src/Host/Broker/Impl/Sessions/SessionsController.cs
> Fix for crash on disconnect.

- src/Common/Core/Impl/Services/IServiceManager.cs
- src/Common/Core/Impl/Services/ServiceManager.cs
- src/Common/Core/Impl/Services/ServiceManagerExtensions.cs
- src/Common/Core/Test/Services/ServiceManagerTests.cs
- src/Package/Test/Sql/SProcPublisherTest.cs
- src/Windows/Host/Client/Test/Fixtures/RemoteBrokerMethodFixture.cs
- src/Windows/Markdown/Editor/Test/Preview/BrowserViewTest.cs
- Address CR comments
- Fix RemoteBrokerMethodFixture
> Editor and Service Manager fixes

- src/Host/Client/Impl/rtvs/R/grid.R
- src/Package/Test/DataInspect/EvaluationWrapperTest.cs
- src/Package/TestApp/Data/GridDataTest.cs
> Fix for grid row names.

- loc/lcl/TRK/Microsoft.VisualStudio.R.Package.dll.lcl
LEGO: Pull request from lego/hb_835_20170802144531489 to Release/1_0 with localized lcls
> LEGO: Pull request from lego/hb_835_20170802144531489 to Release/1_0

- src/Common/Core/Impl/Extensions/RandomExtensions.cs
- src/Host/Client/Impl/Blobs/DataTransferSession.cs
- src/Host/Client/Impl/BrokerServices/IRemotingWebServer.cs
- src/Host/Client/Impl/BrokerServices/WebService.cs
- src/Host/Client/Impl/Host/BrokerClient.cs
- src/Host/Client/Impl/Host/RemoteBrokerClient.cs
- src/Host/Client/Impl/Session/RSessionEvaluationCommands.cs
- src/Host/Client/Impl/Session/RSessionProvider.cs
- src/Windows/Host/Client/Impl/BrokerServices/LocalStaticFileServer.cs
- src/Windows/Host/Client/Impl/BrokerServices/RemoteStaticFileServer.cs
- src/Windows/Host/Client/Impl/BrokerServices/RemotingWebServer.cs
- src/Windows/Host/Client/Impl/BrokerServices/StaticFileServerBase.cs
- src/Windows/Host/Client/Impl/BrokerServices/WebServer.cs
- src/Windows/Host/Client/Impl/Microsoft.R.Host.Client.Windows.csproj
- src/Windows/Host/Client/Impl/Resources.Designer.cs
- src/Windows/Host/Client/Impl/Resources.resx
> Adds local and remote static file web server.

- src/Host/Broker/Impl/Resources.Designer.cs
- src/Host/Broker/Impl/Resources.resx
- src/Host/Broker/Impl/Sessions/SessionsController.cs
- src/Host/Client/Impl/Extensions/AboutHostExtensions.cs
> Ignore delete if session is not found

- loc/lcl/CHS/Microsoft.R.Interpreters.Windows.dll.lcl
- loc/lcl/KOR/Microsoft.R.Containers.Windows.dll.lcl
- loc/lcl/KOR/Microsoft.R.Host.Broker.Windows.exe.lcl
- loc/lcl/PLK/Microsoft.R.Editor.Windows.dll.lcl
- loc/lcl/RUS/Microsoft.Markdown.Editor.Windows.dll.lcl
LEGO: Pull request from lego/hb_835_20170814095849547 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170814095849547 to master

- src/Containers/Impl/Docker/LocalDockerContainer.cs
- src/Containers/Impl/Docker/LocalDockerService.cs
- src/Containers/Impl/IContainer.cs
- src/Linux/Containers/Impl/Docker/LinuxDockerService.cs
- src/Linux/Setup/rtvsd.service
- src/Package/Impl/Logging/OutputWindowLog.cs
- src/Package/Impl/Sql/Publish/SProcPublisher.cs
- src/Windows/Containers/Impl/Docker/WindowsDockerService.cs
- src/Windows/Setup/RemoteServices/Assemblies.wxi
- src/Windows/Setup/RemoteServices/Product.wxs
> Adding Output writer to containers.

- .gitignore
- src/Host/Client/Impl/Extensions/AboutHostExtensions.cs
- src/Package/Impl/Options/R/RToolsOptionsPage.cs
- src/Package/Impl/Resources.Designer.cs
- src/Package/Impl/Resources.resx
- src/R/Editor/Impl/Formatting/RangeFormatter.cs
- src/Windows/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveEvaluator.cs
- src/Windows/R/Components/Impl/Plots/Implementation/Commands/PlotHistoryCutCopyCommand.cs
- src/Windows/R/Components/Impl/Plots/Implementation/RPlotHistoryVisualComponent.cs
- src/Windows/R/Components/Impl/Plots/Implementation/View/RPlotHistoryControl.xaml.cs
#3832 Occasionally Plot History toolbar buttons are disabled
- notify container about selection change
#3636 Cannot change working directory while switching between linux remote and windows local 
- remove directory from options and don't set it on the host.
+ couple minor fixes
We can discuss if it is worth storing directory per connection. Not sure if it necessary....
> #3636  #3832

- src/Host/Broker/Impl/Resources.Designer.cs
- src/Host/Broker/Impl/Resources.resx
- src/Host/Broker/Impl/Startup/Startup.cs
- src/Windows/Core/Impl/IO/NamedPipeServerStreamFactory.cs
- src/Windows/Core/Impl/Microsoft.R.Common.Core.Windows.csproj
- src/Windows/Host/Broker/Impl/Microsoft.R.Host.Broker.Windows.csproj
- src/Windows/Host/Broker/Impl/Resources.Designer.cs
- src/Windows/Host/Broker/Impl/Resources.resx
- src/Windows/Host/Broker/Impl/Startup/WindowsStartup.cs
- src/Windows/Host/Broker/Impl/UserProfile/UserProfileManager.cs
> Switching Userprofile code to use NamedPipeServerStream from .net framework 4.6

- src/Host/Broker/Impl/Sessions/Session.cs
- src/Linux/Setup/DebPackage/control.m4
> Add lshw as a dependency.

- src/Containers/Impl/Docker/IDockerService.cs
- src/Containers/Impl/Docker/LocalDockerContainer.cs
- src/Containers/Impl/Docker/LocalDockerService.cs
- src/Containers/Impl/IContainer.cs
- src/Containers/Impl/IContainerService.cs
- src/Windows/Containers/Test/WindowsContainerServiceTest.cs
> Adds host port property to containers.

- src/Windows/Setup/RemoteServices/Product.wxs
> Set flag to run broker as service on remote.

- loc/lcl/ESN/Microsoft.R.Editor.dll.lcl
- loc/lcl/ESN/Microsoft.R.Host.Broker.dll.lcl
- loc/lcl/ESN/Microsoft.R.Host.Client.dll.lcl
- loc/lcl/PLK/Microsoft.R.Editor.dll.lcl
- loc/lcl/PLK/Microsoft.R.Host.Broker.dll.lcl
- loc/lcl/PLK/Microsoft.R.Host.Client.dll.lcl
LEGO: Pull request from lego/hb_835_20170817204545725 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170817204545725 to master

- loc/lcl/PTB/Microsoft.R.Editor.dll.lcl
- loc/lcl/PTB/Microsoft.R.Host.Broker.dll.lcl
- loc/lcl/PTB/Microsoft.R.Host.Client.dll.lcl
LEGO: Pull request from lego/hb_835_20170818025938176 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170818025938176 to master

- loc/lcl/JPN/Microsoft.R.Editor.dll.lcl
- loc/lcl/JPN/Microsoft.R.Host.Broker.dll.lcl
- loc/lcl/JPN/Microsoft.R.Host.Client.dll.lcl
- loc/lcl/JPN/Microsoft.VisualStudio.R.Package.dll.lcl
- loc/lcl/KOR/Microsoft.R.Editor.dll.lcl
- loc/lcl/KOR/Microsoft.R.Host.Broker.dll.lcl
- loc/lcl/KOR/Microsoft.R.Host.Client.dll.lcl
LEGO: Pull request from lego/hb_835_20170818084721293 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170818084721293 to master

- src/Package/Impl/Repl/Commands/ReplCommandController.cs
- src/Windows/Markdown/Editor/Impl/Microsoft.Markdown.Editor.Windows.csproj
- src/Windows/Markdown/Editor/Impl/Preview/Browser/BrowserView.cs
- src/Windows/Markdown/Editor/Impl/Preview/Browser/DocumentRenderer.cs
- src/Windows/Markdown/Editor/Impl/Preview/Code/HtmlFormatter.cs
- src/Windows/Markdown/Editor/Impl/Preview/Code/RCodeBlockRenderer.cs
- src/Windows/Markdown/Editor/Impl/Preview/Code/RCodeEvaluator.cs
- src/Windows/Markdown/Editor/Test/Files/Preview/03.rmd
- src/Windows/Markdown/Editor/Test/Files/Preview/03.rmd.html
- src/Windows/Markdown/Editor/Test/Microsoft.Markdown.Editor.Test.csproj
- src/Windows/Markdown/Editor/Test/Preview/RendererTest.cs
- src/Windows/R/Editor/Impl/Completions/RCompletionSet.cs
- Port perf fixes from release/1_0
- #3847 Code block not recognized as R should be output as text
> #3847 + port performance fix

- src/Containers/Impl/ContainerServiceNotInstalledException.cs
- src/Containers/Impl/ContainerServiceNotRunningException.cs
- src/Containers/Impl/Docker/LocalDocker.cs
- src/Containers/Impl/Docker/LocalDockerService.cs
- src/Linux/Containers/Impl/Docker/LinuxDockerService.cs
- src/Linux/Containers/Impl/Resources.Designer.cs
- src/Linux/Containers/Impl/Resources.resx
- src/Windows/Containers/Impl/Docker/WindowsDockerService.cs
- src/Windows/Containers/Impl/Microsoft.R.Containers.Windows.csproj
- src/Windows/Containers/Impl/Resources.Designer.cs
- src/Windows/Containers/Impl/Resources.resx
> Fixes to local docker service

- src/Windows/Core/Impl/OS/Win32Process.cs
> Fix for RHost connection regression.

- loc/lcl/CHT/Microsoft.R.Host.Client.dll.lcl
LEGO: Pull request from lego/hb_835_20170828084510920 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170828084510920 to master

- src/Host/Broker/Impl/Extensions/InterpreterExtensions.cs
- src/Host/Broker/Impl/Sessions/SessionsController.cs
> Select the latest version of R by default.

- src/Host/Broker/Impl/About/AboutController.cs
- src/Windows/Host/Broker/Impl/Startup/Program.cs
> Minor bug fixes

- src/Containers/Impl/Docker/LocalDockerService.cs
- src/Linux/Host/Broker/Impl/rtvsd.config.json
- src/Linux/Setup/DebPackage/control.m4
- src/Linux/Setup/DebPackage/postinst
- src/Linux/Setup/DebPackage/rtvsd.8
- src/Windows/Containers/Impl/Docker/WindowsDockerService.cs
1. RTVS daemon installation uses the snakeoil pem and key as the default self-signed SSL certificate.
2. Fix and updates to container build.
> Minor fixes and improvements

- src/Host/Broker/Impl/Resources.Designer.cs
- src/Host/Broker/Impl/Resources.resx
- src/Host/Broker/Impl/Security/TlsConfiguration.cs
> Log critical failure when SSL cert cannot be loaded.

- loc/lcl/ITA/Microsoft.R.Host.Broker.dll.lcl
LEGO: Pull request from lego/hb_835_20170910204510281 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170910204510281 to master

- loc/lcl/CHT/Microsoft.R.Host.Broker.dll.lcl
LEGO: Pull request from lego/hb_835_20170911084514421 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170911084514421 to master

- loc/lcl/CHS/Microsoft.R.Host.Broker.dll.lcl
- loc/lcl/PLK/Microsoft.R.Host.Broker.dll.lcl
- loc/lcl/TRK/Microsoft.R.Host.Broker.dll.lcl
LEGO: Pull request from lego/hb_835_20170911144510109 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170911144510109 to master

- loc/lcl/PTB/Microsoft.R.Host.Broker.dll.lcl
LEGO: Pull request from lego/hb_835_20170911204503842 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170911204503842 to master

- loc/lcl/DEU/Microsoft.R.Host.Broker.dll.lcl
- loc/lcl/JPN/Microsoft.R.Host.Broker.dll.lcl
LEGO: Pull request from lego/hb_835_20170912084506542 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170912084506542 to master

- src/Windows/R/Components/Impl/ContainerManager/Implementation/ViewModel/ContainerManagerViewModel.cs
> Fixes stop and delete container.

- loc/lcl/FRA/Microsoft.R.Host.Broker.dll.lcl
- loc/lcl/RUS/Microsoft.R.Host.Broker.dll.lcl
LEGO: Pull request from lego/hb_835_20170913204505319 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170913204505319 to master

- loc/lcl/CHS/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/CHT/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/DEU/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/JPN/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/PLK/Microsoft.R.Components.Windows.dll.lcl
LEGO: Pull request from lego/hb_835_20170914144508615 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170914144508615 to master

- loc/lcl/ESN/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/FRA/Microsoft.R.Host.Broker.dll.lcl
- loc/lcl/ITA/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/PTB/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/RUS/Microsoft.R.Host.Broker.dll.lcl
- loc/lcl/TRK/Microsoft.R.Components.Windows.dll.lcl
LEGO: Pull request from lego/hb_835_20170915024509846 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170915024509846 to master

- loc/lcl/RUS/Microsoft.R.Components.Windows.dll.lcl
LEGO: Pull request from lego/hb_835_20170915204514381 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170915204514381 to master

- src/Host/Client/Impl/Host/BrokerClient.cs
- src/Host/Client/Impl/Session/RSessionProvider.cs
- src/Windows/R/Components/Impl/ConnectionManager/Implementation/ConnectionManager.cs
- src/Windows/R/Components/Impl/ContainerManager/Implementation/View/ContainerManagerControl.xaml
- src/Windows/R/Components/Impl/Resources.Designer.cs
- src/Windows/R/Components/Impl/Resources.resx
- Address CR comments
- Fix #3993: RSessionProvider.Connected == true when no connection is active
- Fix #3988: Can't connect to the second container after first container is stopped
> Container manager bug fixes

- src/R/Components/Impl/Containers/ContainersStatus.cs
- src/R/Components/Impl/Containers/IContainerManager.cs
- src/R/Components/Impl/Containers/Implementation/ContainerManager.cs
- src/R/Wpf/Impl/Controls/Watermark.cs
- src/Windows/Containers/Impl/Docker/WindowsDockerService.cs
- src/Windows/R/Components/Impl/ContainerManager/Implementation/View/ContainerManagerControl.xaml
- src/Windows/R/Components/Impl/ContainerManager/Implementation/View/ContainerManagerControl.xaml.cs
- src/Windows/R/Components/Impl/ContainerManager/Implementation/ViewModel/ContainerManagerViewModel.cs
- src/Windows/R/Components/Impl/Resources.Designer.cs
- src/Windows/R/Components/Impl/Resources.resx
> Fix #3980: Show watermark that docker isn't installed on Containers window instead of UI

- src/Common/Core/Impl/Output/IOutputService.cs
- src/Common/Core/Test/Fakes/Shell/TestOutputService.cs
- src/Containers/Impl/Docker/LocalDockerService.cs
- src/Package/Impl/Packages/R/RPackage.cs
- src/Package/Impl/Shell/Services/VsOutputService.cs
- src/Windows/R/Components/Impl/ContainerManager/Implementation/View/ContainerManagerControl.xaml
- src/Windows/R/Components/Impl/ContainerManager/Implementation/View/ContainerManagerControl.xaml.cs
- src/Windows/R/Components/Impl/ContainerManager/Implementation/ViewModel/ContainerManagerViewModel.cs
- src/Windows/R/Components/Impl/Resources.Designer.cs
- src/Windows/R/Components/Impl/Resources.resx
- Fix #4004: NRE when creating R project
- Fix #4001: Delete container should show confirmation prompt
- Fix #3997: Container control buttons don't have proper background
- Fix #3981: NRE while invoking workspaces or repl on a clean install machine.
- Fix #3978: UI issues in Create Container panel
> Containers bug fixes

- loc/lcl/CHT/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/JPN/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/RUS/Microsoft.R.Components.Windows.dll.lcl
LEGO: Pull request from lego/hb_835_20170921144509627 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170921144509627 to master

- src/Common/Core/Impl/Net/PortUtil.cs
- src/Containers/Impl/BuildImageParameters.cs
- src/Containers/Impl/Docker/LocalDockerService.cs
- src/R/Components/Impl/Containers/IContainerManager.cs
- src/R/Components/Impl/Containers/Implementation/ContainerManager.cs
- src/Windows/R/Components/Impl/ContainerManager/Implementation/View/ContainerManagerControl.xaml
- src/Windows/R/Components/Impl/ContainerManager/Implementation/ViewModel/ContainerManagerViewModel.cs
- src/Windows/R/Components/Impl/ContainerManager/Implementation/ViewModel/CreateLocalDockerViewModel.cs
- src/Windows/R/Components/Impl/Resources.Designer.cs
- src/Windows/R/Components/Impl/Resources.resx
> Auto select random host port for a container

- loc/lcl/FRA/Microsoft.VisualStudio.R.Package.dll.lcl
- loc/lcl/JPN/Microsoft.VisualStudio.R.Package.dll.lcl
- loc/lcl/RUS/Microsoft.VisualStudio.R.Package.dll.lcl
- loc/lcl/TRK/Microsoft.VisualStudio.R.Package.dll.lcl
LEGO: Pull request from lego/hb_835_20170926034225239 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170926034225239 to master

- loc/lcl/KOR/Microsoft.R.Host.Client.dll.lcl
LEGO: Pull request from lego/hb_835_20170928084508656 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170928084508656 to master

- loc/lcl/CHS/Microsoft.R.Host.Client.dll.lcl
- loc/lcl/DEU/Microsoft.R.Host.Client.dll.lcl
- loc/lcl/ESN/Microsoft.R.Host.Client.dll.lcl
- loc/lcl/JPN/Microsoft.R.Host.Client.dll.lcl
- loc/lcl/PLK/Microsoft.R.Host.Client.dll.lcl
- loc/lcl/TRK/Microsoft.R.Host.Client.dll.lcl
LEGO: Pull request from lego/hb_835_20170928144511103 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170928144511103 to master

- loc/lcl/CSY/Microsoft.R.Host.Client.dll.lcl
LEGO: Pull request from lego/hb_835_20170928204511628 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170928204511628 to master

- loc/lcl/PTB/Microsoft.R.Host.Client.dll.lcl
LEGO: Pull request from lego/hb_835_20170929024506752 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170929024506752 to master

- loc/lcl/CHT/Microsoft.R.Host.Client.dll.lcl
LEGO: Pull request from lego/hb_835_20170929144507073 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20170929144507073 to master

- loc/lcl/ITA/Microsoft.R.Components.Windows.dll.lcl
LEGO: Pull request from lego/hb_835_20171001144514634 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20171001144514634 to master

- loc/lcl/CHT/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/JPN/Microsoft.R.Components.Windows.dll.lcl
LEGO: Pull request from lego/hb_835_20171002084507494 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20171002084507494 to master

- loc/lcl/TRK/Microsoft.R.Components.Windows.dll.lcl
LEGO: Pull request from lego/hb_835_20171002144508222 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20171002144508222 to master

- loc/lcl/CSY/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/DEU/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/FRA/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/FRA/Microsoft.R.Host.Client.dll.lcl
- loc/lcl/PLK/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/RUS/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/RUS/Microsoft.R.Host.Client.dll.lcl
LEGO: Pull request from lego/hb_835_20171002204509337 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20171002204509337 to master

- src/Package/Impl/Microsoft.VisualStudio.R.Package.csproj
- src/R/Components/Impl/Containers/Implementation/ContainerManager.cs
- src/R/Components/Impl/Containers/Implementation/DockerfileTemplate
- src/R/Components/Impl/Microsoft.R.Components.csproj
- src/Windows/R/Components/Impl/ContainerManager/Implementation/View/ContainerManagerControl.xaml
> Moving docker file contents to a template file.

- src/Host/Client/Impl/Host/RemoteBrokerClient.cs
> Disable warning on localhost connections with self signed certs.

- src/Windows/R/Components/Impl/ConnectionManager/Commands/SwitchToConnectionCommand.cs
- src/Windows/R/Components/Impl/ContainerManager/Implementation/View/ContainerManagerControl.xaml
- src/Windows/R/Components/Impl/ContainerManager/Implementation/View/ContainerManagerControl.xaml.cs
- src/Windows/R/Components/Impl/ContainerManager/Implementation/ViewModel/ContainerManagerViewModel.cs
- src/Windows/R/Components/Impl/Resources.Designer.cs
- src/Windows/R/Components/Impl/Resources.resx
- Add network exception handling 
- Fixed button styling
- Added "Workspaces..." button
- Made double-click on container name start container and switch to its default connection
> More UI fixes

- loc/lcl/CHS/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/KOR/Microsoft.R.Components.Windows.dll.lcl
LEGO: Pull request from lego/hb_835_20171009084511525 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20171009084511525 to master

- loc/lcl/CSY/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/DEU/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/ITA/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/RUS/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/TRK/Microsoft.R.Components.Windows.dll.lcl
LEGO: Pull request from lego/hb_835_20171009144512918 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20171009144512918 to master

- loc/lcl/ESN/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/FRA/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/PLK/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/PTB/Microsoft.R.Components.Windows.dll.lcl
LEGO: Pull request from lego/hb_835_20171009204515086 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20171009204515086 to master

- src/R/Components/Impl/Containers/Implementation/DockerfileTemplate
1. Image updated to the final image name.
2. Removing installation of rtvsd. This will be done in the base image.
> Updating dockerfile image name.

- src/Linux/Core/Impl/OS/PathConstants.cs
- src/Linux/Host/Broker/Impl/Services/LinuxRHostProcessService.cs
- src/Linux/Host/Broker/Impl/Services/Utility.cs
This will be needed to run VSCode R on linux
#4141
> Local linux RHost scenario for VSCode.

- loc/lcl/CHS/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/CHT/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/DEU/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/ESN/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/ITA/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/JPN/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/TRK/Microsoft.R.Components.Windows.dll.lcl
LEGO: Pull request from lego/hb_835_20171018144509357 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20171018144509357 to master

- loc/lcl/PLK/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/PTB/Microsoft.R.Components.Windows.dll.lcl
- loc/lcl/TRK/Microsoft.R.Components.Windows.dll.lcl
LEGO: Pull request from lego/hb_835_20171018204514824 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20171018204514824 to master

- loc/lcl/KOR/Microsoft.R.Components.Windows.dll.lcl
LEGO: Pull request from lego/hb_835_20171023084510113 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20171023084510113 to master

- loc/lcl/ESN/Microsoft.R.Components.Windows.dll.lcl
LEGO: Pull request from lego/hb_835_20171023144515069 to master with localized lcls
> LEGO: Pull request from lego/hb_835_20171023144515069 to master

- src/Package/Impl/Resources.resx
I was changing some Lint settings and saw `Flas`.
> Fixed typo

- src/Languages/Editor/Impl/Completions/EditorCompletionEntry.cs
- src/Windows/R/Editor/Impl/Completions/RCompletion.cs
> PERF: prevent exceptions in the completion list binding

- loc/lcl/DEU/Microsoft.VisualStudio.R.Package.dll.lcl
LEGO: Pull request from lego/hb_835_20180103154512447 to Release/1_3 with localized lcls
> LEGO: Pull request from lego/hb_835_20180103154512447 to Release/1_3

- src/Windows/R/Components/Impl/ContainerManager/Implementation/ViewModel/ContainerManagerViewModel.cs
> Deleting a container deletes the stored credentials.

- src/Package/Impl/Expansions/ExpansionClient.cs
> Fixes argument out of range with snippets.

- src/Common/Core/Test/Microsoft.Common.Core.Test.csproj
- src/Host/Broker/Impl/Microsoft.R.Host.Broker.csproj
- src/Package/Impl/Microsoft.VisualStudio.R.Package.csproj
- src/Package/Impl/Properties/AssemblyInfo.cs
- src/Package/Impl/project.json
- src/UnitTests/Core/Impl/Microsoft.UnitTests.Core.csproj
- src/UnitTests/app.config
- src/Windows/Host/Broker/Impl/Microsoft.R.Host.Broker.Windows.csproj
- src/Windows/R/Components/Impl/project.json
- src/Windows/R/Components/Test/Microsoft.R.Components.Windows.Test.csproj
- src/Windows/UnitTests/Core/Impl/Microsoft.UnitTests.Core.Windows.csproj
- src/Windows/UnitTests/Core/Impl/VsPaths.cs
- Fix VsPaths to find correct version of VS
- Remove explicit reference to System.ValueTuple
> Couple of unit test fixes

- src/Package/Impl/DataInspect/Commands/DeleteVariableCommand.cs
- src/Package/Impl/DataInspect/VariableViewModel.cs
- src/Package/Impl/DataInspect/VisualGrid/GridPoints.cs
- src/R/Core/Impl/Classification/RClassificationTypes.cs
- src/R/Core/Impl/Tokens/RTokenSubType .cs
- src/R/Core/Impl/Tokens/RTokenizer.cs
- src/R/Editor/Impl/Completions/Providers/ParameterNameCompletionProvider.cs
- src/R/Editor/Impl/Completions/RCompletionEngine.cs
- src/Windows/Core/Impl/project.json
- src/Windows/Host/Broker/Impl/project.json
- src/Windows/R/Components/Impl/InteractiveWorkflow/Implementation/InteractiveWindowWriter.cs
- src/Windows/R/Editor/Impl/Classification/ClassificationDefinitions.cs
- src/Windows/R/Editor/Impl/Classification/RClassificationNameProvider.cs
#4264 "Space around =" editor setting is recognized in the REPL
#4270 Updating progress bar erases existing output lines in REPL
#4271 Syntax highlighting for functions and operators
#4275 RData grid view: can't select column for sorting after horizontal scroll in wide data frames
Unfortunately, hard to add new tests b/c of VS issues with xUnit.
> Fixes for 15.7

- loc/lcl/PTB/Microsoft.VisualStudio.R.Package.dll.lcl
LEGO: Pull request from lego/hb_835_20180221034604161 to Release/1_3 with localized lcls
> LEGO: Pull request from lego/hb_835_20180221034604161 to Release/1_3

- loc/lcl/TRK/Microsoft.R.Editor.dll.lcl
LEGO: Pull request from lego/hb_835_20180221220305118 to Release/1_3 with localized lcls
> LEGO: Pull request from lego/hb_835_20180221220305118 to Release/1_3

- loc/lcl/RUS/Microsoft.R.Host.Broker.dll.lcl
LEGO: Pull request from lego/hb_835_20180830111320231 to Release/1_3 with localized lcls
> LEGO: Pull request from lego/hb_835_20180830111320231 to Release/1_3

- loc/lcl/CSY/Microsoft.R.Host.Broker.dll.lcl
LEGO: Pull request from lego/hb_835_20180831214525925 to Release/1_3 with localized lcls
> LEGO: Pull request from lego/hb_835_20180831214525925 to Release/1_3
